// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file legacy_shim.cpp
 * @brief Compatibility shim: maps legacy `bnetd_*` Lua globals → `pvpgn.*` API (R349).
 *
 * Plugins written against the old `luafunctions.cpp` API used globals like
 * `bnetd_send_message`, `bnetd_get_account_info`, etc.  This shim installs
 * thin Lua wrappers that forward those calls to the new `pvpgn.*` namespace,
 * allowing old plugins to run without modification.
 *
 * ### Migration table
 * | Legacy (bnetd_*)              | New (pvpgn.*)                    |
 * |-------------------------------|----------------------------------|
 * | bnetd_send_message(u, msg)    | pvpgn.send_chat(u, msg)          |
 * | bnetd_get_account_info(u)     | pvpgn.get_account(u)             |
 * | bnetd_ban_user(u, reason)     | pvpgn.ban_account(u, reason)     |
 * | bnetd_kick_user(u, reason)    | pvpgn.kick_user(u, reason)       |
 * | bnetd_broadcast(ch, msg)      | pvpgn.broadcast(ch, msg)         |
 * | bnetd_log(level, msg)         | pvpgn.log(level, msg)            |
 *
 * ### Usage
 * Call `install_legacy_shim(lua)` after `register_v2_api()` has been called.
 * The shim is a no-op if `pvpgn` table is not present.
 */

#include "infra/scripting/legacy_shim.hpp"

namespace pvpgn::infra::scripting {

namespace {

/// Lua source for the legacy compatibility shim.
/// Each bnetd_* global is mapped to the corresponding pvpgn.* function.
/// The shim is guarded so it only installs if the pvpgn table exists.
constexpr const char* k_legacy_shim_code = R"lua(
-- PvPGN Lua API v2 legacy compatibility shim
-- Maps old bnetd_* globals to the new pvpgn.* namespace.
-- Auto-generated by legacy_shim.cpp — do not edit manually.

if type(pvpgn) ~= "table" then
    -- pvpgn API v2 not loaded; shim cannot be installed.
    return
end

-- bnetd_send_message(username, message) → pvpgn.send_chat(username, message)
bnetd_send_message = function(username, message)
    return pvpgn.send_chat(username, message)
end

-- bnetd_get_account_info(username) → pvpgn.get_account(username)
bnetd_get_account_info = function(username)
    return pvpgn.get_account(username)
end

-- bnetd_ban_user(username, reason) → pvpgn.ban_account(username, reason)
bnetd_ban_user = function(username, reason)
    return pvpgn.ban_account(username, reason or "")
end

-- bnetd_kick_user(username, reason) → pvpgn.kick_user(username, reason)
bnetd_kick_user = function(username, reason)
    return pvpgn.kick_user(username, reason or "")
end

-- bnetd_broadcast(channel, message) → pvpgn.broadcast(channel, message)
bnetd_broadcast = function(channel, message)
    return pvpgn.broadcast(channel, message)
end

-- bnetd_log(level, message) → pvpgn.log(level, message)
bnetd_log = function(level, message)
    return pvpgn.log(level, message)
end
)lua";

} // anonymous namespace

// ============================================================================
// install_legacy_shim
// ============================================================================

void install_legacy_shim(sol::state& lua) {
    lua.script(k_legacy_shim_code);
}

} // namespace pvpgn::infra::scripting
