repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(files/|lua/ghost/maplist\.txt)'
      - id: end-of-file-fixer
        exclude: '^(files/|conf/i18n/)'
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: '^(conf/.*\.win32|appveyor\.yml)'
      - id: check-added-large-files
        args: ['--maxkb=500']
        exclude: '^files/'

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c, c++]
        args: ['-style=file']

  - repo: https://github.com/cheshirekow/cmake_format
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: ['--config-file=.cmake-format.yaml']
      - id: cmake-lint
        args: ['--config-file=.cmake-format.yaml']
