// SPDX-License-Identifier: GPL-2.0-or-later
// wol_game_commands.cpp — WoL joingame/gameopt/startg/host/invmsg/invdel handlers
// Auto-generated by scripts/dev/split_handle_wol.py (plan 15 §5)
#include "wol_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		int _handle_joingame_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char _temp[MAX_IRC_MESSAGE_LEN];

			std::memset(_temp, 0, sizeof(_temp));

			/**
			*  Basically this has 2 modes, Join Game and Create Game output is pretty much
			*  the same...input and output of JOINGAME is listed below. By the way, there is a
			*  hack in here, for Red Alert 1, it use's JOINGAME for some reason to join a lobby channel.
			*
			*   Here is WOLv1 input expected:
			*   JOINGAME [#Game_channel_name] [MinPlayers] [MaxPlayers] [channelType] 1 1 [gameIsTournament]
			*   Knowed channelTypes (0-chat, 1-cnc, 2-ra1, 3-racs, 4-raam, 5-solsurv... listed in tag.cpp)
			*
			*   Here is WOLv2 input expected:
			*   JOINGAME [#Game_channel_name] [MinPlayers] [MaxPlayers] [channelType] unknown unknown [gameIsTournament] [gameExtension] [password_optional]
			*
			*   Heres the output expected:
			*   user!WWOL@hostname JOINGAME [MinPlayers] [MaxPlayers] [channelType] unknown clanID [longIP] [gameIsTournament] :[#Game_channel_name]
			*/
			if ((numparams == 2) || (numparams == 3)) {
				char ** e;

				e = irc_get_listelems(params[0]);
				if ((e) && (e[0])) {
					char const * gamename = irc_convert_ircname(e[0]);
					//    		char * old_channel_name = NULL;
					t_game * game;
					t_game_type gametype;
					t_channel * channel;
					t_channel * old_channel = conn_get_channel(conn);
					char gamepass[MAX_GAMEPASS_LEN];

					std::memset(gamepass, 0, sizeof(gamepass));

					if ((conn_get_clienttag(conn) == CLIENTTAG_REDALERT_UINT)
						&& (channellist_find_channel_by_name(gamename, NULL, NULL) != NULL)
						&& (gamelist_find_game_available(gamename, conn_get_clienttag(conn), game_type_all) == NULL)) {
						/* BUG in Red Alert 1 v3.03e - forwarding to _handle_join_command */
						DEBUG0("BUG in RA1 v3.03e - forwarding to _handle_join_command");
						_handle_join_command(conn, numparams, params, text);
						if (e)
							irc_unget_listelems(e);
						return 0;
					}

					if (!(gamename) || !(game = gamelist_find_game_available(gamename, conn_get_clienttag(conn), game_type_all)))
					{
						irc_send(conn, ERR_GAMEHASCLOSED, std::string(std::string(e[0]) + " :Game channel has closed").c_str());

						if (e)
							irc_unget_listelems(e);

						return 0;
					}

					channel = game_get_channel(game);

					if (game_get_ref(game) == game_get_maxplayers(game))
					{
						irc_send(conn, ERR_CHANNELISFULL, std::string(std::string(e[0]) + " :Channel is full.").c_str());

						if (e)
							irc_unget_listelems(e);

						return 0;
					}

					if (channel_check_banning(channel, conn))
					{
						irc_send(conn, ERR_BANNEDFROMCHAN, std::string(std::string(e[0]) + " :You are banned from that channel.").c_str());
						
						if (e)
							irc_unget_listelems(e);

						return 0;
					}

					if (std::strcmp(game_get_pass(game), "") != 0)
					{
						if ((numparams == 3) && (params[2]) && (std::strcmp(params[2], game_get_pass(game)) == 0))
						{
							std::strcpy(gamepass, params[2]);
						}
						else
						{
							irc_send(conn, ERR_BADCHANNELKEY, std::string(std::string(e[0]) + ":Bad password").c_str());

							if (e)
								irc_unget_listelems(e);

							return 0;
						}
					}

					gametype = game_get_type(game);

					if ((conn_set_game(conn, gamename, gamepass, "", gametype, 0)) < 0)
					{
						irc_send(conn, ERR_GAMEHASCLOSED, std::string(std::string(e[0]) + " :JOINGAME failed").c_str());
					}
					else
					{
						/*conn_set_channel()*/
						channel = game_get_channel(game);
						conn_set_channel_var(conn, channel);
						channel_add_connection(channel, conn);
						channel = conn_get_channel(conn);

						if (channel != old_channel) {
							if (tag_check_wolv1(conn_get_clienttag(conn))) {
								/* WOLv1 JOINGAME message */
								std::sprintf(_temp, "%u %u %u 1 1 %u :%s", channel_get_min(channel), game_get_maxplayers(game), channel_wol_get_game_type(channel),
									((game_get_type(game) == game_type_ladder) ? 1 : 0), irc_convert_channel(channel, conn));
							}
							else {
								/* WOLv2 JOINGAME message with BATTLECLAN support */
								t_clan * clan = account_get_clan(conn_get_account(conn));
								unsigned int clanid = 0;

								if (clan)
									clanid = clan_get_clanid(clan);

								std::sprintf(_temp, "%u %u %u 1 %u %u %u :%s", channel_get_min(channel), game_get_maxplayers(game), channel_wol_get_game_type(channel),
									clanid, conn_get_addr(conn), ((game_get_type(game) == game_type_ladder) ? 1 : 0), irc_convert_channel(channel, conn));
							}

							channel_set_userflags(conn);
							/* we have to send the JOINGAME acknowledgement */
							channel_message_send(channel, message_wol_joingame, conn, _temp);

							irc_send_topic(conn, channel);

							irc_send_rpl_namreply(conn, channel);
						}
						else
						{
							irc_send(conn, ERR_GAMEHASCLOSED, std::string(std::string(e[0]) + " :JOINGAME failed").c_str());
						}
					}
				}
				if (e)
					irc_unget_listelems(e);
				return 0;
			}
			else if ((numparams >= 7)) {
				char ** e;

				eventlog(eventlog_level_debug, __FUNCTION__, "[** WOL **] JOINGAME: * Create * ({}, {})",
					params[0], params[1]);

				if ((numparams == 7)) {
					/* WOLv1 JOINGAME Create */
					std::snprintf(_temp, sizeof(_temp), "%s %s %s %s 0 %s :%s", params[1], params[2], params[3], params[4], params[6], params[0]);
				}
				/* WOLv2 JOINGAME Create */
				else if ((numparams >= 8)) {
					t_clan * clan = account_get_clan(conn_get_account(conn));
					unsigned int clanid = 0;

					if (clan)
						clanid = clan_get_clanid(clan);
					std::snprintf(_temp, sizeof(_temp), "%s %s %s %s %u %u %s :%s", params[1], params[2], params[3], params[4], clanid, conn_get_addr(conn), params[6], params[0]);
				}
				eventlog(eventlog_level_debug, __FUNCTION__, "[** WOL **] JOINGAME [Game Options] ({})", _temp);

				e = irc_get_listelems(params[0]);
				if ((e) && (e[0])) {
					char const * gamename = irc_convert_ircname(e[0]);
					t_game_type gametype;
					char gamepass[MAX_GAMEPASS_LEN];

					std::memset(gamepass, 0, sizeof(gamepass));

					if (std::strcmp(params[6], "1") == 0)
						gametype = game_type_ladder;
					else
						gametype = game_type_ffa;
					//    		    gametype = game_type_none;

					if ((numparams >= 8) && (params[8]))
					{
						std::snprintf(gamepass, sizeof gamepass, "%s", params[8]);
					}

					if ((!(gamename)) || ((conn_set_game(conn, gamename, gamepass, "", gametype, 0))<0)) {
						irc_send(conn, ERR_NOSUCHCHANNEL, ":JOINGAME failed"); /* FIXME: be more precise; what is the real error code for that? */
					}
					else {
						t_game * game = conn_get_game(conn);
						t_channel * channel = channel_create(gamename, gamename, 0, 0, 1, 1, prefs_v3::chanlog(), NULL, NULL, (prefs_v3::maxusers_per_channel() > 0) ? prefs_v3::maxusers_per_channel() : -1, 0, 0, 0);
						game_set_channel(game, channel);
						conn_set_channel_var(conn, channel);
						channel_add_connection(channel, conn);
						channel_set_userflags(conn);

						game_set_maxplayers(game, std::atoi(params[2]));

						channel_set_min(channel, std::atoi(params[1]));
						// HACK: Currently, this is the best way to set the channel game type...
						channel_wol_set_game_type(channel, std::atoi(params[3]));

						if (params[7])
							channel_wol_set_game_extension(channel, params[7]);
						else
							channel_wol_set_game_extension(channel, "0");

						// we have to send the JOINGAME acknowledgement
						message_send_text(conn, message_wol_joingame, conn, _temp);
						irc_send_topic(conn, channel);
						irc_send_rpl_namreply(conn, channel);
					}
				}
				if (e)
					irc_unget_listelems(e);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "JOINGAME :Not enough parameters");
			return 0;
		}

		int _handle_gameopt_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];

			/**
			*  Basically this has 2 modes as like in PRIVMSG - whisper and talk. What is in
			*  text is pretty much unknown, we just dump this to the client to deal with...
			*
			*	Heres the output expected (when gameopt is channel talk):
			*	user!WWOL@hostname GAMEOPT #game_channel_name :gameOptions
			*
			*	Heres the output expected (when gameopt is whispered):
			*	user!WWOL@hostname GAMEOPT sender_nick_name :gameOptions
			*/

			if ((numparams >= 1) && (params[0]) && (text)) {
				int i;
				char ** e;
				t_connection * user;
				t_channel * channel;

				e = irc_get_listelems(params[0]);
				/* FIXME: support wildcards! */

				for (i = 0; ((e) && (e[i])); i++) {
					if (e[i][0] == '#') {
						/* channel gameopt */
						if (channel = conn_get_channel(conn)) {
							channel_message_send(channel, message_type_gameopt_talk, conn, text);
						}
						else {
							std::snprintf(temp, sizeof(temp), "%s :No such channel", params[0]);
							irc_send(conn, ERR_NOSUCHCHANNEL, temp);
						}
					}
					else {
						/* user gameopt */
						if ((user = connlist_find_connection_by_accountname(e[i]))) {
							message_send_text(user, message_type_gameopt_whisper, conn, text);
						}
						else {
							std::snprintf(temp, sizeof(temp), "%s :No such nick", e[i]);
							irc_send(conn, ERR_NOSUCHNICK, temp);
						}
					}
				}
				if (e)
					irc_unget_listelems(e);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "GAMEOPT :Not enough parameters");
			return 0;
		}
		int _handle_startg_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char _temp_a[MAX_IRC_MESSAGE_LEN];
			t_channel * channel;
			t_game * game;

			/**
			*  Imput expected:
			*   STARTG [channel_name] [nick1](,nick2_optional)
			*
			*  Heres the output expected (this can have up-to 8 entries (ie 8 players):
			*  (we are assuming for this example that user1 is the game owner)
			*
			*   WOLv1:
			*   :user1!WWOL@hostname STARTG u :owner_ip gameNumber time_t
			*
			*   WOLv2:
			*   :user1!WWOL@hostname STARTG u :user1 xxx.xxx.xxx.xxx user2 xxx.xxx.xxx.xxx :gameNumber time_t
			*/

			if ((numparams >= 2) && (params[1])) {
				int i;

				std::memset(temp, 0, sizeof(temp));

				char ** e = irc_get_listelems(params[1]);
				/* FIXME: support wildcards! */

				if (!(game = conn_get_game(conn))) {
					ERROR0("conn has not game");
					irc_unget_listelems(e);
					return 0;
				}

				std::strcat(temp, ":");

				if (tag_check_wolv1(conn_get_clienttag(conn))) {
					t_connection * user;
					channel = conn_get_channel(conn);

					for (user = channel_get_first(channel); user; user = channel_get_next()) {
						char const * name = conn_get_chatname(user);
						if (std::strcmp(conn_get_chatname(conn), name) != 0) {
							std::snprintf(temp, sizeof(temp), "%s ", addr_num_to_ip_str(conn_get_addr(game_get_owner(game))));
						}
					}
				}
				else {
					for (i = 0; ((e) && (e[i])); i++) {
						t_connection * user;
						const char * addr = NULL;

						if ((user = connlist_find_connection_by_accountname(e[i]))) {
							addr = addr_num_to_ip_str(conn_get_addr(user));
						}
						std::snprintf(_temp_a, sizeof(_temp_a), "%s %s ", e[i], addr);
						std::strcat(temp, _temp_a);
					}
					std::strcat(temp, ":");
				}

				game_set_status(game, game_status_started);

				std::snprintf(_temp_a, sizeof(_temp_a), "%u %" PRId64, game_get_id(game), static_cast<std::int64_t>(game_get_start_time(game)));
				std::strcat(temp, _temp_a);

				for (i = 0; ((e) && (e[i])); i++) {
					t_connection * user;
					if ((user = connlist_find_connection_by_accountname(e[i]))) {
						message_send_text(user, message_wol_start_game, conn, temp);
					}
				}

				if (e)
					irc_unget_listelems(e);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "STARTG :Not enough parameters");
			return 0;
		}
		int _handle_host_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			t_connection * user;

			std::memset(temp, 0, sizeof(temp));

			if ((numparams >= 1) && (params[0])) {
				if ((user = connlist_find_connection_by_accountname(params[0]))) {
					std::snprintf(temp, sizeof(temp), ": %s", text);
					message_send_text(user, message_type_host, conn, temp);
				}
				else {
					std::snprintf(temp, sizeof(temp), "%s :No such nick", params[0]);
					irc_send(conn, ERR_NOSUCHNICK, temp);
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "HOST :Not enough parameters");
			return 0;
		}

		int _handle_invmsg_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char ** e;
			t_connection * user;
			int i;

			/**
			 *  Here is the imput expected:
			 *  INVMSG [channel] [unknown] [invited],[invited2_optional]
			 *  [unknown] can be 1 or 2
			 *
			 *  Here is the output expected:
			 *  :user!WWOL@hostname INVMSG [invited] [channel] [unknown]
			 */

			if ((numparams >= 3) && (params[0]) && (params[1]) && (params[2])) {
				std::memset(temp, 0, sizeof(temp));
				e = irc_get_listelems(params[2]);

				for (i = 0; ((e) && (e[i])); i++) {
					if ((user = connlist_find_connection_by_accountname(e[i]))) {
						std::snprintf(temp, sizeof(temp), "%s %s", params[0], params[1]);
						/* FIXME: set user to linvitelist! */
						message_send_text(user, message_type_invmsg, conn, temp);
					}
				}

				if (e)
					irc_unget_listelems(e);
			}
			else {
				irc_send(conn, ERR_NEEDMOREPARAMS, "INVMSG :Not enough parameters");
			}
			return 0;
		}

		int _handle_invdel_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/* FIXME: Not implemented yet */
			return 0;
		}

	}

}
