// SPDX-License-Identifier: GPL-2.0-or-later
// wol_internal.h — shared forward declarations for handle_wol/ sub-modules
// Auto-generated by scripts/dev/split_handle_wol.py (plan 15 §5)
#pragma once

#include "common/setup_before.h"
#include "handle_wol.h"

#include <cctype>
#include <cinttypes>
#include <cstdint>
#include <cstdlib>
#include <cstring>

#include <strings.h>
#include "common/irc_protocol.h"
#include "common/eventlog.h"
#include "common/bnethash.h"
#include "common/tag.h"
#include "common/util.h"
#include "common/list.h"
#include "common/addr.h"
#include "common/trans.h"
#include "common/xstring.h"

#include "common/packet.h"

#include "prefs_v3_shim.h"
#include "command.h"
#include "irc.h"
#include "account.h"
#include "account_wrap.h"
#include "command_groups.h"
#include "channel.h"
#include "message.h"
#include "tick.h"
#include "topic.h"
#include "server.h"
#include "friends.h"
#include "clan.h"
#include "game.h"
#include "anongame_wol.h"
#include "common/setup_after.h"

// IRC shared handlers (from irc/irc_internal.h via irc_commands.cpp)
#include "irc/irc_internal.h"


namespace pvpgn
{

	namespace bnetd
	{

		/* xstrdup-equivalent using new char[] for paired delete[] cleanup. */
		inline char* wol_strdup(char const* s)
		{
			if (!s) return nullptr;
			std::size_t n = std::strlen(s) + 1;
			char* r = new char[n];
			std::memcpy(r, s, n);
			return r;
		}

		// wol_user_commands.cpp (originally static — promoted via wol_internal.h)
		int _handle_user_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_pass_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_privmsg_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_list_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_quit_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_names_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_part_command(t_connection * conn, int numparams, char ** params, char * text);

		// wol_misc_commands.cpp (originally static — promoted via wol_internal.h)
		int _handle_cvers_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_verchk_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_apgar_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_serial_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_squadinfo_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_clanbyname_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_setopt_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_setcodepage_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_getcodepage_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_setlocale_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_getlocale_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_getinsider_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_finduser_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_finduserex_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_page_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_advertr_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_advertc_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_chanchk_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_getbuddy_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_addbuddy_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_delbuddy_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_userip_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_listsearch_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_rungsearch_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_highscore_command(t_connection * conn, int numparams, char ** params, char * text);

		// wol_game_commands.cpp (originally static — promoted via wol_internal.h)
		int _handle_joingame_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_gameopt_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_startg_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_host_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_invmsg_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_invdel_command(t_connection * conn, int numparams, char ** params, char * text);

	} // namespace bnetd

} // namespace pvpgn
