// SPDX-License-Identifier: GPL-2.0-or-later
// wol_misc_commands.cpp — WoL cvers/verchk/apgar/serial/squad/buddy/ladder handlers
// Auto-generated by scripts/dev/split_handle_wol.py (plan 15 §5)
#include "wol_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		int _handle_cvers_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_clienttag clienttag;

			/* Ignore command but set clienttag */

			/**
			*  Heres the imput expected:
			*  CVERS [oldvernum] [SKU]
			*
			*  SKU is specific number for any WOL client (Tiberian sun, RedAlert 2 etc.)
			*  This is the best way to set clienttag, because CVERS is the first command which
			*  client send to server.
			*/

			if (numparams == 2) {
				clienttag = tag_sku_to_uint(std::atoi(params[1]));
				if (clienttag != CLIENTTAG_WWOL_UINT)
					conn_set_clienttag(conn, clienttag);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "CVERS :Not enough parameters");
			return 0;
		}

		int _handle_verchk_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_clienttag clienttag;

			/**
			*  Heres the imput expected:
			*  vercheck [SKU] [version]
			*
			*  Heres the output expected:
			*
			*  1) Update non-existant:
			*  :[servername] 379 [username] :none none none 1 [SKU] NONREQ
			*  2) Update existant:
			*  :[servername] 379 [username] :none none none [oldversnum] [SKU] REQ
			*/

			if (numparams == 2)
			{
				clienttag = tag_sku_to_uint(std::atoi(params[0]));
				if (clienttag != CLIENTTAG_WWOL_UINT)
					conn_set_clienttag(conn, clienttag);

				std::string tmp(":none none none 1 " + std::string(params[0]) + " NONREQ");
				eventlog(eventlog_level_debug, __FUNCTION__, "[** WOL **] VERCHK {}", tmp.c_str());
				irc_send(conn, RPL_VERCHK_NONREQ, tmp.c_str());
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "VERCHK :Not enough parameters");

			return 0;
		}

		int _handle_apgar_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char * apgar = NULL;

			if ((numparams >= 1) && (params[0])) {
				apgar = params[0];
				conn_wol_set_apgar(conn, apgar);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "APGAR :Not enough parameters");
			return 0;
		}

		int _handle_serial_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			// Ignore command
			return 0;
		}

		int _handle_squadinfo_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_clan * clan;

			if ((numparams >= 1) && (params[0])) {
				if (std::strcmp(params[0], "0") == 0) {
					/* 0 == claninfo for itself */
					clan = account_get_clan(conn_get_account(conn));
					handle_wol_send_claninfo(conn, clan);
				}
				else {
					/* claninfo for clanid (params[0]) */
					clan = clanlist_find_clan_by_clanid(std::atoi(params[0]));
					handle_wol_send_claninfo(conn, clan);
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "SQUADINFO :Not enough parameters");
			return 0;
		}

		int _handle_clanbyname_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_clan * clan;

			if ((numparams >= 1) && (params[0])) {
				clan = account_get_clan(accountlist_find_account(params[0]));
				handle_wol_send_claninfo(conn, clan);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "CLANBYNAME :Not enough parameters");
			return 0;
		}

		int _handle_setopt_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char ** elems;

			/**
			*   This is option for enabling/disabling Page and Find user.
			*
			*   Heres the input expected:
			*   SETOPT 17,32
			*
			*   First parameter: 16 == FindDisabled 17 == FindEnabled
			*   Second parameter: 32 == PageDisabled 33 == PageEnabled
			*/

			if ((numparams >= 1) && (params[0])) {
				elems = irc_get_listelems(params[0]);

				if ((elems) && (elems[0]) && (elems[1])) {
					conn_wol_set_findme(conn, ((std::strcmp(elems[0], "17") == 0) ? true : false));
					conn_wol_set_pageme(conn, ((std::strcmp(elems[1], "33") == 0) ? true : false));
				}
				if (elems)
					irc_unget_listelems(elems);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "SETOPT :Not enough parameters");
			return 0;
		}

		int _handle_setcodepage_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char * codepage = NULL;

			if ((numparams >= 1) && (params[0])) {
				codepage = params[0];
				conn_wol_set_codepage(conn, std::atoi(codepage));
				irc_send(conn, RPL_SET_CODEPAGE, codepage);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "SETCODEPAGE :Not enough parameters");
			return 0;
		}

		int _handle_getcodepage_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			std::string temp;

			if ((numparams >= 1) && (params[0]))
			{
				for (auto i = 0; i < numparams; i++)
				{
					int codepage = 0;
					t_connection * user = connlist_find_connection_by_accountname(params[i]);
					if (user)
						codepage = conn_wol_get_codepage(user);

					temp.append(std::string(params[i]) + "`" + std::to_string(codepage));

					if (i < numparams - 1)
						temp.append("`");
				}

				irc_send(conn, RPL_GET_CODEPAGE, temp.c_str());
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "GETCODEPAGE :Not enough parameters");
			return 0;
		}

		int _handle_setlocale_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_account * account = conn_get_account(conn);
			int locale;

			if ((numparams >= 1) && (params[0])) {
				locale = std::atoi(params[0]);
				account_set_locale(account, locale);
				irc_send(conn, RPL_SET_LOCALE, params[0]);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "SETLOCALE :Not enough parameters");
			return 0;
		}

		int _handle_getlocale_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			std::string temp;

			if ((numparams >= 1) && (params[0]))
			{
				for (auto i = 0; i < numparams; i++)
				{
					int locale = 0;
					t_account * account = accountlist_find_account(params[i]);
					if (account)
						locale = account_get_locale(account);

					temp.append(std::string(params[i]) + "`" + std::to_string(locale));
					if (i < numparams - 1)
						temp.append("`");
				}
				irc_send(conn, RPL_GET_LOCALE, temp.c_str());
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "GETLOCALE :Not enough parameters");
			return 0;
		}

		int _handle_getinsider_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/**
			 * Here is imput expected:
			 *   GETINSIDER [nickname]
			 * Here is output expected:
			 *   :[servername] 399 [nick] [nickname]`0
			 */

			if ((numparams >= 1) && (params[0]))
				irc_send(conn, RPL_GET_INSIDER, std::string(std::string(params[0]) + "`0").c_str());
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "GETINSIDER :Not enough parameters");

			return 0;
		}
		int _handle_finduser_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char _temp[MAX_IRC_MESSAGE_LEN];
			char const * wolname = NULL;

			std::memset(_temp, 0, sizeof(_temp));

			if ((numparams >= 1) && (params[0])) {
				t_connection * user;

				if ((user = connlist_find_connection_by_accountname(params[0])) && (conn_wol_get_findme(user))) {
					wolname = irc_convert_channel(conn_get_channel(user), conn);
					std::snprintf(_temp, sizeof(_temp), "0 :%s", wolname); /* User found in channel wolname */
				}
				else
					std::snprintf(_temp, sizeof(_temp), "1 :"); /* user not loged or have not allowed find */

				irc_send(conn, RPL_FIND_USER, _temp);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "FINDUSER :Not enough parameters");
			return 0;
		}

		int _handle_finduserex_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char _temp[MAX_IRC_MESSAGE_LEN];
			char const * wolname = NULL;

			std::memset(_temp, 0, sizeof(_temp));

			if ((numparams >= 1) && (params[0])) {
				t_connection * user;

				if ((user = connlist_find_connection_by_accountname(params[0])) && (conn_wol_get_findme(user))) {
					wolname = irc_convert_channel(conn_get_channel(user), conn);
					std::snprintf(_temp, sizeof(_temp), "0 :%s,0", wolname); /* User found in channel wolname */
				}
				else
					std::snprintf(_temp, sizeof(_temp), "1 :"); /* user not loged or have not allowed find */

				irc_send(conn, RPL_FIND_USER_EX, _temp);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "FINDUSEREX :Not enough parameters");
			return 0;;
		}

		int _handle_page_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char _temp[MAX_IRC_MESSAGE_LEN];
			bool paged = false;

			if ((numparams >= 1) && (params[0]) && (text)) {
				t_connection * user;

				if (std::strcmp(params[0], "0") == 0) {
					/* PAGE for MY BATTLECLAN */
					t_clan * clan = account_get_clan(conn_get_account(conn));

					if ((clan) && (clan_send_message_to_online_members(clan, message_type_page, conn, text) >= 1))
						paged = true;
				}
				else if ((user = connlist_find_connection_by_accountname(params[0])) && (conn_wol_get_pageme(user))) {
					message_send_text(user, message_type_page, conn, text);
					paged = true;
				}

				if (paged)
					std::snprintf(_temp, sizeof(_temp), "0 :"); /* Page was succesfull */
				else
					std::snprintf(_temp, sizeof(_temp), "1 :"); /* User not loged in or have not allowed page */

				irc_send(conn, RPL_PAGE, _temp);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "PAGE :Not enough parameters");
			return 0;
		}
		int _handle_advertr_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];

			std::memset(temp, 0, sizeof(temp));

			/**
			*  Heres the imput expected
			*  ADVERTR [channel]
			*
			*  Heres the output expected
			*  :[servername] ADVERTR 5 [channel]
			*/

			if ((numparams >= 1) && (params[0])) {
				std::snprintf(temp, sizeof(temp), "5 %s", params[0]);
				message_send_text(conn, message_wol_advertr, conn, temp);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "ADVERTR :Not enough parameters");
			return 0;
		}

		int _handle_advertc_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/* FIXME: Not implemented yet */
			return 0;
		}

		int _handle_chanchk_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			t_channel * channel;

			std::memset(temp, 0, sizeof(temp));

			/**
			*  Heres the imput expected
			*  chanchk [channel]
			*
			*  Heres the output expected
			*  :[servername] CHANCHK [channel]
			*/

			if ((numparams >= 1) && (params[0]))
			{
				if ((channel = channellist_find_channel_by_name(irc_convert_ircname(params[0]), NULL, NULL)))
				{
					std::snprintf(temp, sizeof temp, "%s", params[0]);
					message_send_text(conn, message_wol_chanchk, conn, temp);
				}
				else
				{
					/* FIXME: This is not dumped from original servers... this is probably wrong */
					std::snprintf(temp, sizeof(temp), "%s :No such channel", params[0]);
					irc_send(conn, ERR_NOSUCHCHANNEL, temp);
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "CHANCHK :Not enough parameters");
			return 0;
		}

		int _handle_getbuddy_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char _temp[MAX_IRC_MESSAGE_LEN];
			char const * friend_name;
			t_account * my_acc;
			t_account * friend_acc;
			t_friend * fr;
			int num;
			unsigned int uid;
			int i;

			std::memset(temp, 0, sizeof(temp));
			std::memset(_temp, 0, sizeof(_temp));

			/**
			*  Heres the output expected
			*  :[servername] 333 [user] [buddy_name1]`[buddy_name2]`
			*
			*  Without names:
			*  :[servername] 333 [user]
			*/

			my_acc = conn_get_account(conn);
			num = account_get_friendcount(my_acc);
	
			auto& flist = account_get_friends(my_acc);
	
			if (!flist.empty()) {
				for (i = 0; i < num; i++) {
					if ((!(uid = account_get_friend(my_acc, i))) || (!(fr = friendlist_find_uid(flist, uid)))) {
						eventlog(eventlog_level_error, __FUNCTION__, "friend uid in list");
						continue;
					}
					friend_acc = friend_get_account(fr);
					friend_name = account_get_name(friend_acc);
					std::snprintf(_temp, sizeof(_temp), "%s`", friend_name);
					std::strcat(temp, _temp);
				}
			}
			irc_send(conn, RPL_GET_BUDDY, temp);
			return 0;
		}

		int _handle_addbuddy_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			t_account * my_acc;
			t_account * friend_acc;

			std::memset(temp, 0, sizeof(temp));

			/**
			*  Heres the imput expected
			*  ADDBUDDY [buddy_name]
			*
			*  Heres the output expected
			*  :[servername] 334 [user] [buddy_name]
			*/

			if ((numparams >= 1) && (params[0])) {
				my_acc = conn_get_account(conn);
				if (friend_acc = accountlist_find_account(params[0])) {
					account_add_friend(my_acc, friend_acc);
					/* FIXME: Check if add friend is done if not then send right message */

					std::snprintf(temp, sizeof(temp), "%s", params[0]);
					irc_send(conn, RPL_ADD_BUDDY, temp);
				}
				else {
					std::snprintf(temp, sizeof(temp), "%s :No such nick", params[0]);
					irc_send(conn, ERR_NOSUCHNICK, temp);
					/* NOTE: this is not dumped from WOL, this not shows message
					  but in Emperor doesnt gives name to list, in RA2 have no efect */
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "ADDBUDDY :Not enough parameters");
			return 0;
		}

		int _handle_delbuddy_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char const * friend_name;
			t_account * my_acc;
			int num;

			std::memset(temp, 0, sizeof(temp));

			/**
			*  Heres the imput expected
			*  DELBUDDY [buddy_name]
			*
			*  Heres the output expected
			*  :[servername] 335 [user] [buddy_name]
			*/

			if ((numparams >= 1) && (params[0])) {
				friend_name = params[0];
				my_acc = conn_get_account(conn);

				num = account_remove_friend2(my_acc, friend_name);

				/**
				*  FIXME: Check if remove friend is done if not then send right message
				*  Btw I dont know another then RPL_DEL_BUDDY message yet.
				*/

				std::snprintf(temp, sizeof(temp), "%s", friend_name);
				irc_send(conn, RPL_DEL_BUDDY, temp);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "DELBUDDY :Not enough parameters");
			return 0;
		}
		int _handle_userip_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			t_connection * user;
			const char * addr = NULL;

			std::memset(temp, 0, sizeof(temp));

			if ((numparams >= 1) && (params[0])) {
				if ((user = connlist_find_connection_by_accountname(params[0]))) {
					addr = addr_num_to_ip_str(conn_get_addr(user));
					//FIXME: We are not sure of first parameter. It can be also nickname of command sender
					std::snprintf(temp, sizeof(temp), "%s %s", params[0], addr);
					message_send_text(conn, message_wol_userip, conn, temp);
				}
				else {
					std::snprintf(temp, sizeof(temp), "%s :No such nick", params[0]);
					irc_send(conn, ERR_NOSUCHNICK, temp);
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "USERIP :Not enough parameters");
			return 0;
		}

		/**
		 * LADDER Server commands:
		 */
		int _ladder_send(t_connection * conn, char const * command)
		{
			char data[MAX_IRC_MESSAGE_LEN + 1];
			unsigned len = 0;

			if (command)
				len = (std::strlen(command) + 6);

			if (len > MAX_IRC_MESSAGE_LEN)
			{
				eventlog(eventlog_level_error, __FUNCTION__, "message to send is too large ({} bytes)", len);
				return -1;
			}

			std::sprintf(data, "\r\n\r\n\r\n%s", command);
			eventlog(eventlog_level_debug, __FUNCTION__, "[{}] sent \"{}\"", conn_get_socket(conn), data);
			{
				int const _rc = pvpgn_v3_send_raw_text(conn, data);
				if (_rc == 1) goto handle_wol_ladder_send_skip_legacy;
				if (_rc == -1) return -1;
			}
			{
				t_packet* const p = packet_create(packet_class_raw);
				if (!p)
				{
					return -1;
				}
				packet_set_size(p, 0);
				packet_append_data(p, data, len);
				conn_push_outqueue(conn, p);
				packet_del_ref(p);
			}
			handle_wol_ladder_send_skip_legacy:;

			/* In ladder server we must destroy connection after send packet */
			conn_set_state(conn, conn_state_destroy);

			return 0;
		}

		int _ladder_is_integer(char * test)
		{
			for (char const* ptr = test; *ptr; ++ptr) {
				if (!std::isdigit(*ptr)) {
					return 0; /* Is not integer */
				}
				else
					return 1; /* Is integer */
			}

			return -1; /* We shouldn't get here */
		}

		int _handle_listsearch_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char ** e;
			int i = 0;
			unsigned rank = 0;
			unsigned points = 0;
			unsigned wins = 0;
			unsigned losses = 0;
			unsigned disconnects = 0;
			char temp[MAX_IRC_MESSAGE_LEN];
			char data[MAX_IRC_MESSAGE_LEN];
			t_account * cl_account;
			t_clienttag cl_tag;
			t_ladder_id id = ladder_id_solo;

			std::memset(data, 0, sizeof(data));

			if ((numparams >= 1) && (params[0]) && (text)) {
				cl_tag = tag_sku_to_uint(std::atoi(params[0]));

				if (e = irc_get_ladderelems(text))
				{
					//TIMESTAMP 1147130452
					//TOTAL 12033
					//NOTFOUND
					// TIMESTAMP 1188740860
					// 'TOTAL 27466
					/*    std::sprintf(temp,"TIMESTAMP %lu\n", std::time(NULL));
						std::strcat(data,temp);
						std::sprintf(temp,"TOTAL 88\n");
						std::strcat(data,temp);*/

					for (i = 0; e[i]; i++) {
						/* Now we have in e[i] names */
						if (e[i] && (std::strcmp(e[i], ":") != 0)) {
							cl_account = accountlist_find_account(e[i]);
							if (cl_account && cl_tag && (rank = account_get_ladder_rank(cl_account, cl_tag, id))) {
								points = account_get_ladder_points(cl_account, cl_tag, id);
								wins = account_get_ladder_wins(cl_account, cl_tag, id);
								losses = account_get_ladder_losses(cl_account, cl_tag, id);
								disconnects = account_get_ladder_disconnects(cl_account, cl_tag, id);
								std::sprintf(temp, "%u  %s  %u  %u  %u  0  %u\r\n", rank, e[i], points, wins, losses, disconnects);
								std::strcat(data, temp);
							}
							else
								std::strcat(data, "NOTFOUND\r\n");
						}
					}
					irc_unget_ladderelems(e);

					_ladder_send(conn, data);
				}
			}
			else {
				WARN0("Not enough parameters");
				conn_set_state(conn, conn_state_destroy);
				return 0;
			}
			return 0;
		}

		int _handle_rungsearch_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char data[MAX_IRC_MESSAGE_LEN];
			unsigned rank = 0;
			unsigned points = 0;
			unsigned wins = 0;
			unsigned losses = 0;
			unsigned disconnects = 0;
			t_account * cl_account;
			t_clienttag cl_tag;
			t_ladder_id id = ladder_id_solo;

			std::memset(data, 0, sizeof(data));

			if ((numparams >= 4) && (params[0]) && (params[1]) && (params[3])) {
				cl_tag = tag_sku_to_uint(std::atoi(params[3]));

				if ((cl_tag != CLIENTTAG_TIBERNSUN_UINT) && (cl_tag != CLIENTTAG_TIBSUNXP_UINT)
					&& (cl_tag != CLIENTTAG_REDALERT2_UINT) && (cl_tag != CLIENTTAG_YURISREV_UINT)) {
					// PELISH: We are not supporting ladders for all WOL clients yet
					std::strcat(data, "\r\n");
					_ladder_send(conn, data);
					DEBUG1("Wants rung search for SKU {}", params[3]);
					return 0;
				}

				if (_ladder_is_integer(params[0]) == 0) {
					/* rungsearch want to line for one player (nick is in params[0]) */
					cl_account = accountlist_find_account(params[0]);
					if (cl_account && cl_tag && (rank = account_get_ladder_rank(cl_account, cl_tag, id))) {
						points = account_get_ladder_points(cl_account, cl_tag, id);
						wins = account_get_ladder_wins(cl_account, cl_tag, id);
						losses = account_get_ladder_losses(cl_account, cl_tag, id);
						disconnects = account_get_ladder_disconnects(cl_account, cl_tag, id);
						std::sprintf(temp, "%u  %s  %u  %u  %u  0  %u\r\n", rank, params[0], points, wins, losses, disconnects);
					}
					else
						std::sprintf(temp, "\r\n");
					_ladder_send(conn, temp);
				}
				else {
					/* Standard RUNG search */
					unsigned start = std::atoi(params[0]);
					unsigned count = std::atoi(params[1]);

					eventlog(eventlog_level_debug, __FUNCTION__, "Start({}) Count({})", start, count);

					LadderList* ladderList = NULL;

					ladderList = ladders.getLadderList(LadderKey(id, cl_tag, ladder_sort_default, ladder_time_default));
					for (unsigned int i = start; i < start + count; i++) {
						const LadderReferencedObject* referencedObject = NULL;
						cl_account = NULL;
						if (((referencedObject = ladderList->getReferencedObject(i))) && (cl_account = referencedObject->getAccount())) {
							rank = account_get_ladder_rank(cl_account, cl_tag, id);
							points = account_get_ladder_points(cl_account, cl_tag, id);
							wins = account_get_ladder_wins(cl_account, cl_tag, id);
							losses = account_get_ladder_losses(cl_account, cl_tag, id);
							disconnects = account_get_ladder_disconnects(cl_account, cl_tag, id);
							std::sprintf(temp, "%u  %s  %u  %u  %u  0  %u\r\n", rank, account_get_name(cl_account), points, wins, losses, disconnects);
							std::strcat(data, temp);
						}
						else {
							std::strcat(data, "\r\n");
							_ladder_send(conn, data);
							return 0;
						}
					}
					_ladder_send(conn, data);
				}
			}
			else {
				WARN0("Not enough parameters");
				conn_set_state(conn, conn_state_destroy);
				return 0;
			}
			return 0;
		}

		int _handle_highscore_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/*    char ** e;
				int i = 0;
				unsigned rank = 2;
				unsigned points = 258;
				unsigned wins = 0;
				unsigned losses = 0;
				unsigned unknown = 0;  // Here is nuber before Nick and Honor Badges in Yuri (1-999)
				unsigned disconnects = 0;
				char temp[MAX_IRC_MESSAGE_LEN];
				char data[MAX_IRC_MESSAGE_LEN];
				t_account * cl_account;
				t_clienttag cltag;

				std::memset(temp,0,sizeof(temp));
				std::memset(data,0,sizeof(data));

				if (text)
				e = irc_get_ladderelems(text);

				if (params[0])
				cltag = tag_sku_to_uint(std::atoi(params[0]));

				for (i=0;e[i];i++) {
				if (e[i] && (std::strcmp(e[i], ":") != 0)) {
				cl_account = accountlist_find_account(e[i]);
				if (cl_account) {
				wins = account_get_normal_wins(cl_account, cltag);
				losses = account_get_normal_losses(cl_account, cltag);
				disconnects = account_get_normal_disconnects(cl_account, cltag);
				std::sprintf(temp,"%u  %s  %u  %u  %u  %u  %u\r\n",rank+i,e[i],points,wins,losses,unknown,disconnects);
				std::strcat(data,temp);
				}
				else
				std::strcat(data,"NOTFOUND\r\n");
				}
				}

				if (e)
				irc_unget_ladderelems(e);

				_ladder_send(conn,data);
				*/
			conn_set_state(conn, conn_state_destroy);
			return 0;
		}

	}

}
