// SPDX-License-Identifier: GPL-2.0-or-later
// wol_user_commands.cpp — WoL user/pass/privmsg/list/quit/names/part handlers
// Auto-generated by scripts/dev/split_handle_wol.py (plan 15 §5)
#include "wol_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		int _handle_user_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/**
			 *  In WOL isnt used USER command (only for backward compatibility)
			 *  RFC 2812 says:
			 *  USER <user> <mode> <unused> :<realname>
			 *
			 *  There is WOL imput expected:
			 *  USER UserName HostName irc.westwood.com :RealName
			 */

			char * user = NULL;
			t_account * a;

			user = (char *)conn_get_loggeduser(conn);

			if (conn_get_user(conn)) {
				/* FIXME: Send real ERROR code/message */
				irc_send(conn, ERR_ALREADYREGISTRED, ":You are already registred");
			}
			else {
				eventlog(eventlog_level_debug, __FUNCTION__, "[{}][** WOL **] got USER: user=\"{}\"", conn_get_socket(conn), user);

				a = accountlist_find_account(user);
				if (!a) {
					/* Auto-create account */
					t_account * tempacct;
					t_hash pass_hash;
					char * pass = wol_strdup(conn_wol_get_apgar(conn)); /* FIXME: Do not use bnet passhash when we have wol passhash */
					strtolower(pass);

					bnet_hash(&pass_hash, std::strlen(pass), pass);
					delete[] pass;

					tempacct = accountlist_create_account(user, hash_get_str(pass_hash));
					if (!tempacct) {
						/* FIXME: Send real ERROR code/message */
						irc_send(conn, RPL_BAD_LOGIN, ":Account creating failed");
						return 0;
					}

					conn_set_user(conn, user);
					conn_set_owner(conn, user);
					if (conn_get_loggeduser(conn))
						handle_wol_welcome(conn); /* only send the welcome if we have USER and NICK */
				}
				else {
					conn_set_user(conn, user);
					conn_set_owner(conn, user);
					if (conn_get_loggeduser(conn))
						handle_wol_welcome(conn); /* only send the welcome if we have USER and NICK */
				}
			}
			return 0;
		}

		int _handle_pass_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/**
			 * PASS is not used in WOL
			 * only for backward compatibility sent client PASS supersecret
			 * real password sent client by apgar command
			 */

			return 0;
		}

		int _handle_privmsg_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			if ((numparams >= 1) && (text))
			{
				int i;
				char ** e;

				e = irc_get_listelems(params[0]);
				/* FIXME: support wildcards! */

				/* start amadeo: code was sent by some unkown fellow of pvpgn (maybe u wanna give us your name
				   for any credits), it adds nick-registration, i changed some things here and there... */
				for (i = 0; ((e) && (e[i])); i++) {
					if (strcasecmp(e[i], "matchbot") == 0) {
						/* Anongames WOL support */
						anongame_wol_privmsg(conn, numparams, params, text);
					}
					else if (conn_get_state(conn) == conn_state_loggedin) {
						if (e[i][0] == '#') {
							/* channel message */
							t_channel * channel;

							//PELISH: We does not support talk for not inside-channel clients now but in WOL is that feature not needed
							if (channel = conn_get_channel(conn)) {
								if ((std::strlen(text) >= 9) && (std::strncmp(text, "\001ACTION ", 8) == 0) && (text[std::strlen(text) - 1] == '\001')) {
									/* at least "\001ACTION \001" */
									/* it's a CTCP ACTION message */
									text = text + 8;
									text[std::strlen(text) - 1] = '\0';
									channel_message_send(channel, message_type_emote, conn, text);
								}
								else {
									if (text[0] == '/') {
										/* "/" commands (like "/help..." */
										handle_command(conn, text);
									}
									else {
										channel_message_log(channel, conn, 1, text);
										channel_message_send(channel, message_type_talk, conn, text);
									}
								}
							}
							else {
								irc_send(conn, ERR_NOSUCHCHANNEL, std::string(std::string(e[0]) + " :No such channel").c_str());
							}
						}
						else {
							/* whisper */
							t_connection * user;

							if ((user = connlist_find_connection_by_accountname(e[i])))
							{
								message_send_text(user, message_type_whisper, conn, text);
							}
							else
							{
								irc_send(conn, ERR_NOSUCHNICK, ":No such user");
							}
						}
					}
				}
				if (e)
					irc_unget_listelems(e);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "PRIVMSG :Not enough parameters");
			return 0;
		}

		struct gamelist_data {
			unsigned tcount, counter;
			t_connection *conn;
		};

		int append_game_info(t_game* game, void* vdata)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char temp_a[MAX_IRC_MESSAGE_LEN];
			gamelist_data* data = static_cast<gamelist_data*>(vdata);
			t_channel *  gamechannel;
			const char * gamename;
			std::string topicstr;

			std::memset(temp, 0, sizeof(temp));
			std::memset(temp_a, 0, sizeof(temp_a));

			data->tcount++;

			if (game_get_status(game) != game_status_open) {
				eventlog(eventlog_level_debug, __FUNCTION__, "[{}] not listing because game is not open", conn_get_socket(data->conn));
				return 0;
			}
			if (game_get_clienttag(game) != conn_get_clienttag(data->conn)) {
				eventlog(eventlog_level_debug, __FUNCTION__, "[{}] not listing because game is for a different client", conn_get_socket(data->conn));
				return 0;
			}

			if (!(gamechannel = game_get_channel(game))) {
				ERROR0("game have no channel");
				return 0;
			}
			if (!(gamename = irc_convert_channel(gamechannel, data->conn))) {
				ERROR0("game have no name");
				return 0;
			}

			class_topic Topic;
			topicstr = Topic.get(channel_get_name(gamechannel));

			if (topicstr.empty() == false) {
				if (std::strlen(gamename) + 1 + 20 + 1 + 1 + std::strlen(topicstr.c_str()) > MAX_IRC_MESSAGE_LEN) {
					WARN0("LISTREPLY length exceeded");
					return 0;
				}
			}
			else {
				if (std::strlen(gamename) + 1 + 20 + 1 + 1 > MAX_IRC_MESSAGE_LEN) {
					WARN0("LISTREPLY length exceeded");
					return 0;
				}
			}

			/***
			 * WOLv1:
			 * : 326 u #nick's_game 1 0 2 0 0 1122334455 128::
			 * WOLv2:
			 * : 326 u #nick's_game 1 0 21 0 16777216 1122334455 128::g040
			 * : 326 u #nick's_game 1 0 41 1 2048 1122334455 128::g12P25,2097731398,0,0,0,WATERF~3.YRM // anon_game
			 */
			/**
			 *  The layout of the game list entry is something like this:
			 *  #game_channel_name currentusers maxplayers gameType gameIsTournment gameExtension longIP LOCK::topic
			 */

			std::strcat(temp, gamename);
			std::strcat(temp, " ");

			std::snprintf(temp_a, sizeof(temp_a), "%u ", game_get_ref(game)); /* curent players */
			std::strcat(temp, temp_a);

			std::snprintf(temp_a, sizeof(temp_a), "%u ", game_get_maxplayers(game)); /* max players */
			std::strcat(temp, temp_a);

			std::snprintf(temp_a, sizeof(temp_a), "%u ", channel_wol_get_game_type(gamechannel)); /* game type */
			std::strcat(temp, temp_a);

			std::snprintf(temp_a, sizeof(temp_a), "%u ", (game_get_type(game) == game_type_ladder) ? 1 : 0); /* tournament */
			std::strcat(temp, temp_a);

			std::snprintf(temp_a, sizeof(temp_a), "%s ", channel_wol_get_game_extension(gamechannel));  /* game extension */
			std::strcat(temp, temp_a);

			std::snprintf(temp_a, sizeof(temp_a), "%u ", conn_get_addr(game_get_owner(game))); /* owner IP - FIXME: address translation here!! */
			std::strcat(temp, temp_a);

			if (std::strcmp(game_get_pass(game), "") == 0)
				std::strcat(temp, "128"); /* game is unloocked 128 == no_pass */
			else
				std::strcat(temp, "384"); /* game is loocked 384 == pass */

			std::strcat(temp, "::");

			if (topicstr.c_str()) {
				std::snprintf(temp_a, sizeof(temp_a), "%s", topicstr.c_str());  /* topic */
				std::strcat(temp, temp_a);
			}

			data->counter++;
			irc_send(data->conn, RPL_GAME_CHANNEL, temp);

			return 0;
		}

		int _handle_list_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];

			irc_send(conn, RPL_LISTSTART, "Channel :Users Names"); /* backward compatibility */

			if ((numparams == 0) || ((numparams == 2) && (params[0]) && (params[1]) && (std::strcmp(params[0], params[1]) != 0))) {
				/**
				 * LIST all chat channels
				 * Emperor sends as params[0] == -1 if want QuickMatch channels too, 0 if not.
				 * This sends also NOX but we dunno why.
				 * DUNE 2000 use params[0] to determine channels by channeltype
				 */

				for (t_channel const* channel : channellist()) {
					char const * tempname;

					tempname = irc_convert_channel(channel, conn);

					if ((tag_check_wolv1(conn_get_clienttag(conn))) && (std::strlen(tempname) > MAX_WOLV1_CHANNELNAME_LEN))
						continue;

					/* FIXME: Delete this if games are not in channels */
					if ((channel_wol_get_game_type(channel) != 0))
						continue;

					sprintf(temp, "%s %u ", tempname, channel_get_length(channel));

					if (channel_get_flags(channel) & channel_flags_permanent)
						std::strcat(temp, "1");  /* Official channel */
					else
						std::strcat(temp, "0");  /* User channel */

					if (tag_check_wolv1(conn_get_clienttag(conn)))
						std::strcat(temp, ":");     /* WOLv1 ends by ":" FIXME: Should be an TOPIC after ":"*/
					else
						std::strcat(temp, " 388");  /* WOLv2 ends by "388" */

					irc_send(conn, RPL_CHANNEL, temp);
				}
			}
			/**
			*  Known channel game types:
			*  0 = Westwood Chat channels, 1 = Command & Conquer Win95 channels, 2 = Red Alert Win95 channels,
			*  3 = Red Alert Counterstrike channels, 4 = Red Alert Aftermath channels, 5 = CnC Sole Survivor channels,
			*  12 = C&C Renegade channels, 14 = Dune 2000 channels, 16 = Nox channels, 18 = Tiberian Sun channels,
			*  21 = Red Alert 1 v 3.03 channels, 31 = Emperor: Battle for Dune, 33 = Red Alert 2,
			*  37 = Nox Quest channels, 38,39,40 = Quickgame channels, 41 = Yuri's Revenge
			*/
			if ((numparams == 0) || ((numparams == 2) && (params[0]) && (params[1]) && (std::strcmp(params[0], params[1]) == 0))) {
				eventlog(eventlog_level_debug, __FUNCTION__, "[** WOL **] LIST [Game]");
				/* list games */
				struct gamelist_data data;
				data.tcount = 0;
				data.counter = 0;
				data.conn = conn;
				gamelist_traverse(&append_game_info, &data, gamelist_source_none);
				DEBUG3("[{}] LIST sent {} of {} games", conn_get_socket(conn), data.counter, data.tcount);
			}
			irc_send(conn, RPL_LISTEND, ":End of LIST command");
			return 0;
		}

		int _handle_quit_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			if (conn_get_channel(conn))
				conn_quit_channel(conn, text);

			irc_send(conn, RPL_QUIT, ":goodbye");

			conn_set_state(conn, conn_state_destroy);

			return 0;
		}

		int _handle_names_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_channel * channel;

			if (numparams >= 1) {
				char ** e;
				char const * verytemp;
				int i;

				e = irc_get_listelems(params[0]);
				for (i = 0; ((e) && (e[i])); i++) {
					verytemp = irc_convert_ircname(e[i]);

					if (!verytemp)
						continue; /* something is wrong with the name ... */
					channel = channellist_find_channel_by_name(verytemp, NULL, NULL);
					if ((!channel) && (!(channel = conn_get_channel(conn))))
						continue; /* channel doesn't exist */
					irc_send_rpl_namreply(conn, channel);
				}
				if (e)
					irc_unget_listelems(e);
			}
			else if (numparams == 0) {
				irc_send_rpl_namreply(conn, NULL);
			}
			return 0;
		}

		int _handle_part_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			t_game * game;

			conn_part_channel(conn);

			if ((game = conn_get_game(conn)) && (game_get_status(game) == game_status_open))
				conn_set_game(conn, NULL, NULL, NULL, game_type_none, 0);

			return 0;
		}

	}

}
