if(PVPGN_V3_WITH_SPDLOG)
    add_subdirectory(log)
endif()
if(PVPGN_V3_WITH_TOMLPP)
    add_subdirectory(config)
endif()
if(PVPGN_V3_WITH_BOOST)
    add_subdirectory(net)
    add_subdirectory(metrics)
endif()
add_subdirectory(compat)
add_subdirectory(compression)
add_subdirectory(crypto)
add_subdirectory(legacy_config)
if(TARGET infra_legacy_crypto)
    add_subdirectory(legacy_crypto)
endif()
add_subdirectory(inmemory)
if(TARGET infra_scripting_plugin)
    add_subdirectory(scripting)
endif()
if(TARGET infra_clock)
    add_subdirectory(clock)
endif()
if(TARGET infra_logging)
    add_subdirectory(logging)
endif()
