if(TARGET application_auth)
    add_subdirectory(auth)
endif()
if(TARGET application_anongame_infoply)
    add_subdirectory(anongame_infoply)
endif()
if(TARGET application_icon_table)
    add_subdirectory(icon_table)
endif()
if(TARGET application_tournament)
    add_subdirectory(tournament)
endif()
if(TARGET application_profile)
    add_subdirectory(profile)
endif()
if(TARGET application_chat)
    add_subdirectory(chat)
endif()
if(TARGET application_game)
    add_subdirectory(game)
endif()
if(TARGET application_moderation)
    add_subdirectory(moderation)
endif()
if(TARGET application_i18n)
    add_subdirectory(i18n)
endif()
if(TARGET application_realm)
    add_subdirectory(realm)
endif()
if(TARGET application_init)
    add_subdirectory(init)
endif()
add_subdirectory(ports)
