// =====================================================================
// handle_bnet_internal.h — shared declarations for handle_bnet/ modules
// Auto-generated by scripts/dev/split_handle_bnet.py
// =====================================================================
#pragma once

#include "common/setup_before.h"
#include "handle_bnet.h"

#include <cctype>
#include <cerrno>
#include <cinttypes>
#include <cstdint>
#include <cstring>
#include <format>
#include <fstream>
#include <iterator>
#include <limits>
#include <sstream>
#include <string>
#include <tuple>

#include <strings.h>
#include "common/packet.h"
#include "common/eventlog.h"
#include "common/tag.h"
#include "common/bn_type.h"
#include "common/addr.h"
#include "common/bnettime.h"
#include "common/trans.h"
#include "common/list.h"
#include "common/bnethash.h"
#include "common/bnethashconv.h"
#include "common/proginfo.h"
#include "common/util.h"
#include "common/bnetsrp3.h"
#include "common/xstring.h"

#include "handlers.h"
#include "connection.h"
#include "prefs_v3_shim.h"
#include "versioncheck.h"
#include "handle_anongame.h"
#include "account.h"
#include "account_wrap.h"
#include "clan.h"
#include "channel.h"
#include "game.h"
#include "game_conv.h"
#include "ladder.h"
#include "watch.h"
#include "realm.h"
#include "adbanner.h"
#include "character.h"
#include "command.h"
#include "tick.h"
#include "message.h"
#include "file.h"
#include "news.h"
#include "team.h"
#include "server.h"
#include "friends.h"
#include "autoupdate.h"
#include "anongame.h"
#include "i18n.h"
#ifdef WIN32_GUI
#include <win32/winmain.h>
#endif
#include "common/setup_after.h"
#ifdef WITH_LUA
#include "luainterface.h"
#endif

#include "integration/legacy_bnetd/strangler_macros.h"
#include "integration/legacy_bnetd/send_friendslist_bridge.hpp"

// ── All extern "C" bridge declarations ───────────────────────────────────────
extern "C" int pvpgn_v3_send_authreply1(void* conn_ptr,
                                        unsigned int message,
                                        char const* mpqfilename) noexcept;
extern "C" int pvpgn_v3_send_authreply109(void* conn_ptr,
                                          unsigned int message,
                                          char const* mpqfilename) noexcept;
extern "C" int pvpgn_v3_send_authinfo_reply(void* conn_ptr,
                                            unsigned int logontype,
                                            unsigned int server_token,
                                            unsigned int session_num,
                                            unsigned long long timestamp,
                                            char const* mpq_filename,
                                            char const* checksum_formula,
                                            int include_w3_signature) noexcept;
extern "C" int pvpgn_v3_send_loginreply1(void* conn_ptr,
                                         unsigned int message) noexcept;
extern "C" int pvpgn_v3_send_loginreply2(void* conn_ptr,
                                         unsigned int message,
                                         char const* reason) noexcept;
extern "C" int pvpgn_v3_send_createacctreply1(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_createacctreply2(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_createaccount_w3(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_iconreply(void* conn_ptr,
                                       unsigned long long timestamp,
                                       char const* filename) noexcept;
extern "C" int pvpgn_v3_send_channellist(void* conn_ptr,
                                         char const* const* names,
                                         unsigned int count) noexcept;
extern "C" int pvpgn_v3_joinchannel(void* conn_ptr,
                                        char const* channel_name,
                                        unsigned int flag) noexcept;
extern "C" int pvpgn_v3_leavechannel(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_gamereport(void* conn_ptr,
                                       char const* username,
                                       unsigned int player_count) noexcept;
extern "C" int pvpgn_v3_startgame(void* conn_ptr,
                                      unsigned int version,
                                      char const* gamename,
                                      char const* gameinfo,
                                      unsigned int bngtype,
                                      unsigned int status,
                                      unsigned int flag,
                                      unsigned int option) noexcept;
extern "C" int pvpgn_v3_gamelistreq(void* conn_ptr,
                                        char const* gamename,
                                        unsigned int bngtype) noexcept;
extern "C" int pvpgn_v3_joingame(void* conn_ptr,
                                     char const* gamename) noexcept;
extern "C" int pvpgn_v3_clan_dispatch(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_friends_dispatch(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_auth_dispatch(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_keepalive_dispatch(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_realm_dispatch(void* conn_ptr,
                                           char const* op) noexcept;
extern "C" int pvpgn_v3_account_dispatch(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_profile_dispatch(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_ladder_dispatch(void* conn_ptr,
                                            char const* op) noexcept;
extern "C" int pvpgn_v3_d2_character_dispatch(void* conn_ptr,
                                                   char const* op) noexcept;
extern "C" int pvpgn_v3_telemetry_dispatch(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_ad_dispatch(void* conn_ptr,
                                        char const* op) noexcept;
extern "C" int pvpgn_v3_progident_dispatch(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_gameport_dispatch(void* conn_ptr,
                                              char const* op) noexcept;
extern "C" int pvpgn_v3_cdkey_dispatch(void* conn_ptr,
                                           char const* op) noexcept;
extern "C" int pvpgn_v3_passemail_dispatch(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_handshake_dispatch(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_stub_dispatch(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_send_logonproof_reply(void* conn_ptr,
                                              unsigned int response,
                                              unsigned char const* server_password_proof,
                                              char const* custom_reason) noexcept;
extern "C" int pvpgn_v3_send_loginreply_w3(void* conn_ptr,
                                           unsigned int message,
                                           unsigned char const* salt,
                                           unsigned char const* server_public_key) noexcept;
extern "C" int pvpgn_v3_send_compreply(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_send_sessionkey1(void* conn_ptr,
                                         unsigned int sessionkey) noexcept;
extern "C" int pvpgn_v3_send_sessionkey2(void* conn_ptr,
                                         unsigned int sessionnum,
                                         unsigned int sessionkey) noexcept;
extern "C" int pvpgn_v3_send_echoreq(void* conn_ptr,
                                      unsigned int ticks) noexcept;
extern "C" int pvpgn_v3_send_clan_invitereply(void*         conn_ptr,
                                               unsigned int  count,
                                               unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clan_membernewchief_reply(void*         conn_ptr,
                                                        unsigned int  count,
                                                        unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clanmember_remove_reply(void*         conn_ptr,
                                                     unsigned int  count,
                                                     unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clanmember_rankupdate_reply(void*         conn_ptr,
                                                          unsigned int  count,
                                                          unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_changepassack(void*        conn_ptr,
                                            unsigned int message) noexcept;
extern "C" int pvpgn_v3_send_authreq1_server(void*                conn_ptr,
                                              unsigned long long   timestamp,
                                              char const*          filename,
                                              char const*          equation) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply(void* conn_ptr,
                                         unsigned int message,
                                         char const* owner) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply2(void* conn_ptr,
                                          unsigned int result,
                                          char const* owner) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply3(void* conn_ptr,
                                          unsigned int message,
                                          char const* owner_name) noexcept;
extern "C" int pvpgn_v3_send_fileinforeply(void*                conn_ptr,
                                            std::uint32_t        type,
                                            std::uint32_t        unknown2,
                                            std::uint64_t        timestamp,
                                            char const*          filename) noexcept;
extern "C" int pvpgn_v3_send_pingreply(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_send_passchangereply(void*                conn_ptr,
                                              unsigned int         message,
                                              unsigned char const* salt,
                                              unsigned char const* server_public_key) noexcept;
extern "C" int pvpgn_v3_send_passchangeproofreply(void*                conn_ptr,
                                                   unsigned int         response,
                                                   unsigned char const* server_password_proof) noexcept;
extern "C" int pvpgn_v3_send_statsreply(void*              conn_ptr,
                                         unsigned int       name_count,
                                         unsigned int       key_count,
                                         unsigned int       request_id,
                                         char const* const* values,
                                         unsigned int       value_count) noexcept;
struct pvpgn_v3_friend_entry;
extern "C" int pvpgn_v3_send_friendslistreply(
    void*                              conn_ptr,
    struct pvpgn_v3_friend_entry const* entries,
    unsigned int                        count) noexcept;
extern "C" int pvpgn_v3_send_friendinforeply(void*        conn_ptr,
                                              unsigned int friend_num,
                                              unsigned int type,
                                              unsigned int status,
                                              unsigned int client_tag,
                                              char const*  game_name) noexcept;
extern "C" int pvpgn_v3_send_atfriendscreenreply(void*              conn_ptr,
                                                  char const* const* names,
                                                  unsigned int       count) noexcept;
extern "C" int pvpgn_v3_send_atinvitefriendack(void*               conn_ptr,
                                                unsigned int        count,
                                                unsigned int        id,
                                                unsigned int        timestamp,
                                                unsigned int        team_size,
                                                unsigned int const* info) noexcept;
extern "C" int pvpgn_v3_send_atmemberdecline(void*        conn_ptr,
                                              unsigned int count,
                                              unsigned int action,
                                              char const*  decliner_name) noexcept;
extern "C" int pvpgn_v3_send_motdw3(void*        conn_ptr,
                                     unsigned int msg_type,
                                     unsigned int curr_time,
                                     unsigned int first_news_time,
                                     unsigned int timestamp,
                                     unsigned int timestamp2,
                                     char const*  text) noexcept;
struct pvpgn_v3_realm_entry;
extern "C" int pvpgn_v3_send_realmlistreply(void*                             conn_ptr,
                                             struct pvpgn_v3_realm_entry const* entries,
                                             unsigned int                       count) noexcept;
struct pvpgn_v3_realm_legacy_entry;
extern "C" int pvpgn_v3_send_realmlistlegacyreply(
    void*                                     conn_ptr,
    struct pvpgn_v3_realm_legacy_entry const* entries,
    unsigned int                              count) noexcept;
extern "C" int pvpgn_v3_realm_list_apply(void* conn_ptr,
                                          int   legacy_format) noexcept;
extern "C" int pvpgn_v3_send_claninforeply(void*        conn_ptr,
                                            unsigned int cookie,
                                            unsigned int fail,
                                            char const*  clan_name,
                                            unsigned int rank,
                                            unsigned int join_time) noexcept;
extern "C" int pvpgn_v3_send_profilereply(void*        conn_ptr,
                                           unsigned int cookie,
                                           unsigned int fail,
                                           char const*  description,
                                           char const*  location,
                                           unsigned int clan_tag) noexcept;
extern "C" int pvpgn_v3_send_realmjoinreply(void*               conn_ptr,
                                             unsigned int        seqno,
                                             unsigned int        u1,
                                             unsigned int        bncs_addr1,
                                             unsigned int        session_num,
                                             unsigned int        addr,
                                             unsigned int        port,
                                             unsigned int        u3,
                                             unsigned int        session_key,
                                             unsigned int        u5,
                                             unsigned int        u6,
                                             unsigned int        client_tag,
                                             unsigned int        version_id,
                                             unsigned int        bncs_addr2,
                                             unsigned int        u7,
                                             unsigned int const* secret_hash,
                                             char const*         account_name) noexcept;
extern "C" int pvpgn_v3_send_charlistreply(void*                conn_ptr,
                                            unsigned int         unknown1,
                                            unsigned int         max_chars,
                                            unsigned int         count,
                                            unsigned char const* char_data,
                                            unsigned int         char_data_len) noexcept;
extern "C" int pvpgn_v3_send_adreply(void*                conn_ptr,
                                      unsigned int         adid,
                                      unsigned int         extension_tag,
                                      unsigned long long   timestamp,
                                      char const*          filename,
                                      char const*          link) noexcept;
extern "C" int pvpgn_v3_send_adclick2reply(void*        conn_ptr,
                                            unsigned int adid,
                                            char const*  link) noexcept;
struct PvpgnV3AdPickOut {
    int          found;
    unsigned int id;
    unsigned int extension_tag;
    char         filename[256];
    char         url[1024];
};
struct PvpgnV3AdClickOut {
    int          accepted;
    unsigned int id;
    char         click_url[1024];
};
extern "C" int pvpgn_v3_ads_pick_apply(unsigned int client_tag,
                                       unsigned int lang_tag,
                                       unsigned int prev_ad_id,
                                       PvpgnV3AdPickOut* out) noexcept;
extern "C" int pvpgn_v3_ads_click_apply(unsigned int client_tag,
                                        unsigned int lang_tag,
                                        unsigned int ad_id,
                                        PvpgnV3AdClickOut* out) noexcept;
extern "C" int pvpgn_v3_send_playerinforeply(void*       conn_ptr,
                                              char const* account_name,
                                              char const* player_info,
                                              char const* username) noexcept;
struct pvpgn_v3_game_list_entry;
extern "C" int pvpgn_v3_send_gamelistreply(
    void*                                    conn_ptr,
    std::uint32_t                            sstatus,
    struct pvpgn_v3_game_list_entry const*   entries,
    unsigned int                             count) noexcept;
extern "C" int pvpgn_v3_send_startgame1ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
extern "C" int pvpgn_v3_send_startgame3ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
extern "C" int pvpgn_v3_send_startgame4ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
struct pvpgn_v3_ladder_list_entry;
extern "C" int pvpgn_v3_send_ladderreply(
    void*                                      conn_ptr,
    unsigned int                               client_tag,
    unsigned int                               id,
    unsigned int                               type,
    unsigned int                               start,
    unsigned int                               count,
    struct pvpgn_v3_ladder_list_entry const*   entries) noexcept;
extern "C" int pvpgn_v3_send_laddersearchreply(void*        conn_ptr,
                                                unsigned int rank) noexcept;
extern "C" int pvpgn_v3_send_mapauthreply1(void*        conn_ptr,
                                            unsigned int response) noexcept;
extern "C" int pvpgn_v3_send_mapauthreply2(void*        conn_ptr,
                                            unsigned int response) noexcept;
extern "C" int pvpgn_v3_send_clandisbandreply(void*        conn_ptr,
                                               unsigned int cookie,
                                               unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_clancreateinviteforward(
    void*                conn_ptr,
    unsigned int         cookie,
    unsigned int         clan_tag,
    char const*          clan_name,
    char const*          clan_creator,
    char const* const*   member_names,
    unsigned int         member_count) noexcept;
extern "C" int pvpgn_v3_send_clancreateinvitereply(void*        conn_ptr,
                                                    unsigned int cookie,
                                                    unsigned int clan_tag,
                                                    char const*  clan_creator,
                                                    unsigned int reply) noexcept;

// ── Forward declarations for all handler functions ───────────────────────────
namespace pvpgn { namespace bnetd {

extern int last_news;
extern int first_news;

// handshake.cpp
int _client_unknown_1b(t_connection * c, t_packet const *const packet);
int _client_compinfo1(t_connection * c, t_packet const *const packet);
int _client_compinfo2(t_connection * c, t_packet const *const packet);
int _client_countryinfo1(t_connection * c, t_packet const *const packet);
int _client_auth_info(t_connection * c, t_packet const *const packet);
int _client_unknown2b(t_connection * c, t_packet const *const packet);
int _client_progident(t_connection * c, t_packet const *const packet);

// auth.cpp
int _client_createaccountw3(t_connection * c, t_packet const *const packet);
int _client_createacctreq1(t_connection * c, t_packet const *const packet);
int _client_createacctreq2(t_connection * c, t_packet const *const packet);
int _client_changepassreq(t_connection * c, t_packet const *const packet);
int _client_echoreply(t_connection * c, t_packet const *const packet);
int _client_authreq1(t_connection * c, t_packet const *const packet);
int _client_authreq109(t_connection * c, t_packet const *const packet);
int _client_regsnoopreply(t_connection * c, t_packet const *const packet);
int _client_iconreq(t_connection * c, t_packet const *const packet);
int _client_cdkey(t_connection * c, t_packet const *const packet);
int _client_cdkey2(t_connection * c, t_packet const *const packet);
int _client_cdkey3(t_connection * c, t_packet const *const packet);
int _client_loginreq1(t_connection * c, t_packet const *const packet);
void client_init_email(t_connection * c, t_account * account);
int _client_loginreq2(t_connection * c, t_packet const *const packet);
int _client_loginreqw3(t_connection * c, t_packet const *const packet);
int _client_passchangereq(t_connection * c, t_packet const *const packet);
int _client_passchangeproofreq(t_connection * c, t_packet const *const packet);
int _client_pingreq(t_connection * c, t_packet const *const packet);
int _client_logonproofreq(t_connection * c, t_packet const *const packet);

// chat.cpp
int _client_joinchannel(t_connection * c, t_packet const *const packet);
int _client_message(t_connection * c, t_packet const *const packet);
int _client_leavechannel(t_connection * c, t_packet const *const packet);
int _client_changegameport(t_connection * c, t_packet const *const packet);

// game.cpp
int _glist_cb(t_game * game, void *data);
int _client_gamelistreq(t_connection * c, t_packet const *const packet);
int _client_joingame(t_connection * c, t_packet const *const packet);
int _client_startgame1(t_connection * c, t_packet const *const packet);
int _client_startgame3(t_connection * c, t_packet const *const packet);
int _client_startgame4(t_connection * c, t_packet const *const packet);
int _client_closegame(t_connection * c, t_packet const *const packet);
int _client_gamereport(t_connection * c, t_packet const *const packet);

// friends.cpp
int _client_friendslistreq(t_connection * c, t_packet const *const packet);
int _client_friendinforeq(t_connection * c, t_packet const *const packet);
int _client_atfriendscreen(t_connection * c, t_packet const *const packet);
int _client_atinvitefriend(t_connection * c, t_packet const *const packet);
int _client_atacceptdeclineinvite(t_connection * c, t_packet const *const packet);
int _client_atacceptinvite(t_connection * c, t_packet const *const packet);

// clan.cpp
int _client_claninforeq(t_connection * c, t_packet const *const packet);
int _client_clanmemberlistreq(t_connection * c, t_packet const *const packet);
int _client_clan_motdreq(t_connection * c, t_packet const *const packet);
int _client_clan_motdchg(t_connection * c, t_packet const *const packet);
int _client_clan_disbandreq(t_connection * c, t_packet const *const packet);
int _client_clan_createreq(t_connection * c, t_packet const *const packet);
int _client_clan_createinvitereq(t_connection * c, t_packet const *const packet);
int _client_clan_createinvitereply(t_connection * c, t_packet const *const packet);
int _client_clanmember_rankupdatereq(t_connection * c, t_packet const *const packet);
int _client_clanmember_removereq(t_connection * c, t_packet const *const packet);
int _client_clan_membernewchiefreq(t_connection * c, t_packet const *const packet);
int _client_clan_invitereq(t_connection * c, t_packet const *const packet);
int _client_clan_invitereply(t_connection * c, t_packet const *const packet);

// ladder.cpp
int _client_ladderreq(t_connection * c, t_packet const *const packet);
int _client_laddersearchreq(t_connection * c, t_packet const *const packet);
int _client_mapauthreq1(t_connection * c, t_packet const *const packet);
int _client_mapauthreq2(t_connection * c, t_packet const *const packet);

// realm.cpp
int _client_realmlistreq(t_connection * c, t_packet const *const packet);
int _client_realmlistreq110(t_connection * c, t_packet const *const packet);
int _client_realmjoinreq109(t_connection * c, t_packet const *const packet);
int _client_charlistreq(t_connection * c, t_packet const *const packet);
int _client_unknown39(t_connection * c, t_packet const *const packet);

// file.cpp
int _client_udpok(t_connection * c, t_packet const *const packet);
int _client_fileinforeq(t_connection * c, t_packet const *const packet);
int _client_statsreq(t_connection * c, t_packet const *const packet);
int _client_readmemory(t_connection * c, t_packet const *const packet);

// misc.cpp
int _client_adreq(t_connection * c, t_packet const *const packet);
int _client_adack(t_connection * c, t_packet const *const packet);
int _client_adclick(t_connection * c, t_packet const *const packet);
int _client_adclick2(t_connection * c, t_packet const *const packet);
int _client_statsupdate(t_connection * c, t_packet const *const packet);
int _client_playerinforeq(t_connection * c, t_packet const *const packet);
int _client_progident2(t_connection * c, t_packet const *const packet);
int _client_profilereq(t_connection * c, t_packet const *const packet);
int _news_cb(std::time_t date, t_lstr * lstr, void *data);
int _client_motdw3(t_connection * c, t_packet const *const packet);
int _client_crashdump(t_connection * c, t_packet const *const packet);
int _client_setemailreply(t_connection * c, t_packet const *const packet);
int _client_changeemailreq(t_connection * c, t_packet const *const packet);
int _client_getpasswordreq(t_connection * c, t_packet const *const packet);
int _client_extrawork(t_connection * c, t_packet const *const packet);
int _client_changeclient(t_connection * c, t_packet const *const packet);

}} // namespace pvpgn::bnetd
