// SPDX-License-Identifier: GPL-2.0-or-later
// codec_internal.h — shared declarations for codec/ modules
// Auto-generated by scripts/dev/split_codec.py
#pragma once

#include "protocol/bnet/codec.hpp"

#include <string>

#include "core/error.hpp"
#include "protocol/common/reader.hpp"

// ── Macros (defined here; each TU gets its own copy — no undef needed) ───────
#define RD_U32(target)                                                         \
    do {                                                                       \
        auto v = r.read_le<std::uint32_t>();                                   \
        if (!v) return core::fail(v.error());                                  \
        (target) = v.value();                                                  \
    } while (0)

#define RD_STR(target)                                                         \
    do {                                                                       \
        auto s = r.read_cstring();                                             \
        if (!s) return core::fail(s.error());                                  \
        (target).assign(s.value());                                            \
    } while (0)

#define RD_U64(target)                                                         \
    do {                                                                       \
        auto v = r.read_le<std::uint64_t>();                                   \
        if (!v) return core::fail(v.error());                                  \
        (target) = v.value();                                                  \
    } while (0)

#define RD_U16(target)                                                         \
    do {                                                                       \
        auto v = r.read_le<std::uint16_t>();                                   \
        if (!v) return core::fail(v.error());                                  \
        (target) = v.value();                                                  \
    } while (0)

#define RD_HASH5(target)                                                       \
    do {                                                                       \
        auto h = r.read_bytes(20);                                             \
        if (!h) return core::fail(h.error());                                  \
        std::copy(h.value().begin(), h.value().end(), (target).begin());       \
    } while (0)

namespace pvpgn::protocol::bnet {
namespace detail {

// ── Helpers ──────────────────────────────────────────────────────────────────
core::Failure<core::Error> unimplemented(std::uint8_t code);
core::Status<> check_empty_body(const Packet& pkt);
core::Status<> read_ladder_block(Reader& r, LadderDataBlock& b);
core::Status<> read_strings(Reader& r, std::vector<std::string>& out,
                            std::size_t max_count);
core::Status<> read_friend_list(Reader& r, std::vector<std::string>& out);

// ── Forward declarations for all decode_* functions ──────────────────────────
// auth
core::Result<Ping> decode_ping(const Packet& pkt);
core::Result<AuthInfo> decode_auth_info(const Packet& pkt);
core::Result<AuthCheckReply> decode_auth_check_reply(const Packet& pkt);
core::Result<AuthInfoReply> decode_auth_info_reply(const Packet& pkt);
core::Result<LogonResponse2> decode_logon_response2(const Packet& pkt);
core::Result<LogonResponse2Reply> decode_logon_response2_reply(const Packet& pkt);
core::Result<AuthCheckRequest> decode_auth_check_request(const Packet& pkt);
core::Result<CdKey2Request> decode_cdkey2_request(const Packet& pkt);
core::Result<CdKey2Reply> decode_cdkey2_reply(const Packet& pkt);
core::Result<CdKey3Request> decode_cdkey3_request(const Packet& pkt);
core::Result<CdKey3Reply> decode_cdkey3_reply(const Packet& pkt);
core::Result<FileInfoRequest> decode_file_info_req(const Packet& pkt);
core::Result<FileInfoReply> decode_file_info_reply(const Packet& pkt);
// chat
core::Result<JoinChannel> decode_join_channel(const Packet& pkt);
core::Result<EnterChatRequest> decode_enter_chat_req(const Packet& pkt);
core::Result<EnterChatReply> decode_enter_chat_reply(const Packet& pkt);
core::Result<ChatCommand> decode_chat_command(const Packet& pkt);
core::Result<ChatEvent> decode_chat_event(const Packet& pkt);
core::Result<ChannelListRequest> decode_channel_list_request(const Packet& pkt);
core::Result<ChannelListReply> decode_channel_list_reply(const Packet& pkt);
core::Result<LeaveChannel> decode_leave_channel(const Packet& pkt);
// game
core::Result<GameListRequest> decode_game_list_req(const Packet& pkt);
core::Result<GameListReply> decode_game_list_reply(const Packet& pkt);
core::Result<StartGame4Request> decode_startgame4_request(const Packet& pkt);
core::Result<StartGame4Ack> decode_startgame4_ack(const Packet& pkt);
core::Result<UdpOk> decode_udp_ok(const Packet& pkt);
core::Result<CloseGame> decode_close_game(const Packet& pkt);
core::Result<CloseGame2> decode_close_game2(const Packet& pkt);
core::Result<StartGame1Request> decode_startgame1_request(const Packet& pkt);
core::Result<StartGame1Ack> decode_startgame1_ack(const Packet& pkt);
core::Result<StartGame3Request> decode_startgame3_request(const Packet& pkt);
core::Result<StartGame3Ack> decode_startgame3_ack(const Packet& pkt);
core::Result<JoinGame> decode_join_game(const Packet& pkt);
core::Result<GameReport> decode_game_report(const Packet& pkt);
core::Result<NetGamePort> decode_netgameport(const Packet& pkt);
core::Result<ReadMemoryRequest> decode_read_memory_request(const Packet& pkt);
core::Result<ReadMemoryReply> decode_read_memory_reply(const Packet& pkt);
core::Result<Unknown1B> decode_unknown_1b(const Packet& pkt);
core::Result<Unknown24> decode_unknown_24(const Packet& pkt);
core::Result<MapAuthReq1> decode_mapauthreq1(const Packet& pkt);
core::Result<MapAuthReply1> decode_mapauthreply1(const Packet& pkt);
core::Result<MapAuthReq2> decode_mapauthreq2(const Packet& pkt);
core::Result<MapAuthReply2> decode_mapauthreply2(const Packet& pkt);
core::Result<ChangeClient> decode_change_client(const Packet& pkt);
// friends
core::Result<FriendsListRequest> decode_friendslist_request(const Packet& pkt);
core::Result<FriendsListReply> decode_friendslist_reply(const Packet& pkt);
core::Result<FriendInfoRequest> decode_friendinfo_request(const Packet& pkt);
core::Result<FriendInfoReply> decode_friendinfo_reply(const Packet& pkt);
core::Result<FriendAddAck> decode_friendadd_ack(const Packet& pkt);
core::Result<FriendDelAck> decode_frienddel_ack(const Packet& pkt);
core::Result<FriendMoveAck> decode_friendmove_ack(const Packet& pkt);
core::Result<ArrangedTeamFriendScreenRequest> decode_arrangedteam_friendscreen_request(const Packet& pkt);
core::Result<ArrangedTeamFriendScreenReply> decode_arrangedteam_friendscreen_reply(const Packet& pkt);
core::Result<ArrangedTeamInviteFriendRequest> decode_arrangedteam_invite_friend_request(const Packet& pkt);
core::Result<ArrangedTeamInviteFriendAck> decode_arrangedteam_invite_friend_ack(const Packet& pkt);
core::Result<ArrangedTeamMemberDecline> decode_arrangedteam_member_decline(const Packet& pkt);
core::Result<ArrangedTeamSendInvite> decode_arrangedteam_send_invite(const Packet& pkt);
core::Result<ArrangedTeamAcceptDeclineInvite> decode_arrangedteam_accept_decline_invite(const Packet& pkt);
core::Result<ArrangedTeamAcceptInvite> decode_arrangedteam_accept_invite(const Packet& pkt);
// clan
core::Result<ClanInfoRequest> decode_claninfo_request(const Packet& pkt);
core::Result<ClanInfoReply> decode_claninfo_reply(const Packet& pkt);
core::Result<ClanCreateRequest> decode_clan_create_request(const Packet& pkt);
core::Result<ClanCreateReply> decode_clan_create_reply(const Packet& pkt);
core::Result<ClanDisbandRequest> decode_clan_disband_request(const Packet& pkt);
core::Result<ClanNewChiefRequest> decode_clan_newchief_request(const Packet& pkt);
core::Result<ClanInviteRequest> decode_clan_invite_request(const Packet& pkt);
core::Result<ClanMemberRemoveRequest> decode_clan_member_remove_request(const Packet& pkt);
core::Result<ClanMemberRankUpdateRequest> decode_clan_member_rank_update_request(const Packet& pkt);
core::Result<ClanGenericResultReply> decode_clan_generic_result_reply(const Packet& pkt);
core::Result<ClanMotdChange> decode_clan_motd_change(const Packet& pkt);
core::Result<ClanMotdRequest> decode_clan_motd_request(const Packet& pkt);
core::Result<ClanMotdReply> decode_clan_motd_reply(const Packet& pkt);
core::Result<ClanCreateInviteRequest> decode_clan_create_invite_request(const Packet& pkt);
core::Result<ClanCreateInviteSummary> decode_clan_create_invite_summary(const Packet& pkt);
core::Result<ClanCreateInviteForward> decode_clan_create_invite_forward(const Packet& pkt);
core::Result<ClanCreateInviteResponse> decode_clan_create_invite_response(const Packet& pkt);
core::Result<ClanInvite2Forward> decode_clan_invite2_forward(const Packet& pkt);
core::Result<ClanInvite2Response> decode_clan_invite2_response(const Packet& pkt);
core::Result<ClanMemberListRequest> decode_clan_memberlist_request(const Packet& pkt);
core::Result<ClanMemberListReply> decode_clan_memberlist_reply(const Packet& pkt);
core::Result<ClanMemberRemovedNotify> decode_clan_member_removed_notify(const Packet& pkt);
core::Result<ClanMemberUpdate> decode_clan_member_update(const Packet& pkt);
// ladder / ads / misc
core::Result<LadderSearchRequest> decode_ladder_search_req(const Packet& pkt);
core::Result<LadderSearchReply> decode_ladder_search_reply(const Packet& pkt);
core::Result<LadderListRequest> decode_ladder_list_request(const Packet& pkt);
core::Result<LadderListReply> decode_ladder_list_reply(const Packet& pkt);
core::Result<AdRequest> decode_ad_request(const Packet& pkt);
core::Result<AdReply> decode_ad_reply(const Packet& pkt);
core::Result<AdClick> decode_ad_click(const Packet& pkt);
core::Result<AdAck> decode_ad_ack(const Packet& pkt);
core::Result<AdClick2Request> decode_ad_click2_request(const Packet& pkt);
core::Result<AdClick2Reply> decode_ad_click2_reply(const Packet& pkt);
core::Result<MotdRequest> decode_motd_request(const Packet& pkt);
core::Result<MotdReply> decode_motd_reply(const Packet& pkt);
core::Result<RegSnoopRequest> decode_regsnoop_request(const Packet& pkt);
core::Result<RegSnoopReply> decode_regsnoop_reply(const Packet& pkt);
core::Result<ProfileRequest> decode_profile_request(const Packet& pkt);
core::Result<ProfileReply> decode_profile_reply(const Packet& pkt);
core::Result<SetEmailRequest> decode_setemail_request(const Packet& pkt);
core::Result<SetEmailReply> decode_setemail_reply(const Packet& pkt);
core::Result<IconRequest> decode_icon_request(const Packet& pkt);
core::Result<IconReply> decode_icon_reply(const Packet& pkt);
core::Result<GetPasswordRequest> decode_get_password_request(const Packet& pkt);
core::Result<ChangeEmailRequest> decode_change_email_request(const Packet& pkt);
core::Result<CrashDump> decode_crash_dump(const Packet& pkt);
// realm
core::Result<RealmListRequest> decode_realm_list_request(const Packet& pkt);
core::Result<RealmListReply> decode_realm_list_reply(const Packet& pkt);
core::Result<RealmJoinRequest> decode_realm_join_request(const Packet& pkt);
core::Result<RealmJoinReply> decode_realm_join_reply(const Packet& pkt);
core::Result<CharListRequest> decode_char_list_request(const Packet& pkt);
core::Result<CharListReply> decode_char_list_reply(const Packet& pkt);
core::Result<ServerList> decode_server_list(const Packet& pkt);
core::Result<MessageBox> decode_message_box(const Packet& pkt);
core::Result<RealmListLegacyRequest> decode_realm_list_legacy_request(const Packet& pkt);
core::Result<RealmListLegacyReply> decode_realm_list_legacy_reply(const Packet& pkt);
core::Result<WarcraftGeneralRequest> decode_warcraft_general_request(const Packet& pkt);
core::Result<WarcraftGeneralReply> decode_warcraft_general_reply(const Packet& pkt);
core::Result<RequiredWork> decode_required_work(const Packet& pkt);
core::Result<ExtraWork> decode_extra_work(const Packet& pkt);
// legacy OLS
core::Result<CompInfo1Request> decode_compinfo1_request(const Packet& pkt);
core::Result<CompReply> decode_compreply(const Packet& pkt);
core::Result<ProgIdent> decode_progident(const Packet& pkt);
core::Result<AuthReq1Server> decode_authreq1_server(const Packet& pkt);
core::Result<AuthReq1> decode_authreq1(const Packet& pkt);
core::Result<AuthReply1> decode_authreply1(const Packet& pkt);
core::Result<CountryInfo1> decode_countryinfo1(const Packet& pkt);
core::Result<SessionKey1> decode_sessionkey1(const Packet& pkt);
core::Result<SessionKey2> decode_sessionkey2(const Packet& pkt);
core::Result<CompInfo2> decode_compinfo2(const Packet& pkt);
core::Result<LoginReq1> decode_loginreq1(const Packet& pkt);
core::Result<LoginReply1> decode_loginreply1(const Packet& pkt);
core::Result<CreateAccount1Request> decode_createaccount1_request(const Packet& pkt);
core::Result<CreateAccount1Reply> decode_createaccount1_reply(const Packet& pkt);
core::Result<Unknown2B> decode_unknown_2b(const Packet& pkt);
core::Result<CdKeyLegacyRequest> decode_cdkey_legacy_request(const Packet& pkt);
core::Result<CdKeyLegacyReply> decode_cdkey_legacy_reply(const Packet& pkt);
core::Result<ChangePasswordRequest> decode_changepassword_request(const Packet& pkt);
core::Result<ChangePasswordReply> decode_changepassword_reply(const Packet& pkt);
core::Result<Unknown39> decode_unknown_39(const Packet& pkt);
core::Result<CreateAccountRequest> decode_createaccount_request(const Packet& pkt);
core::Result<CreateAccountReply> decode_createaccount_reply(const Packet& pkt);
// w3
core::Result<CreateAccount2Request> decode_createaccount2_request(const Packet& pkt);
core::Result<CreateAccount2Reply> decode_createaccount2_reply(const Packet& pkt);
core::Result<LoginW3Request> decode_loginw3_request(const Packet& pkt);
core::Result<LoginW3Reply> decode_loginw3_reply(const Packet& pkt);
core::Result<LogonProofW3Request> decode_logonproof_w3_request(const Packet& pkt);
core::Result<LogonProofW3Reply> decode_logonproof_w3_reply(const Packet& pkt);
core::Result<PassChangeRequest> decode_passchange_request(const Packet& pkt);
core::Result<PassChangeReply> decode_passchange_reply(const Packet& pkt);
core::Result<PassChangeProofRequest> decode_passchange_proof_request(const Packet& pkt);
core::Result<PassChangeProofReply> decode_passchange_proof_reply(const Packet& pkt);
core::Result<UserDataReadRequest> decode_userdata_read_request(const Packet& pkt);
core::Result<UserDataReadReply> decode_userdata_read_reply(const Packet& pkt);
core::Result<UserDataWriteRequest> decode_userdata_write_request(const Packet& pkt);

} // namespace detail
} // namespace pvpgn::protocol::bnet
