#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# gen-config-docs.sh — regenerate docs/config-reference.md from the
# pvpgn_config_tool --print-schema output.
#
# Usage
# -----
#   scripts/dev/gen-config-docs.sh [--tool <path>] [--out <path>]
#
# Options
#   --tool <path>   Path to the pvpgn_config_tool binary.
#                   Default: build/src/v3/app/pvpgn-config/pvpgn_config_tool
#   --out  <path>   Output file.
#                   Default: docs/config-reference.md
#
# The script wraps the Markdown table emitted by --print-schema with a
# standard header and footer so the file is a complete, standalone document.
#
# Round 333: initial implementation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

TOOL="${REPO_ROOT}/build/src/v3/app/pvpgn-config/pvpgn_config_tool"
OUT="${REPO_ROOT}/docs/config-reference.md"

# ── argument parsing ──────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
    case "$1" in
        --tool)
            TOOL="$2"
            shift 2
            ;;
        --out)
            OUT="$2"
            shift 2
            ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# ── pre-flight ────────────────────────────────────────────────────────────────

if [[ ! -x "${TOOL}" ]]; then
    echo "ERROR: pvpgn_config_tool not found at: ${TOOL}" >&2
    echo "       Build the project first, or pass --tool <path>." >&2
    exit 1
fi

# ── generate ──────────────────────────────────────────────────────────────────

SCHEMA="$("${TOOL}" --print-schema)"

cat > "${OUT}" <<EOF
<!--
  docs/config-reference.md
  AUTO-GENERATED — do not edit by hand.
  Regenerate with:  scripts/dev/gen-config-docs.sh
-->

# PvPGN v3 Configuration Reference

This document lists every configuration key recognised by the v3 server,
together with its type, default value, and a short description.

The configuration file is a [TOML](https://toml.io/) file (typically
\`bnetd.toml\`).  Sensitive fields (passwords, DSNs) are stored as
\`core::Secret<std::string>\` internally and are never written to logs.

## Environment-variable overrides

Any key can be overridden at runtime without editing the TOML file by
setting an environment variable of the form:

\`\`\`
PVPGN_BNETD__<SECTION>__<KEY>=<value>
\`\`\`

where \`<SECTION>\` and \`<KEY>\` are the TOML section and key names in
**upper-case**, with hyphens replaced by underscores.  For example:

\`\`\`bash
export PVPGN_BNETD__PERSISTENCE__DSN="sqlite:/data/pvpgn.db"
export PVPGN_BNETD__LOG__LEVELS="info,warning,error"
\`\`\`

Secret fields also support indirection:

| Prefix      | Meaning                                              |
|-------------|------------------------------------------------------|
| \`env:<VAR>\`  | Read the value from environment variable \`<VAR>\`   |
| \`file:<path>\`| Read the first non-empty line from \`<path>\`        |
| *(none)*    | Use the literal string as-is                         |

## Config keys

${SCHEMA}

---
*Generated by \`scripts/dev/gen-config-docs.sh\` — Round 333.*
EOF

echo "Written: ${OUT}"
