#!/usr/bin/env python3
"""
Split src/integration/legacy_bnetd/src/handle_bnet_link.cpp into
handle_bnet/ subdirectory modules per plan 15.

Usage:
    python3 scripts/dev/split_handle_bnet.py
"""

import os
import re
import sys

SRC = "src/integration/legacy_bnetd/src/handle_bnet_link.cpp"
OUT_DIR = "src/integration/legacy_bnetd/src/handle_bnet"

# Read source
with open(SRC, "r") as f:
    lines = f.readlines()

total = len(lines)
print(f"Source: {total} lines")

def get_lines(start, end):
    """1-based inclusive range -> list of lines"""
    return lines[start-1:end]

def strip_static(text):
    """Remove 'static ' prefix from function definitions (not declarations)."""
    # Only strip 'static ' at start of line for function definitions
    result = []
    for line in text:
        # Match 'static int _client_' or 'static int _glist_' or 'static int _news_'
        stripped = re.sub(r'^(\t\t)static (int|void) (_client_|_glist_|_news_)', r'\1\2 \3', line)
        result.append(stripped)
    return result

# ─── Common header for all split files ───────────────────────────────────────
COMMON_HEADER = """\
// =====================================================================
// Auto-split from handle_bnet_link.cpp by scripts/dev/split_handle_bnet.py
// See plans/15-large-file-decomposition-detail.md for rationale.
// =====================================================================
#include "handle_bnet_internal.h"
"""

# ─── Internal header content ─────────────────────────────────────────────────
INTERNAL_HEADER = """\
// =====================================================================
// handle_bnet_internal.h — shared declarations for handle_bnet/ modules
// Auto-generated by scripts/dev/split_handle_bnet.py
// =====================================================================
#pragma once

#include "common/setup_before.h"
#include "handle_bnet.h"

#include <cctype>
#include <cerrno>
#include <cinttypes>
#include <cstdint>
#include <cstring>
#include <format>
#include <fstream>
#include <iterator>
#include <limits>
#include <sstream>
#include <string>
#include <tuple>

#include <strings.h>
#include "common/packet.h"
#include "common/eventlog.h"
#include "common/tag.h"
#include "common/bn_type.h"
#include "common/addr.h"
#include "common/bnettime.h"
#include "common/trans.h"
#include "common/list.h"
#include "common/bnethash.h"
#include "common/bnethashconv.h"
#include "common/proginfo.h"
#include "common/util.h"
#include "common/bnetsrp3.h"
#include "common/xstring.h"

#include "handlers.h"
#include "connection.h"
#include "prefs_v3_shim.h"
#include "versioncheck.h"
#include "handle_anongame.h"
#include "account.h"
#include "account_wrap.h"
#include "clan.h"
#include "channel.h"
#include "game.h"
#include "game_conv.h"
#include "ladder.h"
#include "watch.h"
#include "realm.h"
#include "adbanner.h"
#include "character.h"
#include "command.h"
#include "tick.h"
#include "message.h"
#include "file.h"
#include "news.h"
#include "team.h"
#include "server.h"
#include "friends.h"
#include "autoupdate.h"
#include "anongame.h"
#include "i18n.h"
#ifdef WIN32_GUI
#include <win32/winmain.h>
#endif
#include "common/setup_after.h"
#ifdef WITH_LUA
#include "luainterface.h"
#endif

#include "integration/legacy_bnetd/strangler_macros.h"
#include "integration/legacy_bnetd/send_friendslist_bridge.hpp"

// ── All extern "C" bridge declarations ───────────────────────────────────────
extern "C" int pvpgn_v3_send_authreply1(void* conn_ptr,
                                        unsigned int message,
                                        char const* mpqfilename) noexcept;
extern "C" int pvpgn_v3_send_authreply109(void* conn_ptr,
                                          unsigned int message,
                                          char const* mpqfilename) noexcept;
extern "C" int pvpgn_v3_send_authinfo_reply(void* conn_ptr,
                                            unsigned int logontype,
                                            unsigned int server_token,
                                            unsigned int session_num,
                                            unsigned long long timestamp,
                                            char const* mpq_filename,
                                            char const* checksum_formula,
                                            int include_w3_signature) noexcept;
extern "C" int pvpgn_v3_send_loginreply1(void* conn_ptr,
                                         unsigned int message) noexcept;
extern "C" int pvpgn_v3_send_loginreply2(void* conn_ptr,
                                         unsigned int message,
                                         char const* reason) noexcept;
extern "C" int pvpgn_v3_send_createacctreply1(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_createacctreply2(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_createaccount_w3(void* conn_ptr,
                                              unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_iconreply(void* conn_ptr,
                                       unsigned long long timestamp,
                                       char const* filename) noexcept;
extern "C" int pvpgn_v3_send_channellist(void* conn_ptr,
                                         char const* const* names,
                                         unsigned int count) noexcept;
extern "C" int pvpgn_v3_joinchannel_try(void* conn_ptr,
                                        char const* channel_name,
                                        unsigned int flag) noexcept;
extern "C" int pvpgn_v3_leavechannel_try(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_gamereport_try(void* conn_ptr,
                                       char const* username,
                                       unsigned int player_count) noexcept;
extern "C" int pvpgn_v3_startgame_try(void* conn_ptr,
                                      unsigned int version,
                                      char const* gamename,
                                      char const* gameinfo,
                                      unsigned int bngtype,
                                      unsigned int status,
                                      unsigned int flag,
                                      unsigned int option) noexcept;
extern "C" int pvpgn_v3_gamelistreq_try(void* conn_ptr,
                                        char const* gamename,
                                        unsigned int bngtype) noexcept;
extern "C" int pvpgn_v3_joingame_try(void* conn_ptr,
                                     char const* gamename) noexcept;
extern "C" int pvpgn_v3_clan_dispatch_try(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_friends_dispatch_try(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_auth_dispatch_try(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_keepalive_dispatch_try(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_realm_dispatch_try(void* conn_ptr,
                                           char const* op) noexcept;
extern "C" int pvpgn_v3_account_dispatch_try(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_profile_dispatch_try(void* conn_ptr,
                                             char const* op) noexcept;
extern "C" int pvpgn_v3_ladder_dispatch_try(void* conn_ptr,
                                            char const* op) noexcept;
extern "C" int pvpgn_v3_d2_character_dispatch_try(void* conn_ptr,
                                                   char const* op) noexcept;
extern "C" int pvpgn_v3_telemetry_dispatch_try(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_ad_dispatch_try(void* conn_ptr,
                                        char const* op) noexcept;
extern "C" int pvpgn_v3_progident_dispatch_try(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_gameport_dispatch_try(void* conn_ptr,
                                              char const* op) noexcept;
extern "C" int pvpgn_v3_cdkey_dispatch_try(void* conn_ptr,
                                           char const* op) noexcept;
extern "C" int pvpgn_v3_passemail_dispatch_try(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_handshake_dispatch_try(void* conn_ptr,
                                               char const* op) noexcept;
extern "C" int pvpgn_v3_stub_dispatch_try(void* conn_ptr,
                                          char const* op) noexcept;
extern "C" int pvpgn_v3_send_logonproof_reply(void* conn_ptr,
                                              unsigned int response,
                                              unsigned char const* server_password_proof,
                                              char const* custom_reason) noexcept;
extern "C" int pvpgn_v3_send_loginreply_w3(void* conn_ptr,
                                           unsigned int message,
                                           unsigned char const* salt,
                                           unsigned char const* server_public_key) noexcept;
extern "C" int pvpgn_v3_send_compreply(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_send_sessionkey1(void* conn_ptr,
                                         unsigned int sessionkey) noexcept;
extern "C" int pvpgn_v3_send_sessionkey2(void* conn_ptr,
                                         unsigned int sessionnum,
                                         unsigned int sessionkey) noexcept;
extern "C" int pvpgn_v3_send_echoreq(void* conn_ptr,
                                      unsigned int ticks) noexcept;
extern "C" int pvpgn_v3_send_clan_invitereply(void*         conn_ptr,
                                               unsigned int  count,
                                               unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clan_membernewchief_reply(void*         conn_ptr,
                                                        unsigned int  count,
                                                        unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clanmember_remove_reply(void*         conn_ptr,
                                                     unsigned int  count,
                                                     unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_clanmember_rankupdate_reply(void*         conn_ptr,
                                                          unsigned int  count,
                                                          unsigned char result) noexcept;
extern "C" int pvpgn_v3_send_changepassack(void*        conn_ptr,
                                            unsigned int message) noexcept;
extern "C" int pvpgn_v3_send_authreq1_server(void*                conn_ptr,
                                              unsigned long long   timestamp,
                                              char const*          filename,
                                              char const*          equation) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply(void* conn_ptr,
                                         unsigned int message,
                                         char const* owner) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply2(void* conn_ptr,
                                          unsigned int result,
                                          char const* owner) noexcept;
extern "C" int pvpgn_v3_send_cdkeyreply3(void* conn_ptr,
                                          unsigned int message,
                                          char const* owner_name) noexcept;
extern "C" int pvpgn_v3_send_fileinforeply(void*                conn_ptr,
                                            std::uint32_t        type,
                                            std::uint32_t        unknown2,
                                            std::uint64_t        timestamp,
                                            char const*          filename) noexcept;
extern "C" int pvpgn_v3_send_pingreply(void* conn_ptr) noexcept;
extern "C" int pvpgn_v3_send_passchangereply(void*                conn_ptr,
                                              unsigned int         message,
                                              unsigned char const* salt,
                                              unsigned char const* server_public_key) noexcept;
extern "C" int pvpgn_v3_send_passchangeproofreply(void*                conn_ptr,
                                                   unsigned int         response,
                                                   unsigned char const* server_password_proof) noexcept;
extern "C" int pvpgn_v3_send_statsreply(void*              conn_ptr,
                                         unsigned int       name_count,
                                         unsigned int       key_count,
                                         unsigned int       request_id,
                                         char const* const* values,
                                         unsigned int       value_count) noexcept;
struct pvpgn_v3_friend_entry;
extern "C" int pvpgn_v3_send_friendslistreply(
    void*                              conn_ptr,
    struct pvpgn_v3_friend_entry const* entries,
    unsigned int                        count) noexcept;
extern "C" int pvpgn_v3_send_friendinforeply(void*        conn_ptr,
                                              unsigned int friend_num,
                                              unsigned int type,
                                              unsigned int status,
                                              unsigned int client_tag,
                                              char const*  game_name) noexcept;
extern "C" int pvpgn_v3_send_atfriendscreenreply(void*              conn_ptr,
                                                  char const* const* names,
                                                  unsigned int       count) noexcept;
extern "C" int pvpgn_v3_send_atinvitefriendack(void*               conn_ptr,
                                                unsigned int        count,
                                                unsigned int        id,
                                                unsigned int        timestamp,
                                                unsigned int        team_size,
                                                unsigned int const* info) noexcept;
extern "C" int pvpgn_v3_send_atmemberdecline(void*        conn_ptr,
                                              unsigned int count,
                                              unsigned int action,
                                              char const*  decliner_name) noexcept;
extern "C" int pvpgn_v3_send_motdw3(void*        conn_ptr,
                                     unsigned int msg_type,
                                     unsigned int curr_time,
                                     unsigned int first_news_time,
                                     unsigned int timestamp,
                                     unsigned int timestamp2,
                                     char const*  text) noexcept;
struct pvpgn_v3_realm_entry;
extern "C" int pvpgn_v3_send_realmlistreply(void*                             conn_ptr,
                                             struct pvpgn_v3_realm_entry const* entries,
                                             unsigned int                       count) noexcept;
struct pvpgn_v3_realm_legacy_entry;
extern "C" int pvpgn_v3_send_realmlistlegacyreply(
    void*                                     conn_ptr,
    struct pvpgn_v3_realm_legacy_entry const* entries,
    unsigned int                              count) noexcept;
extern "C" int pvpgn_v3_realm_list_apply(void* conn_ptr,
                                          int   legacy_format) noexcept;
extern "C" int pvpgn_v3_send_claninforeply(void*        conn_ptr,
                                            unsigned int cookie,
                                            unsigned int fail,
                                            char const*  clan_name,
                                            unsigned int rank,
                                            unsigned int join_time) noexcept;
extern "C" int pvpgn_v3_send_profilereply(void*        conn_ptr,
                                           unsigned int cookie,
                                           unsigned int fail,
                                           char const*  description,
                                           char const*  location,
                                           unsigned int clan_tag) noexcept;
extern "C" int pvpgn_v3_send_realmjoinreply(void*               conn_ptr,
                                             unsigned int        seqno,
                                             unsigned int        u1,
                                             unsigned int        bncs_addr1,
                                             unsigned int        session_num,
                                             unsigned int        addr,
                                             unsigned int        port,
                                             unsigned int        u3,
                                             unsigned int        session_key,
                                             unsigned int        u5,
                                             unsigned int        u6,
                                             unsigned int        client_tag,
                                             unsigned int        version_id,
                                             unsigned int        bncs_addr2,
                                             unsigned int        u7,
                                             unsigned int const* secret_hash,
                                             char const*         account_name) noexcept;
extern "C" int pvpgn_v3_send_charlistreply(void*                conn_ptr,
                                            unsigned int         unknown1,
                                            unsigned int         max_chars,
                                            unsigned int         count,
                                            unsigned char const* char_data,
                                            unsigned int         char_data_len) noexcept;
extern "C" int pvpgn_v3_send_adreply(void*                conn_ptr,
                                      unsigned int         adid,
                                      unsigned int         extension_tag,
                                      unsigned long long   timestamp,
                                      char const*          filename,
                                      char const*          link) noexcept;
extern "C" int pvpgn_v3_send_adclick2reply(void*        conn_ptr,
                                            unsigned int adid,
                                            char const*  link) noexcept;
struct PvpgnV3AdPickOut {
    int          found;
    unsigned int id;
    unsigned int extension_tag;
    char         filename[256];
    char         url[1024];
};
struct PvpgnV3AdClickOut {
    int          accepted;
    unsigned int id;
    char         click_url[1024];
};
extern "C" int pvpgn_v3_ads_pick_apply(unsigned int client_tag,
                                       unsigned int lang_tag,
                                       unsigned int prev_ad_id,
                                       PvpgnV3AdPickOut* out) noexcept;
extern "C" int pvpgn_v3_ads_click_apply(unsigned int client_tag,
                                        unsigned int lang_tag,
                                        unsigned int ad_id,
                                        PvpgnV3AdClickOut* out) noexcept;
extern "C" int pvpgn_v3_send_playerinforeply(void*       conn_ptr,
                                              char const* account_name,
                                              char const* player_info,
                                              char const* username) noexcept;
struct pvpgn_v3_game_list_entry;
extern "C" int pvpgn_v3_send_gamelistreply(
    void*                                    conn_ptr,
    std::uint32_t                            sstatus,
    struct pvpgn_v3_game_list_entry const*   entries,
    unsigned int                             count) noexcept;
extern "C" int pvpgn_v3_send_startgame1ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
extern "C" int pvpgn_v3_send_startgame3ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
extern "C" int pvpgn_v3_send_startgame4ack(void*        conn_ptr,
                                            unsigned int reply) noexcept;
struct pvpgn_v3_ladder_list_entry;
extern "C" int pvpgn_v3_send_ladderreply(
    void*                                      conn_ptr,
    unsigned int                               client_tag,
    unsigned int                               id,
    unsigned int                               type,
    unsigned int                               start,
    unsigned int                               count,
    struct pvpgn_v3_ladder_list_entry const*   entries) noexcept;
extern "C" int pvpgn_v3_send_laddersearchreply(void*        conn_ptr,
                                                unsigned int rank) noexcept;
extern "C" int pvpgn_v3_send_mapauthreply1(void*        conn_ptr,
                                            unsigned int response) noexcept;
extern "C" int pvpgn_v3_send_mapauthreply2(void*        conn_ptr,
                                            unsigned int response) noexcept;
extern "C" int pvpgn_v3_send_clandisbandreply(void*        conn_ptr,
                                               unsigned int cookie,
                                               unsigned int result) noexcept;
extern "C" int pvpgn_v3_send_clancreateinviteforward(
    void*                conn_ptr,
    unsigned int         cookie,
    unsigned int         clan_tag,
    char const*          clan_name,
    char const*          clan_creator,
    char const* const*   member_names,
    unsigned int         member_count) noexcept;
extern "C" int pvpgn_v3_send_clancreateinvitereply(void*        conn_ptr,
                                                    unsigned int cookie,
                                                    unsigned int clan_tag,
                                                    char const*  clan_creator,
                                                    unsigned int reply) noexcept;

// ── Forward declarations for all handler functions ───────────────────────────
namespace pvpgn { namespace bnetd {

extern int last_news;
extern int first_news;

// handshake.cpp
int _client_unknown_1b(t_connection * c, t_packet const *const packet);
int _client_compinfo1(t_connection * c, t_packet const *const packet);
int _client_compinfo2(t_connection * c, t_packet const *const packet);
int _client_countryinfo1(t_connection * c, t_packet const *const packet);
int _client_auth_info(t_connection * c, t_packet const *const packet);
int _client_unknown2b(t_connection * c, t_packet const *const packet);
int _client_progident(t_connection * c, t_packet const *const packet);

// auth.cpp
int _client_createaccountw3(t_connection * c, t_packet const *const packet);
int _client_createacctreq1(t_connection * c, t_packet const *const packet);
int _client_createacctreq2(t_connection * c, t_packet const *const packet);
int _client_changepassreq(t_connection * c, t_packet const *const packet);
int _client_echoreply(t_connection * c, t_packet const *const packet);
int _client_authreq1(t_connection * c, t_packet const *const packet);
int _client_authreq109(t_connection * c, t_packet const *const packet);
int _client_regsnoopreply(t_connection * c, t_packet const *const packet);
int _client_iconreq(t_connection * c, t_packet const *const packet);
int _client_cdkey(t_connection * c, t_packet const *const packet);
int _client_cdkey2(t_connection * c, t_packet const *const packet);
int _client_cdkey3(t_connection * c, t_packet const *const packet);
int _client_loginreq1(t_connection * c, t_packet const *const packet);
void client_init_email(t_connection * c, t_account * account);
int _client_loginreq2(t_connection * c, t_packet const *const packet);
int _client_loginreqw3(t_connection * c, t_packet const *const packet);
int _client_passchangereq(t_connection * c, t_packet const *const packet);
int _client_passchangeproofreq(t_connection * c, t_packet const *const packet);
int _client_pingreq(t_connection * c, t_packet const *const packet);
int _client_logonproofreq(t_connection * c, t_packet const *const packet);

// chat.cpp
int _client_joinchannel(t_connection * c, t_packet const *const packet);
int _client_message(t_connection * c, t_packet const *const packet);
int _client_leavechannel(t_connection * c, t_packet const *const packet);
int _client_changegameport(t_connection * c, t_packet const *const packet);

// game.cpp
int _glist_cb(t_game * game, void *data);
int _client_gamelistreq(t_connection * c, t_packet const *const packet);
int _client_joingame(t_connection * c, t_packet const *const packet);
int _client_startgame1(t_connection * c, t_packet const *const packet);
int _client_startgame3(t_connection * c, t_packet const *const packet);
int _client_startgame4(t_connection * c, t_packet const *const packet);
int _client_closegame(t_connection * c, t_packet const *const packet);
int _client_gamereport(t_connection * c, t_packet const *const packet);

// friends.cpp
int _client_friendslistreq(t_connection * c, t_packet const *const packet);
int _client_friendinforeq(t_connection * c, t_packet const *const packet);
int _client_atfriendscreen(t_connection * c, t_packet const *const packet);
int _client_atinvitefriend(t_connection * c, t_packet const *const packet);
int _client_atacceptdeclineinvite(t_connection * c, t_packet const *const packet);
int _client_atacceptinvite(t_connection * c, t_packet const *const packet);

// clan.cpp
int _client_claninforeq(t_connection * c, t_packet const *const packet);
int _client_clanmemberlistreq(t_connection * c, t_packet const *const packet);
int _client_clan_motdreq(t_connection * c, t_packet const *const packet);
int _client_clan_motdchg(t_connection * c, t_packet const *const packet);
int _client_clan_disbandreq(t_connection * c, t_packet const *const packet);
int _client_clan_createreq(t_connection * c, t_packet const *const packet);
int _client_clan_createinvitereq(t_connection * c, t_packet const *const packet);
int _client_clan_createinvitereply(t_connection * c, t_packet const *const packet);
int _client_clanmember_rankupdatereq(t_connection * c, t_packet const *const packet);
int _client_clanmember_removereq(t_connection * c, t_packet const *const packet);
int _client_clan_membernewchiefreq(t_connection * c, t_packet const *const packet);
int _client_clan_invitereq(t_connection * c, t_packet const *const packet);
int _client_clan_invitereply(t_connection * c, t_packet const *const packet);

// ladder.cpp
int _client_ladderreq(t_connection * c, t_packet const *const packet);
int _client_laddersearchreq(t_connection * c, t_packet const *const packet);
int _client_mapauthreq1(t_connection * c, t_packet const *const packet);
int _client_mapauthreq2(t_connection * c, t_packet const *const packet);

// realm.cpp
int _client_realmlistreq(t_connection * c, t_packet const *const packet);
int _client_realmlistreq110(t_connection * c, t_packet const *const packet);
int _client_realmjoinreq109(t_connection * c, t_packet const *const packet);
int _client_charlistreq(t_connection * c, t_packet const *const packet);
int _client_unknown39(t_connection * c, t_packet const *const packet);

// file.cpp
int _client_udpok(t_connection * c, t_packet const *const packet);
int _client_fileinforeq(t_connection * c, t_packet const *const packet);
int _client_statsreq(t_connection * c, t_packet const *const packet);
int _client_readmemory(t_connection * c, t_packet const *const packet);

// misc.cpp
int _client_adreq(t_connection * c, t_packet const *const packet);
int _client_adack(t_connection * c, t_packet const *const packet);
int _client_adclick(t_connection * c, t_packet const *const packet);
int _client_adclick2(t_connection * c, t_packet const *const packet);
int _client_statsupdate(t_connection * c, t_packet const *const packet);
int _client_playerinforeq(t_connection * c, t_packet const *const packet);
int _client_progident2(t_connection * c, t_packet const *const packet);
int _client_profilereq(t_connection * c, t_packet const *const packet);
int _news_cb(std::time_t date, t_lstr * lstr, void *data);
int _client_motdw3(t_connection * c, t_packet const *const packet);
int _client_crashdump(t_connection * c, t_packet const *const packet);
int _client_setemailreply(t_connection * c, t_packet const *const packet);
int _client_changeemailreq(t_connection * c, t_packet const *const packet);
int _client_getpasswordreq(t_connection * c, t_packet const *const packet);
int _client_extrawork(t_connection * c, t_packet const *const packet);
int _client_changeclient(t_connection * c, t_packet const *const packet);

}} // namespace pvpgn::bnetd
"""

# ─── Function ranges per plan ─────────────────────────────────────────────────
# Each entry: (filename, [(start, end), ...])
# Ranges are 1-based inclusive from the original file.
# The functions are inside `namespace pvpgn { namespace bnetd {` so we wrap them.

FILES = {
    "handshake.cpp": [
        (797, 821),    # _client_unknown_1b
        (823, 870),    # _client_compinfo1
        (872, 924),    # _client_compinfo2
        (926, 965),    # _client_countryinfo1
        (967, 1110),   # _client_auth_info
        (1112, 1120),  # _client_unknown2b
        (1122, 1181),  # _client_progident
    ],
    "auth.cpp": [
        (1183, 1314),  # _client_createaccountw3
        (1316, 1371),  # _client_createacctreq1
        (1373, 1435),  # _client_createacctreq2
        (1437, 1546),  # _client_changepassreq
        (1548, 1569),  # _client_echoreply
        (1571, 1728),  # _client_authreq1
        (1730, 1873),  # _client_authreq109
        (1875, 1883),  # _client_regsnoopreply
        (1885, 1936),  # _client_iconreq
        (1938, 1989),  # _client_cdkey
        (1991, 2025),  # _client_cdkey2
        (2027, 2061),  # _client_cdkey3
        (2244, 2390),  # _client_loginreq1
        (2392, 2408),  # client_init_email
        (2410, 2593),  # _client_loginreq2
        (2595, 2730),  # _client_loginreqw3
        (2732, 2854),  # _client_passchangereq
        (2856, 2946),  # _client_passchangeproofreq
        (2948, 2967),  # _client_pingreq
        (2969, 3110),  # _client_logonproofreq
    ],
    "chat.cpp": [
        (3112, 3130),  # _client_changegameport
        (4810, 4891),  # _client_joinchannel
        (4893, 4942),  # _client_message
        (5682, 5690),  # _client_leavechannel
    ],
    "game.cpp": [
        (4944, 5025),  # _glist_cb
        (5027, 5163),  # _client_gamelistreq
        (5165, 5230),  # _client_joingame
        (5232, 5325),  # _client_startgame1
        (5327, 5418),  # _client_startgame3
        (5420, 5560),  # _client_startgame4
        (5562, 5573),  # _client_closegame
        (5575, 5680),  # _client_gamereport
    ],
    "friends.cpp": [
        (3132, 3279),  # _client_friendslistreq
        (3281, 3406),  # _client_friendinforeq
        (3408, 3589),  # _client_atfriendscreen
        (3591, 3756),  # _client_atinvitefriend
        (3758, 3808),  # _client_atacceptdeclineinvite
        (3810, 3820),  # _client_atacceptinvite
    ],
    "clan.cpp": [
        (4019, 4094),  # _client_claninforeq
        (6134, 6144),  # _client_clanmemberlistreq
        (6146, 6156),  # _client_clan_motdreq
        (6158, 6168),  # _client_clan_motdchg
        (6170, 6222),  # _client_clan_disbandreq
        (6224, 6235),  # _client_clan_createreq
        (6237, 6330),  # _client_clan_createinvitereq
        (6332, 6417),  # _client_clan_createinvitereply
        (6419, 6497),  # _client_clanmember_rankupdatereq
        (6499, 6558),  # _client_clanmember_removereq
        (6560, 6602),  # _client_clan_membernewchiefreq
        (6604, 6692),  # _client_clan_invitereq
        (6694, 6793),  # _client_clan_invitereply
    ],
    "ladder.cpp": [
        (5692, 5867),  # _client_ladderreq
        (5869, 5966),  # _client_laddersearchreq
        (5968, 6037),  # _client_mapauthreq1
        (6039, 6108),  # _client_mapauthreq2
    ],
    "realm.cpp": [
        (3967, 3993),  # _client_realmlistreq
        (3995, 4017),  # _client_realmlistreq110
        (4159, 4336),  # _client_realmjoinreq109
        (4338, 4438),  # _client_charlistreq
        (4440, 4448),  # _client_unknown39
    ],
    "file.cpp": [
        (2063, 2074),  # _client_udpok
        (2076, 2129),  # _client_fileinforeq
        # Note: 2130-2148 is a blank/comment gap between fileinforeq and statsreq
        (2149, 2242),  # _client_statsreq
        (4593, 4619),  # _client_readmemory
    ],
    "misc.cpp": [
        (3822, 3965),  # _news_cb + _client_motdw3 (includes typedef at 3822)
        (4096, 4156),  # _client_profilereq
        (4450, 4512),  # _client_adreq
        (4514, 4531),  # _client_adack
        (4533, 4544),  # _client_adclick
        (4546, 4591),  # _client_adclick2
        (4621, 4680),  # _client_statsupdate
        (4682, 4744),  # _client_playerinforeq
        (4746, 4808),  # _client_progident2
        (6110, 6132),  # _client_changeclient
        (6795, 6799),  # _client_crashdump
        (6801, 6826),  # _client_setemailreply
        (6828, 6872),  # _client_changeemailreq
        (6874, 6909),  # _client_getpasswordreq
        (6913, 6942),  # _client_extrawork
    ],
}

os.makedirs(OUT_DIR, exist_ok=True)

# Write internal header
with open(os.path.join(OUT_DIR, "handle_bnet_internal.h"), "w") as f:
    f.write(INTERNAL_HEADER)
print(f"  Wrote handle_bnet_internal.h")

# Write each split file
for filename, ranges in FILES.items():
    parts = []
    for (start, end) in ranges:
        chunk = get_lines(start, end)
        parts.extend(chunk)
        # Add blank line between functions if not already present
        if parts and parts[-1].strip():
            parts.append("\n")

    # Strip 'static' from function definitions
    parts = strip_static(parts)

    content = COMMON_HEADER
    content += "\nnamespace pvpgn { namespace bnetd {\n\n"
    content += "".join(parts)
    content += "\n}} // namespace pvpgn::bnetd\n"

    out_path = os.path.join(OUT_DIR, filename)
    with open(out_path, "w") as f:
        f.write(content)
    loc = len(parts)
    print(f"  Wrote {filename} ({loc} lines from {len(ranges)} ranges)")

print("\nDone. Now update handle_bnet_link.cpp to be the dispatcher.")
