#!/usr/bin/env python3
"""
split_irc_link.py — Decompose irc_link.cpp (2526 LOC) into irc/ sub-modules.

Plan reference: plans/15-large-file-decomposition-detail.md §4 (Decomposition 05.1b)

Output layout:
  src/integration/legacy_bnetd/src/
    irc_link.cpp                  (dispatcher, ~300 LOC — rewritten in place)
    irc/
      irc_internal.h              (shared forward decls)
      irc_send.cpp                (send utilities + element helpers)
      irc_format.cpp              (message formatting)
      irc_channel.cpp             (channel/user ops)
      irc_commands.cpp            (shared command handlers)
      irc_handlers.cpp            (IRC-specific handlers)
"""

import os
import pathlib

SRC = pathlib.Path("src/integration/legacy_bnetd/src/irc_link.cpp")
OUT_DIR = pathlib.Path("src/integration/legacy_bnetd/src/irc")

# ---------------------------------------------------------------------------
# Read source
# ---------------------------------------------------------------------------
lines = SRC.read_text().splitlines(keepends=True)
# lines[i] is 1-based line i+1

def get_lines(start, end):
    """Return lines[start-1 : end] (1-based inclusive)."""
    return "".join(lines[start - 1 : end])

# ---------------------------------------------------------------------------
# File header (copyright + includes) — lines 1-65
# ---------------------------------------------------------------------------
FILE_HEADER = get_lines(1, 65)

# Namespace wrappers
NS_OPEN  = "\nnamespace pvpgn\n{\n\n\tnamespace bnetd\n\t{\n\n"
NS_CLOSE = "\n\t}\n\n}\n"

# ---------------------------------------------------------------------------
# irc_internal.h
# ---------------------------------------------------------------------------
IRC_INTERNAL_H = """\
// SPDX-License-Identifier: GPL-2.0-or-later
// irc_internal.h — shared forward declarations for irc/ sub-modules
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#pragma once

#include "common/setup_before.h"
#include "irc.h"

#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>

#include <strings.h>

#include "common/irc_protocol.h"
#include "common/packet.h"
#include "common/eventlog.h"
#include "common/field_sizes.h"
#include "common/bnethash.h"
#include "common/addr.h"
#include "common/tag.h"
#include "common/list.h"
#include "common/util.h"
#include "common/xstring.h"

#include "message.h"
#include "channel.h"
#include "game.h"
#include "connection.h"
#include "server.h"
#include "account.h"
#include "account_wrap.h"
#include "prefs_v3_shim.h"
#include "tick.h"
#include "handle_wol.h"
#include "command_groups.h"
#include "topic.h"
#include "clan.h"
#include "command.h"
#include "anongame_wol.h"
#include "common/setup_after.h"

namespace pvpgn
{

\tnamespace bnetd
\t{

\t\ttypedef struct {
\t\t\tchar const * nick;
\t\t\tchar const * user;
\t\t\tchar const * host;
\t\t} t_irc_message_from;

\t\t// irc_send.cpp
\t\textern int irc_send_cmd(t_connection * conn, char const * command, char const * params);
\t\textern int irc_send(t_connection * conn, int code, char const * params);
\t\textern int irc_send_ping(t_connection * conn);
\t\textern int irc_send_pong(t_connection * conn, char const * params);
\t\textern int irc_authenticate(t_connection * conn, char const * passhash);
\t\textern char const * irc_convert_channel(t_channel const * channel, t_connection * c);
\t\textern char const * irc_convert_ircname(char const * pircname);
\t\textern char ** irc_get_listelems(char * list);
\t\textern int irc_unget_listelems(char ** elems);
\t\textern char ** irc_get_paramelems(char * list);
\t\textern int irc_unget_paramelems(char ** elems);
\t\textern char ** irc_get_ladderelems(char * list);
\t\textern int irc_unget_ladderelems(char ** elems);

\t\t// irc_format.cpp
\t\textern int irc_message_postformat(t_packet * packet, t_connection const * dest);
\t\textern int irc_message_format(t_packet * packet, t_message_type type, t_connection * me, t_connection * dst, char const * text, unsigned int dstflags);

\t\t// irc_channel.cpp
\t\tint irc_send_rpl_namreply_internal(t_connection * c, t_channel const * channel);
\t\textern int irc_send_rpl_namreply(t_connection * c, t_channel const * channel);
\t\textern int irc_who(t_connection * c, char const * name);
\t\textern int irc_send_motd(t_connection * conn);
\t\tint irc_welcome(t_connection * conn);

\t\t// irc_commands.cpp
\t\textern int _handle_nick_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_ping_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_pong_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_join_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int irc_send_topic(t_connection * c, t_channel const * channel);
\t\textern int _handle_topic_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_kick_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_mode_command(t_connection * conn, int numparams, char ** params, char * text);
\t\textern int _handle_time_command(t_connection * conn, int numparams, char ** params, char * text);

\t\t// irc_handlers.cpp (originally static — promoted to internal linkage via irc_internal.h)
\t\tint _handle_user_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_pass_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_privmsg_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_notice_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_quit_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_who_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_list_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_names_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_userhost_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_ison_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_whois_command(t_connection * conn, int numparams, char ** params, char * text);
\t\tint _handle_part_command(t_connection * conn, int numparams, char ** params, char * text);

\t} // namespace bnetd

} // namespace pvpgn
"""

# ---------------------------------------------------------------------------
# Exact line ranges (1-based inclusive) for each sub-file
# ---------------------------------------------------------------------------
# irc_send.cpp: irc_strdup helper + send functions + element helpers
# Lines 86-538 (irc_strdup through irc_unget_ladderelems)
IRC_SEND_LINES = (86, 538)

# irc_format.cpp: irc_message_preformat + irc_message_postformat + irc_message_format
# Lines 540-1004
IRC_FORMAT_LINES = (540, 1004)

# irc_channel.cpp: irc_send_rpl_namreply_internal through irc_welcome
# Lines 1006-1352
IRC_CHANNEL_LINES = (1006, 1352)

# irc_commands.cpp: _handle_nick_command through _handle_time_command
# Lines 1354-1757
IRC_COMMANDS_LINES = (1354, 1757)

# irc_handlers.cpp: _handle_user_command through _handle_part_command
# Lines 1759-2164
IRC_HANDLERS_LINES = (1759, 2164)

# irc_link.cpp dispatcher: command tables + dispatch + common + packet handler
# Lines 2166-2526
IRC_DISPATCH_LINES = (2166, 2526)

# ---------------------------------------------------------------------------
# Helper: strip the extra indentation level from a block of lines
# The original file uses \t\t\t (3 tabs) for most content inside
# namespace pvpgn { namespace bnetd { ... } }
# We want to keep \t\t (2 tabs) for content inside the namespace wrappers
# ---------------------------------------------------------------------------
def extract_block(start, end):
    """Extract lines start..end (1-based inclusive) as a string."""
    return "".join(lines[start - 1 : end])

# ---------------------------------------------------------------------------
# Build sub-file content
# ---------------------------------------------------------------------------
SUBFILE_HEADER = """\
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"
"""

def make_subfile(block_start, block_end):
    block = extract_block(block_start, block_end)
    return SUBFILE_HEADER + NS_OPEN + block + NS_CLOSE

# ---------------------------------------------------------------------------
# irc_link.cpp dispatcher content
# The dispatch section (2166-2526) already has the closing braces for
# namespace bnetd and namespace pvpgn at lines 2523-2526.
# We need to include the file header + the dispatch section as-is.
# ---------------------------------------------------------------------------
def make_dispatcher():
    dispatch_block = extract_block(IRC_DISPATCH_LINES[0], IRC_DISPATCH_LINES[1])
    return (
        FILE_HEADER
        + "\n#include \"irc/irc_internal.h\"\n"
        + "\nextern \"C\" int pvpgn_v3_send_raw_text(void* conn_ptr, char const* text) noexcept;\n"
        + NS_OPEN
        + dispatch_block
        # The original file already has the closing braces at 2523-2526
        # but we stripped them by taking only 2166-2526 which includes them
    )

# ---------------------------------------------------------------------------
# Write files
# ---------------------------------------------------------------------------
OUT_DIR.mkdir(parents=True, exist_ok=True)

# irc_internal.h
(OUT_DIR / "irc_internal.h").write_text(IRC_INTERNAL_H)
print(f"  wrote {OUT_DIR}/irc_internal.h")

# irc_send.cpp
content = make_subfile(*IRC_SEND_LINES)
(OUT_DIR / "irc_send.cpp").write_text(content)
print(f"  wrote {OUT_DIR}/irc_send.cpp  ({IRC_SEND_LINES[1]-IRC_SEND_LINES[0]+1} source lines)")

# irc_format.cpp
content = make_subfile(*IRC_FORMAT_LINES)
(OUT_DIR / "irc_format.cpp").write_text(content)
print(f"  wrote {OUT_DIR}/irc_format.cpp  ({IRC_FORMAT_LINES[1]-IRC_FORMAT_LINES[0]+1} source lines)")

# irc_channel.cpp
content = make_subfile(*IRC_CHANNEL_LINES)
(OUT_DIR / "irc_channel.cpp").write_text(content)
print(f"  wrote {OUT_DIR}/irc_channel.cpp  ({IRC_CHANNEL_LINES[1]-IRC_CHANNEL_LINES[0]+1} source lines)")

# irc_commands.cpp
content = make_subfile(*IRC_COMMANDS_LINES)
(OUT_DIR / "irc_commands.cpp").write_text(content)
print(f"  wrote {OUT_DIR}/irc_commands.cpp  ({IRC_COMMANDS_LINES[1]-IRC_COMMANDS_LINES[0]+1} source lines)")

# irc_handlers.cpp
# The handlers section uses 'static' keyword — we need to strip 'static' from
# the function definitions since they're now in a separate TU and forward-declared
# in irc_internal.h without 'static'.
handlers_block = extract_block(*IRC_HANDLERS_LINES)
# Replace 'static int _handle_' with 'int _handle_' (remove static linkage)
handlers_block = handlers_block.replace("\t\t\tstatic int _handle_", "\t\t\tint _handle_")
handlers_block = handlers_block.replace("\t\t\t\tstatic int _handle_", "\t\t\t\tint _handle_")
# Also handle the extra-indented versions (some have 4 tabs)
handlers_block = handlers_block.replace("\t\t\t\t\tstatic int _handle_", "\t\t\t\t\tint _handle_")
content = SUBFILE_HEADER + NS_OPEN + handlers_block + NS_CLOSE
(OUT_DIR / "irc_handlers.cpp").write_text(content)
print(f"  wrote {OUT_DIR}/irc_handlers.cpp  ({IRC_HANDLERS_LINES[1]-IRC_HANDLERS_LINES[0]+1} source lines)")

# irc_link.cpp (dispatcher — rewrite in place)
# The dispatch section (2166-2526) already contains the closing namespace braces.
# We need: file header + include irc_internal.h + extern C decl + namespace open + dispatch content
# But the dispatch content (2166-2526) already ends with the namespace closing braces.
# So we DON'T add NS_CLOSE again.
dispatch_block = extract_block(IRC_DISPATCH_LINES[0], IRC_DISPATCH_LINES[1])
dispatcher_content = (
    FILE_HEADER
    + "\n#include \"irc/irc_internal.h\"\n"
    + "\nextern \"C\" int pvpgn_v3_send_raw_text(void* conn_ptr, char const* text) noexcept;\n"
    + "\nnamespace pvpgn\n{\n\n\tnamespace bnetd\n\t{\n\n"
    + dispatch_block
    # dispatch_block already ends with:
    #   \t}\n\n}\n  (lines 2523-2526)
)
SRC.write_text(dispatcher_content)
print(f"  rewrote {SRC}  (dispatcher, lines {IRC_DISPATCH_LINES[0]}-{IRC_DISPATCH_LINES[1]})")

print("\nDone. Files written:")
for f in sorted(OUT_DIR.iterdir()):
    sz = f.stat().st_size
    lc = len(f.read_text().splitlines())
    print(f"  {f}  ({lc} lines, {sz} bytes)")
print(f"  {SRC}  ({len(SRC.read_text().splitlines())} lines)")
