#!/usr/bin/env python3
"""
Split src/protocol/bnet/src/codec.cpp into codec/ subdirectory modules
per plan 15 §8.

Usage:
    python3 scripts/dev/split_codec.py
"""

import os

SRC = "src/protocol/bnet/src/codec.cpp"
OUT_DIR = "src/protocol/bnet/src/codec"

with open(SRC, "r") as f:
    lines = f.readlines()

total = len(lines)
print(f"Source: {total} lines")

def get_lines(start, end):
    """1-based inclusive range -> list of lines"""
    return lines[start-1:end]

# ─── Common header for all split files ───────────────────────────────────────
# decode functions go in pvpgn::protocol::bnet::detail
# encode functions go in pvpgn::protocol::bnet (outer namespace)
# The file structure is:
#   #include "codec_internal.h"
#   namespace pvpgn::protocol::bnet {
#   namespace detail {
#   ... decode functions ...
#   } // namespace detail
#   ... encode functions ...
#   } // namespace pvpgn::protocol::bnet

FILE_HEADER = """\
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-split from codec.cpp by scripts/dev/split_codec.py
// See plans/15-large-file-decomposition-detail.md §8 for rationale.
#include "codec_internal.h"

namespace pvpgn::protocol::bnet {
namespace detail {

"""

DETAIL_CLOSE = """\

} // namespace detail

"""

OUTER_CLOSE = """\

} // namespace pvpgn::protocol::bnet
"""

# ─── Internal header ─────────────────────────────────────────────────────────
INTERNAL_HEADER = """\
// SPDX-License-Identifier: GPL-2.0-or-later
// codec_internal.h — shared declarations for codec/ modules
// Auto-generated by scripts/dev/split_codec.py
#pragma once

#include "protocol/bnet/codec.hpp"

#include <string>

#include "core/error.hpp"
#include "protocol/common/reader.hpp"

// ── Macros (defined here; each TU gets its own copy — no undef needed) ───────
#define RD_U32(target)                                                         \\
    do {                                                                       \\
        auto v = r.read_le<std::uint32_t>();                                   \\
        if (!v) return core::fail(v.error());                                  \\
        (target) = v.value();                                                  \\
    } while (0)

#define RD_STR(target)                                                         \\
    do {                                                                       \\
        auto s = r.read_cstring();                                             \\
        if (!s) return core::fail(s.error());                                  \\
        (target).assign(s.value());                                            \\
    } while (0)

#define RD_U64(target)                                                         \\
    do {                                                                       \\
        auto v = r.read_le<std::uint64_t>();                                   \\
        if (!v) return core::fail(v.error());                                  \\
        (target) = v.value();                                                  \\
    } while (0)

#define RD_U16(target)                                                         \\
    do {                                                                       \\
        auto v = r.read_le<std::uint16_t>();                                   \\
        if (!v) return core::fail(v.error());                                  \\
        (target) = v.value();                                                  \\
    } while (0)

#define RD_HASH5(target)                                                       \\
    do {                                                                       \\
        auto h = r.read_bytes(20);                                             \\
        if (!h) return core::fail(h.error());                                  \\
        std::copy(h.value().begin(), h.value().end(), (target).begin());       \\
    } while (0)

namespace pvpgn::protocol::bnet {
namespace detail {

// ── Helpers ──────────────────────────────────────────────────────────────────
core::Failure<core::Error> unimplemented(std::uint8_t code);
core::Status<> check_empty_body(const Packet& pkt);
core::Status<> read_ladder_block(Reader& r, LadderDataBlock& b);
core::Status<> read_strings(Reader& r, std::vector<std::string>& out,
                            std::size_t max_count);
core::Status<> read_friend_list(Reader& r, std::vector<std::string>& out);

// ── Forward declarations for all decode_* functions ──────────────────────────
// auth
core::Result<Ping> decode_ping(const Packet& pkt);
core::Result<AuthInfo> decode_auth_info(const Packet& pkt);
core::Result<AuthCheckReply> decode_auth_check_reply(const Packet& pkt);
core::Result<AuthInfoReply> decode_auth_info_reply(const Packet& pkt);
core::Result<LogonResponse2> decode_logon_response2(const Packet& pkt);
core::Result<LogonResponse2Reply> decode_logon_response2_reply(const Packet& pkt);
core::Result<AuthCheckRequest> decode_auth_check_request(const Packet& pkt);
core::Result<CdKey2Request> decode_cdkey2_request(const Packet& pkt);
core::Result<CdKey2Reply> decode_cdkey2_reply(const Packet& pkt);
core::Result<CdKey3Request> decode_cdkey3_request(const Packet& pkt);
core::Result<CdKey3Reply> decode_cdkey3_reply(const Packet& pkt);
core::Result<FileInfoRequest> decode_file_info_req(const Packet& pkt);
core::Result<FileInfoReply> decode_file_info_reply(const Packet& pkt);
// chat
core::Result<JoinChannel> decode_join_channel(const Packet& pkt);
core::Result<EnterChatRequest> decode_enter_chat_req(const Packet& pkt);
core::Result<EnterChatReply> decode_enter_chat_reply(const Packet& pkt);
core::Result<ChatCommand> decode_chat_command(const Packet& pkt);
core::Result<ChatEvent> decode_chat_event(const Packet& pkt);
core::Result<ChannelListRequest> decode_channel_list_request(const Packet& pkt);
core::Result<ChannelListReply> decode_channel_list_reply(const Packet& pkt);
core::Result<LeaveChannel> decode_leave_channel(const Packet& pkt);
// game
core::Result<GameListRequest> decode_game_list_req(const Packet& pkt);
core::Result<GameListReply> decode_game_list_reply(const Packet& pkt);
core::Result<StartGame4Request> decode_startgame4_request(const Packet& pkt);
core::Result<StartGame4Ack> decode_startgame4_ack(const Packet& pkt);
core::Result<UdpOk> decode_udp_ok(const Packet& pkt);
core::Result<CloseGame> decode_close_game(const Packet& pkt);
core::Result<CloseGame2> decode_close_game2(const Packet& pkt);
core::Result<StartGame1Request> decode_startgame1_request(const Packet& pkt);
core::Result<StartGame1Ack> decode_startgame1_ack(const Packet& pkt);
core::Result<StartGame3Request> decode_startgame3_request(const Packet& pkt);
core::Result<StartGame3Ack> decode_startgame3_ack(const Packet& pkt);
core::Result<JoinGame> decode_join_game(const Packet& pkt);
core::Result<GameReport> decode_game_report(const Packet& pkt);
core::Result<NetGamePort> decode_netgameport(const Packet& pkt);
core::Result<ReadMemoryRequest> decode_read_memory_request(const Packet& pkt);
core::Result<ReadMemoryReply> decode_read_memory_reply(const Packet& pkt);
core::Result<Unknown1B> decode_unknown_1b(const Packet& pkt);
core::Result<Unknown24> decode_unknown_24(const Packet& pkt);
core::Result<MapAuthReq1> decode_mapauthreq1(const Packet& pkt);
core::Result<MapAuthReply1> decode_mapauthreply1(const Packet& pkt);
core::Result<MapAuthReq2> decode_mapauthreq2(const Packet& pkt);
core::Result<MapAuthReply2> decode_mapauthreply2(const Packet& pkt);
core::Result<ChangeClient> decode_change_client(const Packet& pkt);
// friends
core::Result<FriendsListRequest> decode_friendslist_request(const Packet& pkt);
core::Result<FriendsListReply> decode_friendslist_reply(const Packet& pkt);
core::Result<FriendInfoRequest> decode_friendinfo_request(const Packet& pkt);
core::Result<FriendInfoReply> decode_friendinfo_reply(const Packet& pkt);
core::Result<FriendAddAck> decode_friendadd_ack(const Packet& pkt);
core::Result<FriendDelAck> decode_frienddel_ack(const Packet& pkt);
core::Result<FriendMoveAck> decode_friendmove_ack(const Packet& pkt);
core::Result<ArrangedTeamFriendScreenRequest> decode_arrangedteam_friendscreen_request(const Packet& pkt);
core::Result<ArrangedTeamFriendScreenReply> decode_arrangedteam_friendscreen_reply(const Packet& pkt);
core::Result<ArrangedTeamInviteFriendRequest> decode_arrangedteam_invite_friend_request(const Packet& pkt);
core::Result<ArrangedTeamInviteFriendAck> decode_arrangedteam_invite_friend_ack(const Packet& pkt);
core::Result<ArrangedTeamMemberDecline> decode_arrangedteam_member_decline(const Packet& pkt);
core::Result<ArrangedTeamSendInvite> decode_arrangedteam_send_invite(const Packet& pkt);
core::Result<ArrangedTeamAcceptDeclineInvite> decode_arrangedteam_accept_decline_invite(const Packet& pkt);
core::Result<ArrangedTeamAcceptInvite> decode_arrangedteam_accept_invite(const Packet& pkt);
// clan
core::Result<ClanInfoRequest> decode_claninfo_request(const Packet& pkt);
core::Result<ClanInfoReply> decode_claninfo_reply(const Packet& pkt);
core::Result<ClanCreateRequest> decode_clan_create_request(const Packet& pkt);
core::Result<ClanCreateReply> decode_clan_create_reply(const Packet& pkt);
core::Result<ClanDisbandRequest> decode_clan_disband_request(const Packet& pkt);
core::Result<ClanNewChiefRequest> decode_clan_newchief_request(const Packet& pkt);
core::Result<ClanInviteRequest> decode_clan_invite_request(const Packet& pkt);
core::Result<ClanMemberRemoveRequest> decode_clan_member_remove_request(const Packet& pkt);
core::Result<ClanMemberRankUpdateRequest> decode_clan_member_rank_update_request(const Packet& pkt);
core::Result<ClanGenericResultReply> decode_clan_generic_result_reply(const Packet& pkt);
core::Result<ClanMotdChange> decode_clan_motd_change(const Packet& pkt);
core::Result<ClanMotdRequest> decode_clan_motd_request(const Packet& pkt);
core::Result<ClanMotdReply> decode_clan_motd_reply(const Packet& pkt);
core::Result<ClanCreateInviteRequest> decode_clan_create_invite_request(const Packet& pkt);
core::Result<ClanCreateInviteSummary> decode_clan_create_invite_summary(const Packet& pkt);
core::Result<ClanCreateInviteForward> decode_clan_create_invite_forward(const Packet& pkt);
core::Result<ClanCreateInviteResponse> decode_clan_create_invite_response(const Packet& pkt);
core::Result<ClanInvite2Forward> decode_clan_invite2_forward(const Packet& pkt);
core::Result<ClanInvite2Response> decode_clan_invite2_response(const Packet& pkt);
core::Result<ClanMemberListRequest> decode_clan_memberlist_request(const Packet& pkt);
core::Result<ClanMemberListReply> decode_clan_memberlist_reply(const Packet& pkt);
core::Result<ClanMemberRemovedNotify> decode_clan_member_removed_notify(const Packet& pkt);
core::Result<ClanMemberUpdate> decode_clan_member_update(const Packet& pkt);
// ladder / ads / misc
core::Result<LadderSearchRequest> decode_ladder_search_req(const Packet& pkt);
core::Result<LadderSearchReply> decode_ladder_search_reply(const Packet& pkt);
core::Result<LadderListRequest> decode_ladder_list_request(const Packet& pkt);
core::Result<LadderListReply> decode_ladder_list_reply(const Packet& pkt);
core::Result<AdRequest> decode_ad_request(const Packet& pkt);
core::Result<AdReply> decode_ad_reply(const Packet& pkt);
core::Result<AdClick> decode_ad_click(const Packet& pkt);
core::Result<AdAck> decode_ad_ack(const Packet& pkt);
core::Result<AdClick2Request> decode_ad_click2_request(const Packet& pkt);
core::Result<AdClick2Reply> decode_ad_click2_reply(const Packet& pkt);
core::Result<MotdRequest> decode_motd_request(const Packet& pkt);
core::Result<MotdReply> decode_motd_reply(const Packet& pkt);
core::Result<RegSnoopRequest> decode_regsnoop_request(const Packet& pkt);
core::Result<RegSnoopReply> decode_regsnoop_reply(const Packet& pkt);
core::Result<ProfileRequest> decode_profile_request(const Packet& pkt);
core::Result<ProfileReply> decode_profile_reply(const Packet& pkt);
core::Result<SetEmailRequest> decode_setemail_request(const Packet& pkt);
core::Result<SetEmailReply> decode_setemail_reply(const Packet& pkt);
core::Result<IconRequest> decode_icon_request(const Packet& pkt);
core::Result<IconReply> decode_icon_reply(const Packet& pkt);
core::Result<GetPasswordRequest> decode_get_password_request(const Packet& pkt);
core::Result<ChangeEmailRequest> decode_change_email_request(const Packet& pkt);
core::Result<CrashDump> decode_crash_dump(const Packet& pkt);
// realm
core::Result<RealmListRequest> decode_realm_list_request(const Packet& pkt);
core::Result<RealmListReply> decode_realm_list_reply(const Packet& pkt);
core::Result<RealmJoinRequest> decode_realm_join_request(const Packet& pkt);
core::Result<RealmJoinReply> decode_realm_join_reply(const Packet& pkt);
core::Result<CharListRequest> decode_char_list_request(const Packet& pkt);
core::Result<CharListReply> decode_char_list_reply(const Packet& pkt);
core::Result<ServerList> decode_server_list(const Packet& pkt);
core::Result<MessageBox> decode_message_box(const Packet& pkt);
core::Result<RealmListLegacyRequest> decode_realm_list_legacy_request(const Packet& pkt);
core::Result<RealmListLegacyReply> decode_realm_list_legacy_reply(const Packet& pkt);
core::Result<WarcraftGeneralRequest> decode_warcraft_general_request(const Packet& pkt);
core::Result<WarcraftGeneralReply> decode_warcraft_general_reply(const Packet& pkt);
core::Result<RequiredWork> decode_required_work(const Packet& pkt);
core::Result<ExtraWork> decode_extra_work(const Packet& pkt);
// legacy OLS
core::Result<CompInfo1Request> decode_compinfo1_request(const Packet& pkt);
core::Result<CompReply> decode_compreply(const Packet& pkt);
core::Result<ProgIdent> decode_progident(const Packet& pkt);
core::Result<AuthReq1Server> decode_authreq1_server(const Packet& pkt);
core::Result<AuthReq1> decode_authreq1(const Packet& pkt);
core::Result<AuthReply1> decode_authreply1(const Packet& pkt);
core::Result<CountryInfo1> decode_countryinfo1(const Packet& pkt);
core::Result<SessionKey1> decode_sessionkey1(const Packet& pkt);
core::Result<SessionKey2> decode_sessionkey2(const Packet& pkt);
core::Result<CompInfo2> decode_compinfo2(const Packet& pkt);
core::Result<LoginReq1> decode_loginreq1(const Packet& pkt);
core::Result<LoginReply1> decode_loginreply1(const Packet& pkt);
core::Result<CreateAccount1Request> decode_createaccount1_request(const Packet& pkt);
core::Result<CreateAccount1Reply> decode_createaccount1_reply(const Packet& pkt);
core::Result<Unknown2B> decode_unknown_2b(const Packet& pkt);
core::Result<CdKeyLegacyRequest> decode_cdkey_legacy_request(const Packet& pkt);
core::Result<CdKeyLegacyReply> decode_cdkey_legacy_reply(const Packet& pkt);
core::Result<ChangePasswordRequest> decode_changepassword_request(const Packet& pkt);
core::Result<ChangePasswordReply> decode_changepassword_reply(const Packet& pkt);
core::Result<Unknown39> decode_unknown_39(const Packet& pkt);
core::Result<CreateAccountRequest> decode_createaccount_request(const Packet& pkt);
core::Result<CreateAccountReply> decode_createaccount_reply(const Packet& pkt);
// w3
core::Result<CreateAccount2Request> decode_createaccount2_request(const Packet& pkt);
core::Result<CreateAccount2Reply> decode_createaccount2_reply(const Packet& pkt);
core::Result<LoginW3Request> decode_loginw3_request(const Packet& pkt);
core::Result<LoginW3Reply> decode_loginw3_reply(const Packet& pkt);
core::Result<LogonProofW3Request> decode_logonproof_w3_request(const Packet& pkt);
core::Result<LogonProofW3Reply> decode_logonproof_w3_reply(const Packet& pkt);
core::Result<PassChangeRequest> decode_passchange_request(const Packet& pkt);
core::Result<PassChangeReply> decode_passchange_reply(const Packet& pkt);
core::Result<PassChangeProofRequest> decode_passchange_proof_request(const Packet& pkt);
core::Result<PassChangeProofReply> decode_passchange_proof_reply(const Packet& pkt);
core::Result<UserDataReadRequest> decode_userdata_read_request(const Packet& pkt);
core::Result<UserDataReadReply> decode_userdata_read_reply(const Packet& pkt);
core::Result<UserDataWriteRequest> decode_userdata_write_request(const Packet& pkt);

} // namespace detail
} // namespace pvpgn::protocol::bnet
"""

# ─── Function-to-file mapping ─────────────────────────────────────────────────
# Each entry: (filename, [(decode_start, decode_end), ...], [(encode_start, encode_end), ...])
# Ranges are 1-based inclusive from the original file.
# decode functions are in anonymous namespace (lines 11-2144)
# encode functions are in pvpgn::protocol::bnet namespace (lines 2951-4318)
# Ranges verified by running:
#   grep -n "^core::Status<> encode" src/protocol/bnet/src/codec.cpp
# and computing end lines via brace counting.

FILES = [
    ("codec_auth.cpp", {
        "decode": [
            (45, 51),    # decode_ping
            (52, 68),    # decode_auth_info
            (69, 76),    # decode_auth_check_reply
            (77, 103),   # decode_auth_info_reply
            (104, 113),  # decode_logon_response2
            (114, 123),  # decode_logon_response2_reply
            (170, 197),  # decode_auth_check_request
            (295, 308),  # decode_cdkey2_request
            (309, 319),  # decode_cdkey2_reply
            (1129, 1147), # decode_cdkey3_request
            (1148, 1159), # decode_cdkey3_reply
            (272, 280),  # decode_file_info_req
            (281, 294),  # decode_file_info_reply
        ],
        "encode": [
            (2951, 2954),  # encode(Null)
            (2956, 2960),  # encode(Ping)
            (2962, 2976),  # encode(AuthInfo)
            (2978, 2983),  # encode(AuthCheckReply)
            (2985, 3000),  # encode(AuthInfoReply)
            (3002, 3009),  # encode(LogonResponse2)
            (3011, 3019),  # encode(LogonResponse2Reply)
            (3062, 3084),  # encode(AuthCheckRequest)
            (3155, 3166),  # encode(CdKey2Request)
            (3168, 3173),  # encode(CdKey2Reply)
            (3691, 3703),  # encode(CdKey3Request)
            (3705, 3710),  # encode(CdKey3Reply)
            (3138, 3144),  # encode(FileInfoRequest)
            (3146, 3153),  # encode(FileInfoReply)
        ],
    }),
    ("codec_chat.cpp", {
        "decode": [
            (124, 131),  # decode_join_channel
            (132, 139),  # decode_enter_chat_req
            (140, 148),  # decode_enter_chat_reply
            (149, 155),  # decode_chat_command
            (156, 169),  # decode_chat_event
            (754, 761),  # decode_channel_list_request (with constexpr before)
            (762, 763),  # constexpr kChannelListLimit
            (764, 782),  # decode_channel_list_reply
            (783, 793),  # decode_leave_channel
        ],
        "encode": [
            (3021, 3026),  # encode(JoinChannel)
            (3028, 3033),  # encode(EnterChatRequest)
            (3035, 3041),  # encode(EnterChatReply)
            (3043, 3047),  # encode(ChatCommand)
            (3049, 3060),  # encode(ChatEvent)
            (3439, 3443),  # encode(ChannelListRequest)
            (3445, 3463),  # encode(ChannelListReply)
            (3465, 3468),  # encode(LeaveChannel)
        ],
    }),
    ("codec_game.cpp", {
        "decode": [
            (198, 213),  # decode_game_list_req
            (214, 254),  # decode_game_list_reply
            (547, 574),  # decode_startgame4_request
            (575, 583),  # decode_startgame4_ack
            (584, 592),  # decode_udp_ok
            (1950, 1959), # decode_netgameport
            (1960, 1964), # decode_close_game
            (1965, 1971), # decode_close_game2
            (1972, 1985), # decode_startgame1_request
            (1986, 1993), # decode_startgame1_ack
            (1994, 2008), # decode_startgame3_request
            (2009, 2016), # decode_startgame3_ack
            (2017, 2027), # decode_join_game
            (2028, 2057), # decode_game_report
            (2058, 2067), # decode_read_memory_request
            (2068, 2080), # decode_read_memory_reply
            (2081, 2092), # decode_unknown_1b
            (2093, 2099), # decode_unknown_24
            (2100, 2106), # decode_mapauthreq1
            (2107, 2114), # decode_mapauthreply1
            (2115, 2122), # decode_mapauthreq2
            (2123, 2130), # decode_mapauthreply2
            (2131, 2139), # decode_change_client
        ],
        "encode": [
            (3086, 3095),  # encode(GameListRequest)
            (3097, 3121),  # encode(GameListReply)
            (3298, 3311),  # encode(StartGame4Request)
            (3313, 3317),  # encode(StartGame4Ack)
            (3319, 3323),  # encode(UdpOk)
            (4185, 4192),  # encode(NetGamePort)
            (4193, 4196),  # encode(CloseGame)
            (4197, 4200),  # encode(CloseGame2)
            (4201, 4213),  # encode(StartGame1Request)
            (4214, 4218),  # encode(StartGame1Ack)
            (4219, 4232),  # encode(StartGame3Request)
            (4233, 4237),  # encode(StartGame3Ack)
            (4238, 4245),  # encode(JoinGame)
            (4246, 4262),  # encode(GameReport)
            (4263, 4269),  # encode(ReadMemoryRequest)
            (4270, 4275),  # encode(ReadMemoryReply)
            (4276, 4284),  # encode(Unknown1B)
            (4285, 4288),  # encode(Unknown24)
            (4289, 4294),  # encode(MapAuthReq1)
            (4295, 4299),  # encode(MapAuthReply1)
            (4300, 4306),  # encode(MapAuthReq2)
            (4307, 4311),  # encode(MapAuthReply2)
            (4312, 4316),  # encode(ChangeClient)
        ],
    }),
    ("codec_friends.cpp", {
        "decode": [
            (320, 325),  # decode_friendslist_request
            (326, 355),  # decode_friendslist_reply
            (356, 364),  # decode_friendinfo_request
            (365, 383),  # decode_friendinfo_reply
            (384, 398),  # decode_friendadd_ack
            (399, 407),  # decode_frienddel_ack
            (408, 421),  # decode_friendmove_ack
            (422, 423),  # constexpr kArrangedTeamFriendLimit
            (424, 428),  # decode_arrangedteam_friendscreen_request
            (429, 448),  # decode_arrangedteam_friendscreen_reply
            (449, 471),  # decode_arrangedteam_invite_friend_request
            (472, 489),  # decode_arrangedteam_invite_friend_ack
            (490, 499),  # decode_arrangedteam_member_decline
            (500, 528),  # decode_arrangedteam_send_invite
            (529, 539),  # decode_arrangedteam_accept_decline_invite
            (540, 546),  # decode_arrangedteam_accept_invite
        ],
        "encode": [
            (3175, 3178),  # encode(FriendsListRequest)
            (3180, 3191),  # encode(FriendsListReply)
            (3193, 3197),  # encode(FriendInfoRequest)
            (3199, 3207),  # encode(FriendInfoReply)
            (3209, 3217),  # encode(FriendAddAck)
            (3219, 3223),  # encode(FriendDelAck)
            (3225, 3230),  # encode(FriendMoveAck)
            (3232, 3235),  # encode(ArrangedTeamFriendScreenRequest)
            (3237, 3242),  # encode(ArrangedTeamFriendScreenReply)
            (3244, 3252),  # encode(ArrangedTeamInviteFriendRequest)
            (3254, 3262),  # encode(ArrangedTeamInviteFriendAck)
            (3264, 3270),  # encode(ArrangedTeamMemberDecline)
            (3272, 3282),  # encode(ArrangedTeamSendInvite)
            (3284, 3291),  # encode(ArrangedTeamAcceptDeclineInvite)
            (3293, 3296),  # encode(ArrangedTeamAcceptInvite)
        ],
    }),
    ("codec_clan.cpp", {
        "decode": [
            (1317, 1325),  # decode_claninfo_request
            (1326, 1345),  # decode_claninfo_reply
            (1429, 1436),  # decode_clan_create_request
            (1437, 1460),  # decode_clan_create_reply
            (1461, 1467),  # decode_clan_disband_request
            (1468, 1476),  # decode_clan_newchief_request
            (1477, 1484),  # decode_clan_invite_request
            (1485, 1493),  # decode_clan_member_remove_request
            (1494, 1508),  # decode_clan_member_rank_update_request
            (1509, 1520),  # decode_clan_generic_result_reply
            (1521, 1528),  # decode_clan_motd_change
            (1529, 1535),  # decode_clan_motd_request
            (1536, 1546),  # decode_clan_motd_reply
            (1547, 1548),  # constexpr kClanInviteFriendLimit
            (1549, 1565),  # read_friend_list
            (1566, 1577),  # decode_clan_create_invite_request
            (1578, 1590),  # decode_clan_create_invite_summary
            (1591, 1603),  # decode_clan_create_invite_forward
            (1604, 1616),  # decode_clan_create_invite_response
            (1617, 1626),  # decode_clan_invite2_forward
            (1627, 1641),  # decode_clan_invite2_response
            (1642, 1643),  # constexpr kClanMemberListLimit
            (1644, 1651),  # decode_clan_memberlist_request
            (1652, 1683),  # decode_clan_memberlist_reply
            (1684, 1691),  # decode_clan_member_removed_notify
            (1692, 1727),  # decode_clan_member_update
        ],
        "encode": [
            (3787, 3793),  # encode(ClanInfoRequest)
            (3795, 3805),  # encode(ClanInfoReply)
            (3836, 3841),  # encode(ClanCreateRequest)
            (3843, 3850),  # encode(ClanCreateReply)
            (3852, 3856),  # encode(ClanDisbandRequest)
            (3858, 3863),  # encode(ClanNewChiefRequest)
            (3865, 3870),  # encode(ClanInviteRequest)
            (3872, 3877),  # encode(ClanMemberRemoveRequest)
            (3879, 3885),  # encode(ClanMemberRankUpdateRequest)
            (3887, 3895),  # encode(ClanGenericResultReply)
            (3897, 3902),  # encode(ClanMotdChange)
            (3904, 3908),  # encode(ClanMotdRequest)
            (3910, 3916),  # encode(ClanMotdReply)
            (3918, 3926),  # encode(ClanCreateInviteRequest)
            (3928, 3934),  # encode(ClanCreateInviteSummary)
            (3936, 3945),  # encode(ClanCreateInviteForward)
            (3947, 3954),  # encode(ClanCreateInviteResponse)
            (3956, 3963),  # encode(ClanInvite2Forward)
            (3965, 3972),  # encode(ClanInvite2Response)
            (3974, 3978),  # encode(ClanMemberListRequest)
            (3980, 3991),  # encode(ClanMemberListReply)
            (3993, 3997),  # encode(ClanMemberRemovedNotify)
            (3999, 4006),  # encode(ClanMemberUpdate)
        ],
    }),
    ("codec_ladder.cpp", {
        "decode": [
            (255, 264),  # decode_ladder_search_req
            (265, 271),  # decode_ladder_search_reply
            (593, 594),  # constexpr kLadderListLimit
            (595, 605),  # decode_ladder_list_request
            (606, 624),  # read_ladder_block
            (625, 665),  # decode_ladder_list_reply
            (666, 675),  # decode_ad_request
            (676, 690),  # decode_ad_reply
            (691, 700),  # decode_ad_click
            (701, 713),  # decode_ad_ack
            (714, 720),  # decode_ad_click2_request
            (721, 730),  # decode_ad_click2_reply
            (731, 737),  # decode_motd_request
            (738, 753),  # decode_motd_reply
            (794, 803),  # decode_regsnoop_request
            (804, 814),  # decode_regsnoop_reply
            (815, 822),  # decode_profile_request
            (823, 843),  # decode_profile_reply
            (844, 852),  # decode_setemail_request
            (853, 861),  # decode_setemail_reply
            (862, 870),  # decode_icon_request
            (871, 882),  # decode_icon_reply
            (883, 893),  # decode_get_password_request
            (894, 905),  # decode_change_email_request
            (906, 913),  # decode_crash_dump
        ],
        "encode": [
            (3123, 3130),  # encode(LadderSearchRequest)
            (3132, 3136),  # encode(LadderSearchReply)
            (3325, 3333),  # encode(LadderListRequest)
            (3335, 3371),  # encode(LadderListReply)
            (3373, 3380),  # encode(AdRequest)
            (3382, 3390),  # encode(AdReply)
            (3392, 3397),  # encode(AdClick)
            (3399, 3407),  # encode(AdAck)
            (3409, 3413),  # encode(AdClick2Request)
            (3415, 3420),  # encode(AdClick2Reply)
            (3422, 3426),  # encode(MotdRequest)
            (3428, 3437),  # encode(MotdReply)
            (3470, 3477),  # encode(RegSnoopRequest)
            (3479, 3484),  # encode(RegSnoopReply)
            (3486, 3491),  # encode(ProfileRequest)
            (3493, 3503),  # encode(ProfileReply)
            (3505, 3508),  # encode(SetEmailRequest)
            (3510, 3514),  # encode(SetEmailReply)
            (3516, 3519),  # encode(IconRequest)
            (3521, 3526),  # encode(IconReply)
            (3528, 3533),  # encode(GetPasswordRequest)
            (3535, 3541),  # encode(ChangeEmailRequest)
            (3543, 3547),  # encode(CrashDump)
        ],
    }),
    ("codec_realm.cpp", {
        "decode": [
            (914, 922),   # decode_char_list_request
            (923, 935),   # decode_char_list_reply
            (936, 945),   # decode_server_list
            (946, 956),   # decode_message_box
            (957, 958),   # constexpr kRealmListLimit
            (959, 962),   # decode_realm_list_request
            (963, 985),   # decode_realm_list_reply
            (986, 998),   # decode_realm_join_request
            (999, 1034),  # decode_realm_join_reply
            (1035, 1046), # decode_warcraft_general_request
            (1047, 1060), # decode_warcraft_general_reply
            (1061, 1062), # constexpr kExtraWorkMaxLen
            (1063, 1069), # decode_required_work
            (1070, 1089), # decode_extra_work
            (1090, 1098), # decode_realm_list_legacy_request
            (1099, 1128), # decode_realm_list_legacy_reply
        ],
        "encode": [
            (3549, 3554),  # encode(CharListRequest)
            (3556, 3563),  # encode(CharListReply)
            (3565, 3570),  # encode(ServerList)
            (3572, 3578),  # encode(MessageBox)
            (3580, 3583),  # encode(RealmListRequest)
            (3585, 3599),  # encode(RealmListReply)
            (3601, 3607),  # encode(RealmJoinRequest)
            (3609, 3628),  # encode(RealmJoinReply)
            (3630, 3635),  # encode(WarcraftGeneralRequest)
            (3637, 3642),  # encode(WarcraftGeneralReply)
            (3644, 3648),  # encode(RequiredWork)
            (3650, 3660),  # encode(ExtraWork)
            (3662, 3667),  # encode(RealmListLegacyRequest)
            (3669, 3689),  # encode(RealmListLegacyReply)
        ],
    }),
    ("codec_legacy_ols.cpp", {
        "decode": [
            # RD_U64/RD_U16/RD_HASH5 macros defined at 1710-1726 — included via codec_internal.h
            (1728, 1739), # decode_compinfo1_request
            (1740, 1749), # decode_compreply
            (1750, 1759), # decode_progident
            (1760, 1768), # decode_authreq1_server
            (1769, 1780), # decode_authreq1
            (1781, 1799), # decode_authreply1
            (1800, 1819), # decode_countryinfo1
            (1820, 1827), # decode_sessionkey2
            (1828, 1840), # decode_compinfo2
            (1841, 1847), # decode_sessionkey1
            (1848, 1857), # decode_loginreq1
            (1858, 1864), # decode_loginreply1
            (1865, 1872), # decode_createaccount1_request
            (1873, 1879), # decode_createaccount1_reply
            (1880, 1892), # decode_unknown_2b
            (1893, 1901), # decode_cdkey_legacy_request
            (1902, 1909), # decode_cdkey_legacy_reply
            (1910, 1920), # decode_changepassword_request
            (1921, 1927), # decode_changepassword_reply
            (1928, 1934), # decode_unknown_39
            (1935, 1942), # decode_createaccount_request
            (1943, 1949), # decode_createaccount_reply
        ],
        "encode": [
            (4012, 4023),  # encode(CompInfo1Request)
            (4024, 4031),  # encode(CompReply)
            (4032, 4039),  # encode(ProgIdent)
            (4040, 4046),  # encode(AuthReq1Server)
            (4047, 4056),  # encode(AuthReq1)
            (4057, 4068),  # encode(AuthReply1)
            (4069, 4082),  # encode(CountryInfo1)
            (4083, 4087),  # encode(SessionKey1)
            (4088, 4093),  # encode(SessionKey2)
            (4094, 4106),  # encode(CompInfo2)
            (4107, 4114),  # encode(LoginReq1)
            (4115, 4119),  # encode(LoginReply1)
            (4120, 4125),  # encode(CreateAccount1Request)
            (4126, 4130),  # encode(CreateAccount1Reply)
            (4131, 4141),  # encode(Unknown2B)
            (4142, 4148),  # encode(CdKeyLegacyRequest)
            (4149, 4154),  # encode(CdKeyLegacyReply)
            (4155, 4163),  # encode(ChangePasswordRequest)
            (4164, 4168),  # encode(ChangePasswordReply)
            (4169, 4173),  # encode(Unknown39)
            (4174, 4179),  # encode(CreateAccountRequest)
            (4180, 4184),  # encode(CreateAccountReply)
        ],
    }),
    ("codec_w3.cpp", {
        "decode": [
            (1160, 1178), # decode_createaccount2_request
            (1179, 1187), # decode_createaccount2_reply
            (1188, 1200), # decode_loginw3_request
            (1201, 1221), # decode_loginw3_reply
            (1222, 1231), # decode_logonproof_w3_request
            (1232, 1247), # decode_logonproof_w3_reply
            (1248, 1258), # decode_passchange_request
            (1259, 1279), # decode_passchange_reply
            (1280, 1303), # decode_passchange_proof_request
            (1304, 1316), # decode_passchange_proof_reply
            (1346, 1363), # read_strings
            (1364, 1379), # decode_userdata_read_request
            (1380, 1400), # decode_userdata_read_reply
            (1401, 1428), # decode_userdata_write_request
        ],
        "encode": [
            (3712, 3718),  # encode(CreateAccount2Request)
            (3720, 3724),  # encode(CreateAccount2Reply)
            (3726, 3731),  # encode(LoginW3Request)
            (3733, 3739),  # encode(LoginW3Reply)
            (3741, 3745),  # encode(LogonProofW3Request)
            (3747, 3755),  # encode(LogonProofW3Reply)
            (3757, 3762),  # encode(PassChangeRequest)
            (3764, 3770),  # encode(PassChangeReply)
            (3772, 3778),  # encode(PassChangeProofRequest)
            (3780, 3785),  # encode(PassChangeProofReply)
            (3807, 3815),  # encode(UserDataReadRequest)
            (3817, 3824),  # encode(UserDataReadReply)
            (3826, 3834),  # encode(UserDataWriteRequest)
        ],
    }),
]

os.makedirs(OUT_DIR, exist_ok=True)

# Write internal header
with open(os.path.join(OUT_DIR, "codec_internal.h"), "w") as f:
    f.write(INTERNAL_HEADER)
print(f"  Wrote codec_internal.h")

# Write each split file
for filename, spec in FILES:
    decode_ranges = spec.get("decode", [])
    encode_ranges = spec.get("encode", [])

    # Collect decode lines
    decode_parts = []
    for (start, end) in decode_ranges:
        chunk = get_lines(start, end)
        decode_parts.extend(chunk)
        if decode_parts and decode_parts[-1].strip():
            decode_parts.append("\n")

    # Collect encode lines
    encode_parts = []
    for (start, end) in encode_ranges:
        chunk = get_lines(start, end)
        encode_parts.extend(chunk)
        if encode_parts and encode_parts[-1].strip():
            encode_parts.append("\n")

    # Build file content:
    # FILE_HEADER opens: namespace pvpgn::protocol::bnet { namespace detail {
    # decode functions go here
    # DETAIL_CLOSE: } // namespace detail
    # encode functions go here (in pvpgn::protocol::bnet)
    # OUTER_CLOSE: } // namespace pvpgn::protocol::bnet
    content = FILE_HEADER
    content += "".join(decode_parts)
    content += DETAIL_CLOSE
    content += "".join(encode_parts)
    content += OUTER_CLOSE

    out_path = os.path.join(OUT_DIR, filename)
    with open(out_path, "w") as f:
        f.write(content)
    print(f"  Wrote {filename} ({len(decode_parts)} decode lines, {len(encode_parts)} encode lines)")

print("\nDone. Now update codec.cpp to be the dispatcher.")
