# SPDX-License-Identifier: GPL-2.0-or-later
# Application layer — aggregates all bounded-context modules

add_subdirectory(auth)
add_subdirectory(chat)
add_subdirectory(game)
add_subdirectory(moderation)
add_subdirectory(realm)
add_subdirectory(social)
add_subdirectory(ads)
add_subdirectory(admin_commands)
add_subdirectory(anongame_inforeply)
add_subdirectory(anongame_lobby)
add_subdirectory(bnet_packet_pump)
add_subdirectory(email_management)
add_subdirectory(i18n)
add_subdirectory(icon_table)
add_subdirectory(init)
add_subdirectory(profile)
add_subdirectory(tournament)
add_subdirectory(ladder)
