add_subdirectory(common)
if(TARGET protocol_bnet)
    add_subdirectory(bnet)
endif()
if(TARGET protocol_irc)
    add_subdirectory(irc)
endif()
if(TARGET protocol_udp)
    add_subdirectory(udp)
endif()
if(TARGET protocol_telnet)
    add_subdirectory(telnet)
endif()
if(TARGET protocol_file)
    add_subdirectory(file)
endif()
if(TARGET protocol_d2cs)
    add_subdirectory(d2cs)
endif()
if(TARGET protocol_d2gs)
    add_subdirectory(d2gs)
endif()
if(TARGET protocol_d2dbs)
    add_subdirectory(d2dbs)
endif()
if(TARGET protocol_wolgameres)
    add_subdirectory(wolgameres)
endif()
if(TARGET pvpgn_v3_protocol_d2save)
    add_subdirectory(d2save)
endif()
