// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

			// ---------------------------------------------------------------------------
			// IRC command handlers — moved from handle_irc.cpp (Round 134)
			// TODO(Phase3): handled by v3 IrcFsm — legacy IRC command handlers inlined here
			// ---------------------------------------------------------------------------
	
			int _handle_user_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				char * user = NULL;
				char * realname = NULL;
	
				if ((numparams >= 3) && (params[0]) && (text)) {
					user = params[0];
					realname = text;
	
					if (conn_get_user(conn)) {
						irc_send(conn, ERR_ALREADYREGISTRED, ":You are already registred");
					}
					else {
						eventlog(eventlog_level_debug, __FUNCTION__, "[{}] got USER: user=\"{}\" realname=\"{}\"", conn_get_socket(conn), user, realname);
						conn_set_user(conn, user);
						conn_set_owner(conn, realname);
						if (conn_get_loggeduser(conn))
							irc_welcome(conn); /* only send the welcome if we have USER and NICK */
					}
				}
				else {
					irc_send(conn, ERR_NEEDMOREPARAMS, "USER :Not enough parameters");
				}
				return 0;
			}
	
			int _handle_pass_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				if ((!conn_get_ircpass(conn)) && (conn_get_state(conn) == conn_state_bot_username)) {
					t_hash h;
	
					if (numparams >= 1) {
						bnet_hash(&h, std::strlen(params[0]), params[0]);
						conn_set_ircpass(conn, hash_get_str(h));
					}
					else
						irc_send(conn, ERR_NEEDMOREPARAMS, "PASS :Not enough parameters");
				}
				else {
					irc_send(conn, ERR_ALREADYREGISTRED, ":Unauthorized command (already registered)");
				}
				return 0;
			}
	
			int _handle_privmsg_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				if ((numparams >= 1) && (text))
				{
					int i;
					char ** e;
	
					e = irc_get_listelems(params[0]);
	
					for (i = 0; ((e) && (e[i])); i++) {
						if (strcasecmp(e[i], "NICKSERV") == 0) {
							char * pass;
	
							pass = std::strchr(text, ' ');
							if (pass)
								*pass++ = '\0';
	
							if (strcasecmp(text, "identify") == 0) {
								switch (conn_get_state(conn)) {
								case conn_state_bot_password:
								{
									if (pass) {
										t_hash h;
	
										strtolower(pass);
										bnet_hash(&h, std::strlen(pass), pass);
										irc_authenticate(conn, hash_get_str(h));
									}
									else {
										message_send_text(conn, message_type_notice, NULL, "Syntax: IDENTIFY <password> (max 16 characters)");
									}
									break;
								}
								case conn_state_loggedin:
								{
									message_send_text(conn, message_type_notice, NULL, "You don't need to IDENTIFY");
									break;
								}
								default:;
									eventlog(eventlog_level_trace, __FUNCTION__, "got /msg in unexpected connection state ({})", conn_state_get_str(conn_get_state(conn)));
								}
							}
							else if (strcasecmp(text, "register") == 0) {
								t_hash       passhash;
								t_account  * temp;
								char       * username = (char *)conn_get_loggeduser(conn);
	
								if (account_check_name(username)<0) {
									message_send_text(conn, message_type_error, conn, "Account name contains invalid symbol!");
									break;
								}
	
								if (!prefs_v3::allow_new_accounts()){
									message_send_text(conn, message_type_error, conn, "Account creation is not allowed");
									break;
								}
	
								if (!pass || pass[0] == '\0' || (std::strlen(pass)>16)) {
									message_send_text(conn, message_type_error, conn, "Syntax: REGISTER <password> (max 16 characters)");
									break;
								}
	
								strtolower(pass);
	
								bnet_hash(&passhash, std::strlen(pass), pass);
	
								message_send_text(conn, message_type_info, conn, std::string("Trying to create account \"" + std::string(username) + "\" with password \"" + std::string(pass) + "\"").c_str());
	
								temp = accountlist_create_account(username, hash_get_str(passhash));
								if (!temp) {
									message_send_text(conn, message_type_error, conn, "Failed to create account!");
									eventlog(eventlog_level_debug, __FUNCTION__, "[{}] account \"{}\" not created (failed)", conn_get_socket(conn), username);
									conn_unget_chatname(conn, username);
									break;
								}
	
								message_send_text(conn, message_type_info, conn, std::string("Account #" + std::to_string(account_get_uid(temp)) + " created."));
								eventlog(eventlog_level_debug, __FUNCTION__, "[{}] account \"{}\" created", conn_get_socket(conn), username);
								conn_unget_chatname(conn, username);
							}
							else {
								message_send_text(conn, message_type_notice, nullptr, "Invalid arguments for NICKSERV");
								message_send_text(conn, message_type_notice, nullptr, std::string(":Unrecognized command \"" + std::string(text) + "\"").c_str());
							}
						}
						else if (conn_get_state(conn) == conn_state_loggedin) {
							if (e[i][0] == '#') {
								t_channel * channel;
	
								if ((channel = channellist_find_channel_by_name(irc_convert_ircname(e[i]), NULL, NULL))) {
									if ((std::strlen(text) >= 9) && (std::strncmp(text, "\001ACTION ", 8) == 0) && (text[std::strlen(text) - 1] == '\001')) {
										text = text + 8;
										text[std::strlen(text) - 1] = '\0';
										channel_message_send(channel, message_type_emote, conn, text);
									}
									else {
										channel_message_log(channel, conn, 1, text);
										channel_message_send(channel, message_type_talk, conn, text);
									}
								}
								else {
									irc_send(conn, ERR_NOSUCHCHANNEL, ":No such channel");
								}
							}
							else {
								t_connection * user;
	
								if ((user = connlist_find_connection_by_accountname(e[i])))
								{
									message_send_text(user, message_type_whisper, conn, text);
								}
								else
								{
									irc_send(conn, ERR_NOSUCHNICK, ":No such user");
								}
							}
						}
					}
					if (e)
						irc_unget_listelems(e);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "PRIVMSG :Not enough parameters");
				return 0;
			}
	
			int _handle_notice_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				if ((numparams >= 1) && (text)) {
					int i;
					char ** e;
	
					e = irc_get_listelems(params[0]);
	
					for (i = 0; ((e) && (e[i])); i++) {
						if (conn_get_state(conn) == conn_state_loggedin) {
							t_connection * user;
	
							if ((user = connlist_find_connection_by_accountname(e[i]))) {
								message_send_text(user, message_type_notice, conn, text);
							}
							else {
								irc_send(conn, ERR_NOSUCHNICK, ":No such user");
							}
						}
					}
					if (e)
						irc_unget_listelems(e);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "NOTICE :Not enough parameters");
				return 0;
			}
	
			int _handle_quit_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				conn_quit_channel(conn, text);
				conn_set_state(conn, conn_state_destroy);
				return 0;
			}
	
			int _handle_who_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				if (numparams >= 1) {
					int i;
					char ** e;
	
					e = irc_get_listelems(params[0]);
					for (i = 0; ((e) && (e[i])); i++) {
						irc_who(conn, e[i]);
					}
					irc_send(conn, RPL_ENDOFWHO, ":End of WHO list");
					if (e)
						irc_unget_listelems(e);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "WHO :Not enough parameters");
				return 0;
			}
	
			int _handle_list_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				std::string tmp;
				irc_send(conn, RPL_LISTSTART, "Channel :Users Names");
	
				if (numparams == 0)
				{
					class_topic Topic;
					for (t_channel const* channel : channellist())
					{
						char const * tempname = irc_convert_channel(channel, conn);
						std::string topicstr = Topic.get(channel_get_name(channel));
	
						tmp = std::string(tempname) + " " + std::to_string(channel_get_length(channel)) + " :" + topicstr;
	
						if (tmp.length() > MAX_IRC_MESSAGE_LEN)
							eventlog(eventlog_level_warn, __FUNCTION__, "LISTREPLY length exceeded");
	
						irc_send(conn, RPL_LIST, tmp.c_str());
					}
				}
				else if (numparams >= 1)
				{
					int i;
					char ** e;
					class_topic Topic;
	
					e = irc_get_listelems(params[0]);
	
					for (i = 0; ((e) && (e[i])); i++)
					{
						char const * verytemp = irc_convert_ircname(e[i]);
						if (!verytemp)
							continue;
	
						t_channel const * channel = channellist_find_channel_by_name(verytemp, NULL, NULL);
						if (!channel)
							continue;
	
						std::string topicstr = Topic.get(channel_get_name(channel));
						char const * tempname = irc_convert_channel(channel, conn);
	
						tmp = std::string(tempname) + " " + std::to_string(channel_get_length(channel)) + " :" + topicstr;
	
						if (tmp.length() > MAX_IRC_MESSAGE_LEN)
							eventlog(eventlog_level_warn, __FUNCTION__, "LISTREPLY length exceeded");
	
						irc_send(conn, RPL_LIST, tmp.c_str());
					}
	
					if (e)
						irc_unget_listelems(e);
				}
	
				irc_send(conn, RPL_LISTEND, ":End of LIST command");
	
				return 0;
			}
	
			int _handle_names_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				t_channel * channel;
	
				if (numparams >= 1) {
					char ** e;
					char const * verytemp;
					int i;
	
					e = irc_get_listelems(params[0]);
					for (i = 0; ((e) && (e[i])); i++) {
						verytemp = irc_convert_ircname(e[i]);
	
						if (!verytemp)
							continue;
						channel = channellist_find_channel_by_name(verytemp, NULL, NULL);
						if (!channel)
							continue;
						irc_send_rpl_namreply(conn, channel);
					}
					if (e)
						irc_unget_listelems(e);
				}
				else if (numparams == 0) {
					irc_send_rpl_namreply(conn, NULL);
				}
				return 0;
			}
	
			int _handle_userhost_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				/* FIXME: Send RPL_USERHOST */
				return 0;
			}
	
			int _handle_ison_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				char temp[MAX_IRC_MESSAGE_LEN];
				char first = 1;
	
				if (numparams >= 1)
				{
					int i;
	
					temp[0] = '\0';
					for (i = 0; (i < numparams && (params) && (params[i])); i++)
					{
						if (connlist_find_connection_by_accountname(params[i]))
						{
							std::snprintf(temp, sizeof temp, "%s%s", first ? ":" : " ", params[i]);
							first = 0;
						}
					}
					irc_send(conn, RPL_ISON, temp);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "ISON :Not enough parameters");
				return 0;
			}
	
			int _handle_whois_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				std::string tmp;
	
				if (numparams >= 1)
				{
					int i;
					char ** e = irc_get_listelems(params[0]);
					t_connection * c;
					t_channel * chan;
	
					for (i = 0; ((e) && (e[i])); i++)
					{
						if ((c = connlist_find_connection_by_accountname(e[i])))
						{
							if (prefs_v3::hide_addr() && !(account_get_command_groups(conn_get_account(conn)) & command_get_group("/admin-addr")))
								tmp = std::string(e[i]) + " " + std::string(clienttag_uint_to_str(conn_get_clienttag(c))) + " hidden * :PvPGN user";
							else
								tmp = std::string(e[i]) + " " + std::string(clienttag_uint_to_str(conn_get_clienttag(c))) + " " + std::string(addr_num_to_ip_str(conn_get_addr(c))) + " * :PvPGN user";
							irc_send(conn, RPL_WHOISUSER, tmp.c_str());
	
							if ((chan = conn_get_channel(conn)))
							{
								std::string flg;
								auto flags = conn_get_flags(c);
	
								if (flags & MF_BLIZZARD)
									flg = '@';
								else if ((flags & MF_BNET) || (flags & MF_GAVEL))
									flg = '%';
								else if (flags & MF_VOICE)
									flg = '+';
								else
									flg = ' ';
	
								tmp = std::string(e[i]) + " :" + flg + std::string(irc_convert_channel(chan, conn));
								irc_send(conn, RPL_WHOISCHANNELS, tmp.c_str());
							}
	
						}
						else
							irc_send(conn, ERR_NOSUCHNICK, ":No such nick/channel");
	
					}
					irc_send(conn, RPL_ENDOFWHOIS, ":End of /WHOIS list");
					if (e)
						irc_unget_listelems(e);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "WHOIS :Not enough parameters");
				return 0;
			}
	
			int _handle_part_command(t_connection * conn, int numparams, char ** params, char * text)
			{
				conn_part_channel(conn);
				return 0;
			}

	}

}
