// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		static char* irc_strdup(char const* s)
		{
			if (!s) return nullptr;
			std::size_t n = std::strlen(s) + 1;
			char* r = new char[n];
			std::memcpy(r, s, n);
			return r;
		}
		static char ** irc_split_elems(char * list, int separator, int ignoreblank);
		static int irc_unget_elems(char ** elems);
		static char * irc_message_preformat(t_irc_message_from const * from, char const * command, char const * dest, char const * text);

		extern int irc_send_cmd(t_connection * conn, char const * command, char const * params)
		{
			t_packet * p;
			char data[MAX_IRC_MESSAGE_LEN + 1];
			char const * ircname = server_get_hostname();
			char const * nick;

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}
			if (!command) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL command");
				return -1;
			}
			nick = conn_get_loggeduser(conn);
			if (!nick)
				nick = "UserName";

			if (params)
					std::snprintf(data, sizeof(data), ":%s %s %s %s", ircname, command, nick, params);
			else
					std::snprintf(data, sizeof(data), ":%s %s %s", ircname, command, nick);

			DEBUG2("[{}] sent \"{}\"", conn_get_socket(conn), data);
			std::strcat(data, "\r\n");

			{
				int const _rc = pvpgn_v3_send_raw_text(conn, data);
				if (_rc == 1) goto irc_send_cmd_skip_legacy;
				if (_rc == -1) return -1;
			}
			if (!(p = packet_create(packet_class_raw))) {
				eventlog(eventlog_level_error, __FUNCTION__, "could not create packet");
				return -1;
			}
			packet_set_size(p, 0);
			packet_append_data(p, data, std::strlen(data));
			conn_push_outqueue(conn, p);
			packet_del_ref(p);
			irc_send_cmd_skip_legacy:;
			return 0;
		}

		extern int irc_send(t_connection * conn, int code, char const * params)
		{
			char temp[4]; /* '000\0' */

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}
			if ((code > 999) || (code < 0)) { /* more than 3 digits or negative */
				eventlog(eventlog_level_error, __FUNCTION__, "invalid message code ({})", code);
				return -1;
			}
			std::sprintf(temp, "%03u", code);
			return irc_send_cmd(conn, temp, params);
		}

		extern int irc_send_ping(t_connection * conn)
		{
			t_packet * p;
			char data[MAX_IRC_MESSAGE_LEN];

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}

			if ((conn_get_class(conn) == conn_class_wserv) ||
				(conn_get_class(conn) == conn_class_wgameres) ||
				(conn_get_class(conn) == conn_class_wladder))
				return 0;

			conn_set_ircping(conn, get_ticks());
			if (conn_get_state(conn) == conn_state_bot_username)
				std::sprintf(data, "PING :%u", conn_get_ircping(conn)); /* Undernet doesn't reveal the servername yet ... neither do we */
			else if ((6 + std::strlen(server_get_hostname()) + 2 + 1) <= MAX_IRC_MESSAGE_LEN)
				std::sprintf(data, "PING :%s", server_get_hostname());
			else
				eventlog(eventlog_level_error, __FUNCTION__, "maximum message length exceeded");
			eventlog(eventlog_level_debug, __FUNCTION__, "[{}] sent \"{}\"", conn_get_socket(conn), data);
			std::strcat(data, "\r\n");

			{
				int const _rc = pvpgn_v3_send_raw_text(conn, data);
				if (_rc == 1) goto irc_send_ping_skip_legacy;
				if (_rc == -1) return -1;
			}
			if (!(p = packet_create(packet_class_raw))) {
				eventlog(eventlog_level_error, __FUNCTION__, "could not create packet");
				return -1;
			}
			packet_set_size(p, 0);
			packet_append_data(p, data, std::strlen(data));
			conn_push_outqueue(conn, p);
			packet_del_ref(p);
			irc_send_ping_skip_legacy:;
			return 0;
		}

		extern int irc_send_pong(t_connection * conn, char const * params)
		{
			t_packet * p;
			char data[MAX_IRC_MESSAGE_LEN];

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}
			if ((1 + std::strlen(server_get_hostname()) + 1 + 4 + 1 + std::strlen(server_get_hostname()) + ((params) ? (2 + std::strlen(params)) : (0)) + 2 + 1) > MAX_IRC_MESSAGE_LEN) {
				eventlog(eventlog_level_error, __FUNCTION__, "max message length exceeded");
				return -1;
			}
			if (params)
				std::sprintf(data, ":%s PONG %s :%s", server_get_hostname(), server_get_hostname(), params);
			else
				std::sprintf(data, ":%s PONG %s", server_get_hostname(), server_get_hostname());
			eventlog(eventlog_level_debug, __FUNCTION__, "[{}] sent \"{}\"", conn_get_socket(conn), data);
			std::strcat(data, "\r\n");

			{
				int const _rc = pvpgn_v3_send_raw_text(conn, data);
				if (_rc == 1) goto irc_send_pong_skip_legacy;
				if (_rc == -1) return -1;
			}
			if (!(p = packet_create(packet_class_raw))) {
				eventlog(eventlog_level_error, __FUNCTION__, "could not create packet");
				return -1;
			}
			packet_set_size(p, 0);
			packet_append_data(p, data, std::strlen(data));
			conn_push_outqueue(conn, p);
			packet_del_ref(p);
			irc_send_pong_skip_legacy:;
			return 0;
		}

		extern int irc_authenticate(t_connection * conn, char const * passhash)
		{
			/* FIXME: Move this function to handle_irc.* file! */
			char temp[MAX_IRC_MESSAGE_LEN];
			t_hash h1;
			t_hash h2;
			t_account * a;
			char const * temphash;
			char const * username;

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return 0;
			}
			if (!passhash) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL passhash");
				return 0;
			}
			username = conn_get_loggeduser(conn);
			if (!username) {
				/* redundant sanity check */
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL conn->protocol.loggeduser");
				return 0;
			}
			a = accountlist_find_account(username);
			if (!a) {
				message_send_text(conn, message_type_notice, NULL, "Authentication failed.");
				return 0;
			}

			if (connlist_find_connection_by_account(a) && prefs_v3::kick_old_login() == 0) {
				std::snprintf(temp, sizeof(temp), "%s :Account is already in use!", conn_get_loggeduser(conn));
				irc_send(conn, ERR_NICKNAMEINUSE, temp);
			}
			else if (account_get_auth_lock(a) == 1) {
				message_send_text(conn, message_type_notice, NULL, "Authentication rejected (account is locked) ");
			}
			else
			{
				hash_set_str(&h1, passhash);
				temphash = account_get_pass(a);
				hash_set_str(&h2, temphash);
				if (hash_eq(h1, h2)) {
					conn_login(conn, a, username);
					conn_set_state(conn, conn_state_loggedin);
					conn_set_clienttag(conn, CLIENTTAG_IIRC_UINT); /* IIRC hope here is ok */
					message_send_text(conn, message_type_notice, NULL, "Authentication successful. You are now logged in.");
					return 1;
				}
				else {
					message_send_text(conn, message_type_notice, NULL, "Authentication failed."); /* wrong password */
					conn_increment_passfail_count(conn);
				}
			}
			return 0;
		}

		/* Channel name conversion rules: */
		/* Not allowed in IRC (RFC2812): NUL, BELL, CR, LF, ' ', ':' and ','*/
		/*   ' '  -> '_'      */
		/*   '_'  -> '%_'     */
		/*   '%'  -> '%%'     */
		/*   '\b' -> '%b'     */
		/*   '\n' -> '%n'     */
		/*   '\r' -> '%r'     */
		/*   ':'  -> '%='     */
		/*   ','  -> '%-'     */
		/* In IRC a channel can be specified by '#'+channelname or '!'+channelid */
		extern char const * irc_convert_channel(t_channel const * channel, t_connection * c)
		{
			char const * bname;
			static char out[MAX_CHANNELNAME_LEN];
			unsigned int outpos;
			int i;

			if (!channel)
				return "*";

			std::memset(out, 0, sizeof(out));
			out[0] = '#';
			outpos = 1;

			if ((conn_get_wol(c) == 1) && (channel_get_clienttag(channel) != 0 && (conn_get_clienttag(c) == channel_get_clienttag(channel))))
				bname = channel_get_shortname(channel); /* We converting unreadable "lob 18 0" names to human redable ones */
			else
				bname = channel_get_name(channel);

			for (i = 0; bname[i] != '\0'; i++) {
				if (bname[i] == ' ') {
					out[outpos++] = '_';
				}
				else if (bname[i] == '_') {
					out[outpos++] = '%';
					out[outpos++] = '_';
				}
				else if (bname[i] == '%') {
					out[outpos++] = '%';
					out[outpos++] = '%';
				}
				else if (bname[i] == '\b') {
					out[outpos++] = '%';
					out[outpos++] = 'b';
				}
				else if (bname[i] == '\n') {
					out[outpos++] = '%';
					out[outpos++] = 'n';
				}
				else if (bname[i] == '\r') {
					out[outpos++] = '%';
					out[outpos++] = 'r';
				}
				else if (bname[i] == ':') {
					out[outpos++] = '%';
					out[outpos++] = '=';
				}
				else if (bname[i] == ',') {
					out[outpos++] = '%';
					out[outpos++] = '-';
				}
				else {
					out[outpos++] = bname[i];
				}
				if ((outpos + 2) >= (sizeof(out))) {
					std::sprintf(out, "!%u", channel_get_channelid(channel));
					return out;
				}
			}
			return out;
		}

		extern char const * irc_convert_ircname(char const * pircname)
		{
			static char out[MAX_CHANNELNAME_LEN];
			unsigned int outpos;
			int special;
			int i;
			char const * ircname = pircname + 1;

			if (!ircname) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL ircname");
				return NULL;
			}

			outpos = 0;
			std::memset(out, 0, sizeof(out));
			special = 0;
			if (pircname[0] == '!') {
				t_channel * channel;

				channel = channellist_find_channel_bychannelid(std::atoi(ircname));
				if (channel)
					return channel_get_name(channel);
				else
					return NULL;
			}
			else if (pircname[0] != '#') {
				return NULL;
			}
			for (i = 0; ircname[i] != '\0'; i++) {
				if (ircname[i] == '_') {
					out[outpos++] = ' ';
				}
				else if (ircname[i] == '%') {
					if (special) {
						out[outpos++] = '%';
						special = 0;
					}
					else {
						special = 1;
					}
				}
				else if (special) {
					if (ircname[i] == '_') {
						out[outpos++] = '_';
					}
					else if (ircname[i] == 'b') {
						out[outpos++] = '\b';
					}
					else if (ircname[i] == 'n') {
						out[outpos++] = '\n';
					}
					else if (ircname[i] == 'r') {
						out[outpos++] = '\r';
					}
					else if (ircname[i] == '=') {
						out[outpos++] = ':';
					}
					else if (ircname[i] == '-') {
						out[outpos++] = ',';
					}
					else {
						/* maybe it's just a typo :) */
						out[outpos++] = '%';
						out[outpos++] = ircname[i];
					}
				}
				else {
					out[outpos++] = ircname[i];
				}
				if ((outpos + 2) >= (sizeof(out))) {
					return NULL;
				}
			}
			return out;
		}

		/* splits an string list into its elements */
		/* (list will be modified) */
		static char ** irc_split_elems(char * list, int separator, int ignoreblank)
		{
			int i;
			int count;
			char ** out;

			if (!list) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL list");
				return NULL;
			}

			for (count = 0, i = 0; list[i] != '\0'; i++) {
				if (list[i] == separator) {
					count++;
					if (ignoreblank) {
						/* ignore more than one separators "in a row" */
						while ((list[i + 1] != '\0') && (list[i] == separator)) i++;
					}
				}
			}
			count++; /* count separators -> we have one more element ... */
			/* we also need a terminating element */
			out = new char*[count + 1]{};

			out[0] = list;
			if (count > 1) {
				for (i = 1; i < count; i++) {
					out[i] = std::strchr(out[i - 1], separator);
					if (!out[i]) {
						eventlog(eventlog_level_error, __FUNCTION__, "BUG: wrong number of separators");
						delete[] out;
						return NULL;
					}
					if (ignoreblank)
					while ((*out[i] + 1) == separator) out[i]++;
					*out[i]++ = '\0';
				}
				if ((ignoreblank) && (out[count - 1]) && (*out[count - 1] == '\0')) {
					out[count - 1] = NULL; /* last element is blank */
				}
			}
			else if ((ignoreblank) && (*out[0] == '\0')) {
				out[0] = NULL; /* now we have 2 terminators ... never mind */
			}
			out[count] = NULL; /* terminating element */
			return out;
		}

		static int irc_unget_elems(char ** elems)
		{
			if (!elems) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL elems");
				return -1;
			}
			delete[] elems;
			return 0;
		}

		extern char ** irc_get_listelems(char * list)
		{
			return irc_split_elems(list, ',', 0);
		}

		extern int irc_unget_listelems(char ** elems)
		{
			return irc_unget_elems(elems);
		}

		extern char ** irc_get_paramelems(char * list)
		{
			return irc_split_elems(list, ' ', 1);
		}

		extern int irc_unget_paramelems(char ** elems)
		{
			return irc_unget_elems(elems);
		}

		extern char ** irc_get_ladderelems(char * list)
		{
			return irc_split_elems(list, ':', 1);
		}

		extern int irc_unget_ladderelems(char ** elems)
		{
			return irc_unget_elems(elems);
		}

	}

}
