// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		extern int _handle_nick_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			/* FIXME: more strict param checking */

			if ((conn_get_loggeduser(conn)) &&
				(conn_get_state(conn) != conn_state_bot_password &&
				conn_get_state(conn) != conn_state_bot_username)) {
				irc_send(conn, ERR_RESTRICTED, ":You can't change your nick after login");
			}
			else {
				if ((params) && (params[0])) {
					if (conn_get_loggeduser(conn)){
						std::snprintf(temp, sizeof(temp), ":%s", params[0]);
						message_send_text(conn, message_type_nick, conn, temp);
					}
					conn_set_loggeduser(conn, params[0]);
				}
				else if (text) {
					if (conn_get_loggeduser(conn)){
						std::snprintf(temp, sizeof(temp), ":%s", text);
						message_send_text(conn, message_type_nick, conn, temp);
					}
					conn_set_loggeduser(conn, text);
				}
				else
					irc_send(conn, ERR_NEEDMOREPARAMS, "NICK :Not enough parameters");

				if ((conn_get_user(conn)) && (conn_get_loggeduser(conn)))
					irc_welcome(conn); /* only send the welcome if we have USER and NICK */
			}
			return 0;
		}

		extern int _handle_ping_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/* Dizzy: just ignore this because RFC says we should not reply client PINGs
			 * NOTE: RFC2812 doesn't seem to be very expressive about this ... */
			if (numparams)
				irc_send_pong(conn, params[0]);
			else
				irc_send_pong(conn, text);
			return 0;
		}

		extern int _handle_pong_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			/* NOTE: RFC2812 doesn't seem to be very expressive about this ... */
			if (conn_get_ircping(conn) == 0) {
				eventlog(eventlog_level_warn, __FUNCTION__, "[{}] PONG without PING", conn_get_socket(conn));
			}
			else {
				unsigned int val = 0;
				char * sname;

				if (numparams >= 1) {
					val = std::strtoul(params[0], NULL, 10);
					sname = params[0];
				}
				else if (text) {
					val = std::strtoul(text, NULL, 10);
					sname = text;
				}
				else {
					val = 0;
					sname = 0;
				}

				if (conn_get_ircping(conn) != val) {
					if ((!(sname)) || (std::strcmp(sname, server_get_hostname()) != 0)) {
						/* Actually the servername should not be always accepted but we aren't that pedantic :) */
						eventlog(eventlog_level_warn, __FUNCTION__, "[{}] got bad PONG ({}!={} && {}!={})", conn_get_socket(conn), val, conn_get_ircping(conn), sname, server_get_hostname());
						return -1;
					}
				}
				conn_set_latency(conn, get_ticks() - conn_get_ircping(conn));
				eventlog(eventlog_level_debug, __FUNCTION__, "[{}] latency is now {} ({}-{})", conn_get_socket(conn), get_ticks() - conn_get_ircping(conn), get_ticks(), conn_get_ircping(conn));
				conn_set_ircping(conn, 0);
			}
			return 0;
		}

		extern int _handle_join_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			if (numparams >= 1) {
				char ** e;

				/* According to RFC2812 - if channelname is "0" we need to PART all channels */
				if (std::strcmp(params[0], "0") == 0) {
					conn_part_channel(conn);
					return 0;
				}

				e = irc_get_listelems(params[0]);
				if ((e) && (e[0])) {
					char temp[MAX_IRC_MESSAGE_LEN];
					char const * ircname = irc_convert_ircname(e[0]);
					t_channel * old_channel = conn_get_channel(conn);
					t_channel * channel;
					t_account * acc = conn_get_account(conn);

					if ((ircname) && (channel = channellist_find_channel_by_name(ircname, NULL, NULL))) {
						if (channel_check_banning(channel, conn)) {
							std::snprintf(temp, sizeof(temp), "%s :You are banned from that channel.", e[0]);
							irc_send(conn, ERR_BANNEDFROMCHAN, temp);
							if (e)
								irc_unget_listelems(e);
							return 0;
						}

						if ((account_get_auth_admin(acc, NULL) != 1) && (account_get_auth_admin(acc, ircname) != 1) &&
							(account_get_auth_operator(acc, NULL) != 1) && (account_get_auth_operator(acc, ircname) != 1) &&
							(channel_get_max(channel) != -1) && (channel_get_curr(channel) >= channel_get_max(channel))) {

							std::snprintf(temp, sizeof(temp), "%s :The channel is currently full.", e[0]);
							irc_send(conn, ERR_CHANNELISFULL, temp);
							if (e)
								irc_unget_listelems(e);
							return 0;
						}
					}

					if ((!(ircname)) || (conn_set_channel(conn, ircname) < 0)) {
						std::snprintf(temp, sizeof(temp), "%s :JOIN failed", e[0]);
						irc_send(conn, ERR_NOSUCHCHANNEL, temp); /* Anything is still bad */
					}
				}
				if (e)
					irc_unget_listelems(e);
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "JOIN :Not enough parameters");
			return 0;
		}

		extern int irc_send_topic(t_connection * c, t_channel const * channel)
		{
			class_topic Topic;
			std::string topicstr = Topic.get(channel_get_name(channel));
			char temp[MAX_IRC_MESSAGE_LEN];

			if (topicstr.empty() == false) {
				std::snprintf(temp, sizeof(temp), "%s :%s", irc_convert_channel(channel, c), topicstr.c_str());
				irc_send(c, RPL_TOPIC, temp);
			}
			else {
				std::snprintf(temp, sizeof(temp), "%s :", irc_convert_channel(channel, c));
				irc_send(c, RPL_TOPIC, temp);
				/* PELISH: This is according to RFC2812 but brakes WOLv1/WOLv2 */
				//snprintf(temp, sizeof(temp), "%s :No topic is set", irc_convert_channel(channel,c));
				//irc_send(c, RPL_NOTOPIC, temp);
			}
			return 0;
		}

		extern int _handle_topic_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char ** e = NULL;
			char temp[MAX_IRC_MESSAGE_LEN];
			class_topic Topic;

			if (params && params[0])
			{
				if (conn_get_wol(conn) == 1) {
					t_channel * channel = conn_get_channel(conn);
					if (channel)
						Topic.set(std::string(channel_get_name(channel)), std::string(text), false);
					else {
						std::snprintf(temp, sizeof(temp), "%s :You're not on that channel", params[0]);
						irc_send(conn, ERR_NOTONCHANNEL, temp);
					}
				}
				e = irc_get_listelems(params[0]);
			}
			if ((e) && (e[0])) 
			{
				t_channel *channel = conn_get_channel(conn);

				if (channel) {
					char const * ircname = irc_convert_ircname(e[0]);

					if ((ircname) && (strcasecmp(channel_get_name(channel), ircname) == 0)) {
						irc_send_topic(conn, channel);
					}
					else {
						std::snprintf(temp, sizeof(temp), "%s :You're not on that channel", e[0]);
						irc_send(conn, ERR_NOTONCHANNEL, temp);
					}
				}
				else {
					std::snprintf(temp, sizeof(temp), "%s :You're not on that channel", e[0]);
					irc_send(conn, ERR_NOTONCHANNEL, temp);
				}
			}
			else
				irc_send(conn, ERR_NEEDMOREPARAMS, "TOPIC :Not enough parameters");

			if (e)
			{
				irc_unget_listelems(e);
			}

			return 0;
		}

		extern int _handle_kick_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char ** e;
			/**
			*  Heres the imput expected
			*  KICK [channel] [kicked_user],[kicked_user2]
			*
			*  Heres the output expected
			*  :user!WWOL@hostname KICK [channel] [kicked_user] :[text]
			*
			*  WOL in [text] sends Admin name
			*/

			if ((numparams != 2) || !(params[1])) {
				irc_send(conn, ERR_NEEDMOREPARAMS, "KICK :Not enough parameters");
				return 0;
			}

			if (e = irc_get_listelems(params[1]))
			{
				/* Make standart PvPGN KICK from RFC2812 KICK */
				if (text)
					std::snprintf(temp, sizeof(temp), "/kick %s %s", e[0], text);
				else
					std::snprintf(temp, sizeof(temp), "/kick %s", e[0]);

				handle_command(conn, temp);

				irc_unget_listelems(e);
			}
			return 0;
		}

		static int irc_send_banlist(t_connection * conn, t_channel * channel)
		{
			char const * ircname = server_get_hostname();
			char temp[MAX_IRC_MESSAGE_LEN];

			if (!conn) {
				ERROR0("got NULL conn");
				return -1;
			}

			if (!channel) {
				ERROR0("got NULL channel");
				return -1;
			}

			for (const auto& banned : channel_get_banlist(channel)) {
				//FIXME: right now we lie about who have gives ban and also about bantime
				std::snprintf(temp, sizeof(temp), "%s %s!*@* %s 1208297879", irc_convert_channel(channel, conn), banned.c_str(), ircname);
				irc_send(conn, RPL_BANLIST, temp);
			}
			return 0;
		}

		extern int _handle_mode_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			t_account * acc = conn_get_account(conn);

			std::memset(temp, 0, sizeof(temp));

			if (numparams < 1) {
				irc_send(conn, ERR_NEEDMOREPARAMS, "MODE :Not enough parameters");
				return 0;
			}

			if (params[0][0] == '#') {
				/* Channel mode */
				t_channel * channel;
				char const * ircname = irc_convert_ircname(params[0]);

				/* FIXME: Supports more than one channel in MODE command */
				if (!(channel = conn_get_channel(conn))) {
					std::snprintf(temp, sizeof(temp), "%s :No such channel", params[0]);
					irc_send(conn, ERR_NOSUCHCHANNEL, temp);
					return 0;
				}

				if (numparams == 1) {
					/* FIXME: Send real CHANELMODE flags! */
					std::snprintf(temp, sizeof(temp), "%s +tns", params[0]);
					irc_send(conn, RPL_CHANNELMODEIS, temp);
					return 0;
				}

				if (numparams == 2) {
					if (std::strcmp(params[1], "b") == 0) {
						irc_send_banlist(conn, channel);
						std::snprintf(temp, sizeof(temp), "%s :End of channel ban list", params[0]);
						irc_send(conn, RPL_ENDOFBANLIST, temp);
						return 0;
					}
					else {
						std::snprintf(temp, sizeof(temp), ":%s is unknown mode char to me for %s", params[1], params[0]);
						irc_send(conn, ERR_UNKNOWNMODE, temp);
						return 0;
					}
				}

				/* PELISH: Also tmpOP have setting modes alowed because all new channels have only tmpOP */
				if ((channel_conn_is_tmpOP(channel, conn) != 1) &&
					(account_get_auth_admin(acc, NULL) != 1) && (account_get_auth_admin(acc, ircname) != 1) &&
					(account_get_auth_operator(acc, NULL) != 1) && (account_get_auth_operator(acc, ircname) != 1)) {
					std::snprintf(temp, sizeof(temp), "%s :You're not channel operator", params[0]);
					irc_send(conn, ERR_CHANOPRIVSNEEDED, temp);
					return 0;
				}

				if (std::strcmp(params[1], "+b") == 0) {
					channel_ban_user(channel, params[2]);
					std::snprintf(temp, sizeof(temp), "%s %s %s!*@*", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "-b") == 0) {
					channel_unban_user(channel, params[2]);
					std::snprintf(temp, sizeof(temp), "%s %s %s!*@*", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "+o") == 0) {
					std::snprintf(temp, sizeof(temp), "/op %s", params[2]);
					handle_command(conn, temp);
					std::snprintf(temp, sizeof(temp), "%s %s %s", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "-o") == 0) {
					std::snprintf(temp, sizeof(temp), "/deop %s", params[2]);
					handle_command(conn, temp);
					std::snprintf(temp, sizeof(temp), "%s %s %s", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "+v") == 0) {
					std::snprintf(temp, sizeof(temp), "/voice %s", params[2]);
					handle_command(conn, temp);
					std::snprintf(temp, sizeof(temp), "%s %s %s", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "-v") == 0) {
					std::snprintf(temp, sizeof(temp), "/devoice %s", params[2]);
					handle_command(conn, temp);

					std::snprintf(temp, sizeof(temp), "%s %s %s", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "+i") == 0) {
					/* FIXME: channel will be only for invited */
				}
				else if (std::strcmp(params[1], "+l") == 0) {
					channel_set_max(channel, std::atoi(params[2]));
					std::snprintf(temp, sizeof(temp), "%s %s %s", params[0], params[1], params[2]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else if (std::strcmp(params[1], "-l") == 0) {
					channel_set_max(channel, -1);
					std::snprintf(temp, sizeof(temp), "%s %s", params[0], params[1]);
					channel_message_send(channel, message_type_mode, conn, temp);
				}
				else {
					std::snprintf(temp, sizeof(temp), ":%s is unknown mode char to me for %s", params[1], params[0]);
					irc_send(conn, ERR_UNKNOWNMODE, temp);
				}
			}
			else {
				/* User modes */
				/* FIXME: Support user modes (away, invisible...) */
				irc_send(conn, ERR_UMODEUNKNOWNFLAG, ":Unknown MODE flag");
			}
			return 0;
		}

		extern int _handle_time_command(t_connection * conn, int numparams, char ** params, char * text)
		{
			char temp[MAX_IRC_MESSAGE_LEN] = {}; // PELISH: According to RFC2812
			std::time_t now;
			char const * ircname = server_get_hostname();

			if ((numparams >= 1) && (params[0]))
			{
				if (std::strcmp(params[0], ircname) == 0)
				{
					now = std::time(NULL);
					std::snprintf(temp, sizeof(temp), "%s :%" PRId64, ircname, static_cast<std::int64_t>(now));
					irc_send(conn, RPL_TIME, temp);
				}
				else {
					std::snprintf(temp, sizeof(temp), "%s :No such server", params[0]);
					irc_send(conn, ERR_NOSUCHSERVER, temp);
				}
			}
			else {
				/* RPL_TIME contains time and name of this server */
				now = std::time(NULL);
				std::snprintf(temp, sizeof(temp), "%s :%" PRId64, ircname, static_cast<std::int64_t>(now));
				irc_send(conn, RPL_TIME, temp);
			}
			return 0;
			}

	}

}
