// SPDX-License-Identifier: GPL-2.0-or-later
// irc_internal.h — shared forward declarations for irc/ sub-modules
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#pragma once

#include "common/setup_before.h"
#include "irc.h"

#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>

#include <strings.h>

#include "common/irc_protocol.h"
#include "common/packet.h"
#include "common/eventlog.h"
#include "common/field_sizes.h"
#include "common/bnethash.h"
#include "common/addr.h"
#include "common/tag.h"
#include "common/list.h"
#include "common/util.h"
#include "common/xstring.h"

#include "message.h"
#include "channel.h"
#include "game.h"
#include "connection.h"
#include "server.h"
#include "account.h"
#include "account_wrap.h"
#include "prefs_v3_shim.h"
#include "tick.h"
#include "handle_wol.h"
#include "command_groups.h"
#include "topic.h"
#include "clan.h"
#include "command.h"
#include "anongame_wol.h"
#include "common/setup_after.h"

namespace pvpgn
{

	namespace bnetd
	{

		typedef struct {
			char const * nick;
			char const * user;
			char const * host;
		} t_irc_message_from;

		// irc_send.cpp
		extern int irc_send_cmd(t_connection * conn, char const * command, char const * params);
		extern int irc_send(t_connection * conn, int code, char const * params);
		extern int irc_send_ping(t_connection * conn);
		extern int irc_send_pong(t_connection * conn, char const * params);
		extern int irc_authenticate(t_connection * conn, char const * passhash);
		extern char const * irc_convert_channel(t_channel const * channel, t_connection * c);
		extern char const * irc_convert_ircname(char const * pircname);
		extern char ** irc_get_listelems(char * list);
		extern int irc_unget_listelems(char ** elems);
		extern char ** irc_get_paramelems(char * list);
		extern int irc_unget_paramelems(char ** elems);
		extern char ** irc_get_ladderelems(char * list);
		extern int irc_unget_ladderelems(char ** elems);

		// irc_format.cpp
		extern int irc_message_postformat(t_packet * packet, t_connection const * dest);
		extern int irc_message_format(t_packet * packet, t_message_type type, t_connection * me, t_connection * dst, char const * text, unsigned int dstflags);

		// irc_channel.cpp
		int irc_send_rpl_namreply_internal(t_connection * c, t_channel const * channel);
		extern int irc_send_rpl_namreply(t_connection * c, t_channel const * channel);
		extern int irc_who(t_connection * c, char const * name);
		extern int irc_send_motd(t_connection * conn);
		int irc_welcome(t_connection * conn);

		// irc_commands.cpp
		extern int _handle_nick_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_ping_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_pong_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_join_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int irc_send_topic(t_connection * c, t_channel const * channel);
		extern int _handle_topic_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_kick_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_mode_command(t_connection * conn, int numparams, char ** params, char * text);
		extern int _handle_time_command(t_connection * conn, int numparams, char ** params, char * text);

		// irc_handlers.cpp (originally static — promoted to internal linkage via irc_internal.h)
		int _handle_user_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_pass_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_privmsg_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_notice_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_quit_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_who_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_list_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_names_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_userhost_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_ison_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_whois_command(t_connection * conn, int numparams, char ** params, char * text);
		int _handle_part_command(t_connection * conn, int numparams, char ** params, char * text);

	} // namespace bnetd

} // namespace pvpgn
