// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		static char * irc_message_preformat(t_irc_message_from const * from, char const * command, char const * dest, char const * text)
		{
			char * myfrom;
			char const * mydest = "";
			char const * mytext = "";
			int len;
			char * msg;

			if (!command) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL command");
				return NULL;
			}
			if (from) {
				if ((!from->nick) || (!from->user) || (!from->host)) {
					eventlog(eventlog_level_error, __FUNCTION__, "got malformed from");
					return NULL;
				}
				myfrom = new char[std::strlen(from->nick) + 1 + std::strlen(from->user) + 1 + std::strlen(from->host) + 1]; /* nick + "!" + user + "@" + host + "\0" */
				std::sprintf(myfrom, "%s!%s@%s", from->nick, from->user, from->host);
			}
			else
				myfrom = irc_strdup(server_get_hostname());
			if (dest)
				mydest = dest;

			if (text)
				mytext = text;

			len = 1 + std::strlen(myfrom) + 1 +
				std::strlen(command) + 1 +
				std::strlen(mydest) + 1 +
				1 + std::strlen(mytext) + 1;


			msg = new char[len];

			std::sprintf(msg, ":%s\n%s\n%s\n%s", myfrom, command, mydest, mytext);
			delete[] myfrom;
			return msg;
		}

		extern int irc_message_postformat(t_packet * packet, t_connection const * dest)
		{
			/* the four elements */
			char * e1;
			char * e1_2;
			char * e2;
			char * e3;
			char * e4;
			char const * tname = NULL;
			char const * toname = "AUTH"; /* fallback name */
			const char * temp;

			if (!packet) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL packet");
				return -1;
			}
			if (!dest) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL dest");
				return -1;
			}

			e1 = (char*)packet_get_raw_data(packet, 0);
			e2 = std::strchr(e1, '\n');
			if (!e2) {
				eventlog(eventlog_level_warn, __FUNCTION__, "malformed message (e2 missing)");
				return -1;
			}
			*e2++ = '\0';
			e3 = std::strchr(e2, '\n');
			if (!e3) {
				eventlog(eventlog_level_warn, __FUNCTION__, "malformed message (e3 missing)");
				return -1;
			}
			*e3++ = '\0';
			e4 = std::strchr(e3, '\n');
			if (!e4) {
				eventlog(eventlog_level_warn, __FUNCTION__, "malformed message (e4 missing)");
				return -1;
			}
			*e4++ = '\0';

			if (prefs_v3::hide_addr() && !(account_get_command_groups(conn_get_account(dest)) & command_get_group("/admin-addr")))
			{
				e1_2 = std::strchr(e1, '@');
				if (e1_2)
				{
					*e1_2++ = '\0';
				}
			}
			else
				e1_2 = NULL;

			if (e3[0] == '\0') { /* fill in recipient */
				if ((tname = conn_get_loggeduser(dest)))
					toname = tname;
			}
			else
				toname = e3;

			if (std::strcmp(toname, "\r") == 0) {
				toname = ""; /* HACK: the target field is really empty */
				temp = "";
			}
			else
				temp = " ";

			if (std::strlen(e1) + 1 + std::strlen(e2) + 1 + std::strlen(toname) + std::strlen(temp) + std::strlen(e4) + 2 + 1 <= MAX_IRC_MESSAGE_LEN) {
				char msg[MAX_IRC_MESSAGE_LEN + 1];

				if (e1_2)
					std::sprintf(msg, "%s@hidden %s %s%s%s", e1, e2, toname, temp, e4);
				else
					std::sprintf(msg, "%s %s %s%s%s", e1, e2, toname, temp, e4);

				DEBUG2("[{}] sent \"{}\"", conn_get_socket(dest), msg);
				std::strcat(msg, "\r\n");

				packet_set_size(packet, 0);
				packet_append_data(packet, msg, std::strlen(msg));
				if (tname)
					conn_unget_chatname(dest, tname);
				return 0;
			}
			else {
				/* FIXME: split up message? */
				eventlog(eventlog_level_warn, __FUNCTION__, "maximum IRC message length exceeded");
				if (tname)
					conn_unget_chatname(dest, tname);
				return -1;
			}
		}

		extern int irc_message_format(t_packet * packet, t_message_type type, t_connection * me, t_connection * dst, char const * text, unsigned int dstflags)
		{
			char * msg;
			char const * ctag;
			t_irc_message_from from;

			if (!packet)
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL packet");
				return -1;
			}

			msg = NULL;
			if (me)
				ctag = clienttag_uint_to_str(conn_get_clienttag(me));
			else
				ctag = clienttag_uint_to_str(CLIENTTAG_IIRC_UINT);

			switch (type)
			{
				/* case message_type_adduser: this is sent manually in handle_irc */
			case message_type_adduser:
				/* when we do it somewhere else, then we can also make sure to not get our logs spammed */
				break;
			case message_type_join:
			{
									  t_channel * channel;
									  from.nick = conn_get_chatname(me);
									  from.user = ctag;
									  from.host = addr_num_to_ip_str(conn_get_addr(me));

									  channel = conn_get_channel(me);

									  if (tag_check_wolv2(conn_get_clienttag(dst))) {
										  char temp[MAX_IRC_MESSAGE_LEN];
										  t_clan * clan;
										  unsigned int clanid = 0;
										  std::memset(temp, 0, sizeof(temp));

										  /**
										  *  For WOLv2 the channel JOIN output must be like the following:
										  *  user!WWOL@hostname JOIN :clanID,longIP channelName
										  */

										  clan = account_get_clan(conn_get_account(me));

										  if (clan)
											  clanid = clan_get_clanid(clan);

										  std::sprintf(temp, ":%u,%u", clanid, conn_get_addr(me));
										  msg = irc_message_preformat(&from, "JOIN", temp, irc_convert_channel(channel, dst));
									  }
									  else {
										  msg = irc_message_preformat(&from, "JOIN", "\r", irc_convert_channel(channel, dst));
									  }
									  conn_unget_chatname(me, from.nick);
			}
				break;
			case message_type_part:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "PART", "\r", irc_convert_channel(conn_get_channel(me), dst));
				conn_unget_chatname(me, from.nick);
				break;
			case message_type_talk:
			case message_type_whisper:
			{
										 char const * dest;
										 char temp[MAX_IRC_MESSAGE_LEN];

										 if (me) {
											 from.nick = conn_get_chatname(me);
											 from.host = addr_num_to_ip_str(conn_get_addr(me));
										 }
										 else {
											 from.nick = server_get_hostname();
											 from.host = server_get_hostname();
										 }
										 from.user = ctag;

										 if (type == message_type_talk)
											 dest = irc_convert_channel(conn_get_channel(me), dst); /* FIXME: support more channels and choose right one! */
										 else
											 dest = ""; /* will be replaced with username in postformat */

										 std::sprintf(temp, ":%s", text);

										 if ((conn_get_wol(me) != 1) && (conn_get_wol(dst) == 1) && (conn_wol_get_pageme(dst))
											 && (type == message_type_whisper) && (conn_get_channel(me) != (conn_get_channel(dst))))
											 msg = irc_message_preformat(&from, "PAGE", NULL, temp);
										 else
											 msg = irc_message_preformat(&from, "PRIVMSG", dest, temp);

										 if (me)
											 conn_unget_chatname(me, from.nick);
			}
				break;
			case message_type_emote:
			{
									   char const * dest;
									   char temp[MAX_IRC_MESSAGE_LEN];

									   /* "\001ACTION " + text + "\001" + \0 */

									   /* PELISH: WOLv1, DUNE2000 and RENEGADE shows emotes automaticaly to self */
									   if ((me == dst) && ((tag_check_wolv1(conn_get_clienttag(dst))) ||
										   (conn_get_clienttag(dst) == CLIENTTAG_DUNE2000_UINT) ||
										   (conn_get_clienttag(dst) == CLIENTTAG_RENEGADE_UINT) ||
										   (conn_get_clienttag(dst) == CLIENTTAG_RENGDFDS_UINT)))
										   break;

									   if ((8 + std::strlen(text) + 1 + 1) <= MAX_IRC_MESSAGE_LEN) {
										   std::sprintf(temp, ":\001ACTION %s\001", text);
									   }
									   else {
										   std::sprintf(temp, ":\001ACTION (maximum message length exceeded)\001");
									   }
									   from.nick = conn_get_chatname(me);
									   from.user = ctag;
									   from.host = addr_num_to_ip_str(conn_get_addr(me));
									   /* FIXME: also supports whisper emotes? */
									   dest = irc_convert_channel(conn_get_channel(me), dst); /* FIXME: support more channels and choose right one! */
									   msg = irc_message_preformat(&from, "PRIVMSG", dest, temp);
									   conn_unget_chatname(me, from.nick);
			}
				break;
			case message_type_broadcast:
			case message_type_info:
			case message_type_error:
			{
									   char temp[MAX_IRC_MESSAGE_LEN];
									   std::sprintf(temp, ":%s", text);
									   if (conn_get_wol(dst) == 1) {
										   if ((type == message_type_info) || (type == message_type_error))
											   msg = irc_message_preformat(NULL, "PAGE", NULL, temp);
										   else
											   msg = irc_message_preformat(NULL, "NOTICE", NULL, temp);
									   }
									   else
										   msg = irc_message_preformat(NULL, "NOTICE", NULL, temp);
			}
				break;
			case message_type_channel:
				/* ignore it */
				break;
			case message_type_userflags:
				/* ignore it but maybe will be used for set MODE +o if user is operator
				 * but at this time is this command sended only once when user join
				 * first channel */
				break;
			case message_type_mode:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "MODE", "\r", text);
				conn_unget_chatname(me, from.nick);
				break;
			case message_type_nick:
			{
									  from.nick = conn_get_loggeduser(me);
									  from.host = addr_num_to_ip_str(conn_get_addr(me));
									  from.user = ctag;
									  msg = irc_message_preformat(&from, "NICK", "\r", text);
			}
				break;
			case message_type_notice:
			{
										char temp[MAX_IRC_MESSAGE_LEN];
										std::sprintf(temp, ":%s", text);

										if (me && conn_get_chatname(me))
										{
											from.nick = conn_get_chatname(me);
											from.host = addr_num_to_ip_str(conn_get_addr(me));
											from.user = ctag;
											msg = irc_message_preformat(&from, "NOTICE", "", temp);
										}
										else
										{
											msg = irc_message_preformat(NULL, "NOTICE", "", temp);
										}
			}
				break;
			case message_type_namreply:
			{
										  t_channel * channel;

										  channel = conn_get_channel(me);

										  irc_send_rpl_namreply(dst, channel);
			}
				break;
			case message_type_topic:
			{
									   t_channel * channel;
									   channel = conn_get_channel(me);
									   irc_send_topic(dst, channel);
			}
				break;
			case message_type_kick:
			{
									  char temp[MAX_IRC_MESSAGE_LEN];
									  from.nick = conn_get_chatname(me);
									  from.user = ctag;
									  from.host = addr_num_to_ip_str(conn_get_addr(me));
									  if (text)
										  std::sprintf(temp, "%s :%s", conn_get_chatname(me), text);
									  else
										  std::sprintf(temp, "%s :", conn_get_chatname(me));
									  msg = irc_message_preformat(&from, "KICK", irc_convert_channel(conn_get_channel(me), dst), temp);
									  conn_unget_chatname(me, from.nick);
			}
				break;
			case message_type_quit:
				if (conn_get_clienttag(dst) == CLIENTTAG_IIRC_UINT) {
					char temp[MAX_IRC_MESSAGE_LEN];
					if (text)
						sprintf(temp, ":%s", text);
					else
						sprintf(temp, ":");

					from.nick = conn_get_chatname(me);
					from.host = addr_num_to_ip_str(conn_get_addr(me));
					from.user = ctag;
					msg = irc_message_preformat(&from, "QUIT", "\r", temp);
				}
				else {
					from.nick = conn_get_chatname(me);
					from.user = ctag;
					from.host = addr_num_to_ip_str(conn_get_addr(me));
					msg = irc_message_preformat(&from, "PART", "\r", irc_convert_channel(conn_get_channel(me), dst));
					conn_unget_chatname(me, from.nick);
				}
				break;

				/**
				*  Westwood Online Extensions
				*/
			case message_type_host:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "HOST", "\r", text);
				conn_unget_chatname(me, from.nick);
				break;
			case message_type_invmsg:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "INVMSG", NULL, text);
				conn_unget_chatname(me, from.nick);
				break;
			case message_type_page:
			{
									  char temp[MAX_IRC_MESSAGE_LEN];
									  from.nick = conn_get_chatname(me);
									  from.user = ctag;
									  from.host = addr_num_to_ip_str(conn_get_addr(me));
									  std::sprintf(temp, ":%s", text);
									  msg = irc_message_preformat(&from, "PAGE", NULL, temp);
									  conn_unget_chatname(me, from.nick);
			}
				break;
			case message_wol_joingame:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "JOINGAME", "\r", text);
				conn_unget_chatname(me, from.nick);
				break;
			case message_type_gameopt_talk:
			case message_type_gameopt_whisper:
			{
												 char const * dest;
												 char temp[MAX_IRC_MESSAGE_LEN];

												 if (me) {
													 from.nick = conn_get_chatname(me);
													 from.host = addr_num_to_ip_str(conn_get_addr(me));
												 }
												 else {
													 from.nick = server_get_hostname();
													 from.host = server_get_hostname();
												 }
												 from.user = ctag;

												 if (type == message_type_gameopt_talk)
													 dest = irc_convert_channel(conn_get_channel(me), dst); /* FIXME: support more channels and choose right one! */
												 else
													 dest = ""; /* will be replaced with username in postformat */

												 std::sprintf(temp, ":%s", text);

												 msg = irc_message_preformat(&from, "GAMEOPT", dest, temp);

												 if (me)
													 conn_unget_chatname(me, from.nick);
			}
				break;
			case message_wol_start_game:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "STARTG", NULL, text);
				conn_unget_chatname(me, from.nick);
				break;
			case message_wol_advertr:
				msg = irc_message_preformat(NULL, "ADVERTR", "\r", text);
				break;
			case message_wol_chanchk:
				msg = irc_message_preformat(NULL, "CHANCHK", "\r", text);
				break;
			case message_wol_userip:
				from.nick = conn_get_chatname(me);
				from.user = ctag;
				from.host = addr_num_to_ip_str(conn_get_addr(me));
				msg = irc_message_preformat(&from, "USERIP", "\r", text);
				conn_unget_chatname(me, from.nick);
				break;
			default:
				eventlog(eventlog_level_warn, __FUNCTION__, "{} not yet implemented", type);
				return -1;
			}

			if (msg) {
				packet_append_string(packet, msg);
				delete[] msg;
				return 0;
			}
			return -1;
		}

	}

}
