// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by scripts/dev/split_irc_link.py (plan 15 §4)
#include "irc_internal.h"

namespace pvpgn
{

	namespace bnetd
	{

		int irc_send_rpl_namreply_internal(t_connection * c, t_channel const * channel){
			char temp[MAX_IRC_MESSAGE_LEN];
			char const * ircname;
			int first = 1;
			t_connection * m;

			if (!channel) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL channel");
				return -1;
			}

			std::memset(temp, 0, sizeof(temp));
			ircname = irc_convert_channel(channel, c);
			if (!ircname) {
				eventlog(eventlog_level_error, __FUNCTION__, "channel has NULL ircname");
				return -1;
			}
			/* '@' = secret; '*' = private; '=' = public */
			if ((1 + 1 + std::strlen(ircname) + 2 + 1) <= MAX_IRC_MESSAGE_LEN) {
				std::sprintf(temp, "%c %s :", ((channel_get_permanent(channel)) ? ('=') : ('*')), ircname);
			}
			else {
				eventlog(eventlog_level_warn, __FUNCTION__, "maximum message length exceeded");
				return -1;
			}

			if (!(channel_get_flags(channel) & channel_flags_thevoid))
			for (m = channel_get_first(channel); m; m = channel_get_next()) {
				char const * name = conn_get_chatname(m);
				char flg[5] = "";
				unsigned int flags;

				if (!name)
					continue;
				flags = conn_get_flags(m);
				if (flags & MF_BLIZZARD)
					std::strcat(flg, "@");
				else if ((flags & MF_BNET) || (flags & MF_GAVEL))
					std::strcat(flg, "%");
				else if (flags & MF_VOICE)
					std::strcat(flg, "+");
				if ((std::strlen(temp) + ((!first) ? (1) : (0)) + std::strlen(flg) + std::strlen(name) + 1) <= sizeof(temp)) {
					if (!first) std::strcat(temp, " ");
					if (conn_get_wol(c) == 1) {
						char _temp[MAX_IRC_MESSAGE_LEN];
						t_game * game = conn_get_game(m);
						if ((first) && ((std::strcmp(ircname, "#Lob_38_0") == 0) ||
							(std::strcmp(ircname, "#Lob_39_0") == 0) ||
							(std::strcmp(ircname, "#Lob_40_0") == 0))) {

							std::sprintf(_temp, "@matchbot,0,0 ");
							std::strcat(temp, _temp);
							first = 0;

						}

						if ((game) && (game_get_channel(game) == channel)) {
							if (game_get_owner(game) == m) {
								/* PELISH: Only game owners will have OP flag (this prevent official OP to be normal player) */
								std::strcat(temp, "@");
							}
						}
						else {
							if ((flags & MF_BNET) || (flags & MF_GAVEL))
								std::sprintf(flg, "@");  /* PELISH: WOL does not understand to '%' char so we using '@' for TempOP too */
							std::strcat(temp, flg);
						}
						if (tag_check_wolv2(conn_get_clienttag(c))) {
							/* BATTLECLAN Support */
							std::memset(_temp, 0, sizeof(_temp));
							t_clan * clan = account_get_clan(conn_get_account(m));
							unsigned int clanid = 0;

							if (clan)
								clanid = clan_get_clanid(clan);

							std::sprintf(_temp, "%s,%u,%u", name, clanid, conn_get_addr(m));
							std::strcat(temp, _temp);
						}
						else {
							std::strcat(temp, name);
						}
					}
					else {
						std::strcat(temp, flg);
						std::strcat(temp, name);
					}

					first = 0;
				}
				conn_unget_chatname(m, name);
			}
			irc_send(c, RPL_NAMREPLY, temp);

			return 0;
		}

		extern int irc_send_rpl_namreply(t_connection * c, t_channel const * channel)
		{
			char temp[MAX_IRC_MESSAGE_LEN];
			char const * ircname;

			if (!c) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}

			if (channel) {
				ircname = irc_convert_channel(channel, c);
				if (!ircname) {
					eventlog(eventlog_level_error, __FUNCTION__, "channel has NULL ircname");
					return -1;
				}
				irc_send_rpl_namreply_internal(c, channel);
				std::sprintf(temp, "%.32s :End of NAMES list", ircname);
			}
			else {
				for (t_channel const* ch : channellist())
				{
					irc_send_rpl_namreply_internal(c, ch);
				}
				std::sprintf(temp, "* :End of NAMES list");
			}

			irc_send(c, RPL_ENDOFNAMES, temp);
			return 0;
		}

		static int irc_who_connection(t_connection * dest, t_connection * c)
		{
			t_account * a;
			char const * tempuser;
			char const * tempowner;
			char const * tempname;
			char const * tempip;
			char const * tempflags = "@"; /* FIXME: that's dumb */
			char temp[MAX_IRC_MESSAGE_LEN];
			char const * tempchannel;

			if (!dest) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL destination");
				return -1;
			}
			if (!c) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}
			a = conn_get_account(c);
			if (!(tempuser = clienttag_uint_to_str(conn_get_clienttag(c))))
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL clienttag (tempuser)");
				return -1;
			}
			if (!(tempowner = account_get_ll_owner(a)))
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL ll_owner (tempowner)");
				return -1;
			}
			if (!(tempname = conn_get_username(c)))
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL username (tempname)");
				return -1;
			}
			if (!(tempip = addr_num_to_ip_str(conn_get_addr(c))))
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL addr (tempip)");
				return -1;
			}
			if (!(tempchannel = irc_convert_channel(conn_get_channel(c), c)))
			{
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL channel (tempchannel)");
				return -1;
			}
			if ((std::strlen(tempchannel) + 1 + std::strlen(tempuser) + 1 + std::strlen(tempip) + 1 + std::strlen(server_get_hostname()) + 1 + std::strlen(tempname) + 1 + 1 + std::strlen(tempflags) + 4 + std::strlen(tempowner) + 1) > MAX_IRC_MESSAGE_LEN) {
				eventlog(eventlog_level_info, __FUNCTION__, "WHO reply too long - skip");
				return -1;
			}
			else
				std::sprintf(temp, "%s %s %s %s %s %c%s :0 %s", tempchannel, tempuser, tempip, server_get_hostname(), tempname, 'H', tempflags, tempowner);
			irc_send(dest, RPL_WHOREPLY, temp);
			return 0;
		}

		extern int irc_who(t_connection * c, char const * name)
		{
			/* FIXME: support wildcards! */

			if (!c) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}
			if (!name) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL name");
				return -1;
			}
			if ((name[0] == '#') || (name[0] == '&') || (name[0] == '!')) {
				/* it's a channel */
				t_connection * info;
				t_channel * channel;
				char const * ircname;

				ircname = irc_convert_ircname(name);
				channel = channellist_find_channel_by_name(ircname, NULL, NULL);
				if (!channel) {
					char temp[MAX_IRC_MESSAGE_LEN];

					if ((std::strlen(":No such channel") + 1 + std::strlen(name) + 1) <= MAX_IRC_MESSAGE_LEN) {
						std::sprintf(temp, ":No such channel %s", name);
						irc_send(c, ERR_NOSUCHCHANNEL, temp);
					}
					else {
						irc_send(c, ERR_NOSUCHCHANNEL, ":No such channel");
					}
					return 0;
				}
				for (info = channel_get_first(channel); info; info = channel_get_next()) {
					irc_who_connection(c, info);
				}
			}
			else {
				/* it's just one user */
				t_connection * info;

				if ((info = connlist_find_connection_by_accountname(name)))
					return irc_who_connection(c, info);
			}
			return 0;
		}

		extern int irc_send_motd(t_connection * conn)
		{
			char const * tempname;
			char const * filename;
			std::FILE *fp;
			char * line, *formatted_line;
			char send_line[MAX_IRC_MESSAGE_LEN];
			char motd_failed = 0;
			bool first = true;

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}

			tempname = conn_get_loggeduser(conn);

			if ((filename = prefs_v3::motdfile())) {
				if ((fp = std::fopen(filename, "r"))) {
					while ((line = file_get_line(fp))) {
						if ((formatted_line = message_format_line(conn, line))) {
							formatted_line[0] = ' ';
							std::sprintf(send_line, ":-%s", formatted_line);
							if (first) {
								irc_send(conn, RPL_MOTDSTART, send_line);
								first = false;
							}
							else
								irc_send(conn, RPL_MOTD, send_line);
							delete[] formatted_line;
						}
					}

					file_get_line(NULL); // clear file_get_line buffer
					std::fclose(fp);
				}
				else
					motd_failed = 1;
			}
			else
				motd_failed = 1;

			if (motd_failed) {
				irc_send(conn, RPL_MOTDSTART, ":- Failed to load motd, sending default motd              ");
				irc_send(conn, RPL_MOTD, ":- ====================================================== ");
				irc_send(conn, RPL_MOTD, ":-                 http://www.pvpgn.pro                   ");
				irc_send(conn, RPL_MOTD, ":- ====================================================== ");
			}
			irc_send(conn, RPL_ENDOFMOTD, ":End of /MOTD command");
			return 0;
		}

		int irc_welcome(t_connection * conn){
			if (conn_get_wol(conn)) {
				handle_wol_welcome(conn);
				return 0;
			}

			// TODO(Phase3): handled by v3 IrcFsm — legacy welcome inlined from handle_irc.cpp
			char temp[MAX_IRC_MESSAGE_LEN];
			std::time_t temptime;
			char const * tempname;
			char const * temptimestr;

			if (!conn) {
				eventlog(eventlog_level_error, __FUNCTION__, "got NULL connection");
				return -1;
			}

			tempname = conn_get_loggeduser(conn);

			if ((34 + std::strlen(tempname) + 1) <= MAX_IRC_MESSAGE_LEN)
				std::sprintf(temp, ":Welcome to the %s IRC Network %s", prefs_v3::irc_network_name(), tempname);
			else
				std::sprintf(temp, ":Maximum length exceeded");
			irc_send(conn, RPL_WELCOME, temp);

			if ((14 + std::strlen(server_get_hostname()) + 10 + std::strlen(PVPGN_SOFTWARE " " PVPGN_VERSION) + 1) <= MAX_IRC_MESSAGE_LEN)
				std::sprintf(temp, ":Your host is %s, running " PVPGN_SOFTWARE " " PVPGN_VERSION, server_get_hostname());
			else
				std::sprintf(temp, ":Maximum length exceeded");
			irc_send(conn, RPL_YOURHOST, temp);

			temptime = server_get_starttime(); /* FIXME: This should be build time */
			temptimestr = std::ctime(&temptime);
			if ((25 + std::strlen(temptimestr) + 1) <= MAX_IRC_MESSAGE_LEN)
				std::sprintf(temp, ":This server was created %s", temptimestr); /* FIXME: is ctime() portable? */
			else
				std::sprintf(temp, ":Maximum length exceeded");
			irc_send(conn, RPL_CREATED, temp);

			/* we don't give mode information on MYINFO we give it on ISUPPORT */
			if ((std::strlen(server_get_hostname()) + 7 + std::strlen(PVPGN_SOFTWARE " " PVPGN_VERSION) + 9 + 1) <= MAX_IRC_MESSAGE_LEN)
				std::sprintf(temp, "%s " PVPGN_SOFTWARE " " PVPGN_VERSION " - -", server_get_hostname());
			else
				std::sprintf(temp, ":Maximum length exceeded");
			irc_send(conn, RPL_MYINFO, temp);

			std::sprintf(temp, "NICKLEN=%d TOPICLEN=%d CHANNELLEN=%d PREFIX=%s CHANTYPES=" CHANNEL_TYPE " NETWORK=%s IRCD=" PVPGN_SOFTWARE,
				MAX_CHARNAME_LEN, MAX_TOPIC_LEN, MAX_CHANNELNAME_LEN, CHANNEL_PREFIX, prefs_v3::irc_network_name());

			irc_send(conn, RPL_ISUPPORT, temp);

			irc_send_motd(conn);

			message_send_text(conn, message_type_notice, NULL, "This is an experimental service");

			conn_set_state(conn, conn_state_bot_password);

			if (conn_get_ircpass(conn)) {
				message_send_text(conn, message_type_notice, NULL, "Trying to authenticate with PASS ...");
				irc_authenticate(conn, conn_get_ircpass(conn));
			}
			else {
				message_send_text(conn, message_type_notice, NULL, "No PASS command received. Please identify yourself by /msg NICKSERV identify <password>.");
			}
			return 0;
		}

	}

}
